# Simply trigger the workflow to start the rollout schedule.

timeout: 60s

steps:
- name: 'google/cloud-sdk:alpine'
  args:
    - 'bash'
    - '-c'
    - 'gcloud workflows execute workflow-gradually-rollout$_TEST_SUFFIX
        --project=$PROJECT_ID
        --data="{
          \"rolloutPhase\":{$_ROLLOUT_PHASES},
          \"tools\":\"gce_vm_image_import;gce_vm_image_export;gce_onestep_image_import;gce_ovf_import;gce_ovf_export;gce_windows_upgrade\",
          \"tagName\":\"$TAG_NAME\",
          \"waitPeriod\":\"$_WAIT_PERIOD\",
          \"skipValidation\":\"$_SKIP_VALIDATION\"
        }"'
  env: ['CGO_ENABLED=0']
