dist: trusty
sudo: false
language: go

go:
  - 1.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go vet ./...
  - ./.travis.gofmt.sh
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

