steps:
# Build docker container.
- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-d', './daisy/...']
  env: ['PROJECT_ROOT=daisy']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', './daisy']
  env: ['PROJECT_ROOT=daisy', 'CGO_ENABLED=0']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/daisy:latest', '--file=Dockerfile.daisy', '.']

# Build Windows binary.
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o=windows/daisy.exe', './daisy/daisy.go']
  env: ['GOOS=windows', 'PROJECT_ROOT=daisy']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './windows/daisy.exe', 'gs://compute-image-tools/latest/windows/daisy.exe']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['acl', 'ch', '-u', 'AllUsers:R', 'gs://compute-image-tools/latest/windows/daisy.exe']

# Build OSX binary.
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o=darwin/daisy', './daisy/daisy.go']
  env: ['GOOS=darwin', 'PROJECT_ROOT=daisy']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './darwin/daisy', 'gs://compute-image-tools/latest/darwin/daisy']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['acl', 'ch', '-u', 'AllUsers:R', 'gs://compute-image-tools/latest/darwin/daisy']

# Build Linux binary.
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o=linux/daisy', './daisy/daisy.go']
  env: ['PROJECT_ROOT=daisy']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './linux/daisy', 'gs://compute-image-tools/latest/linux/daisy']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['acl', 'ch', '-u', 'AllUsers:R', 'gs://compute-image-tools/latest/linux/daisy']

images: ['gcr.io/$PROJECT_ID/daisy:latest']
