# We use this image just for ca-certificates.crt
FROM gcr.io/distroless/base

FROM scratch

COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY linux/gce_image_publish /gce_image_publish

ENTRYPOINT ["/gce_image_publish"]
