timeout: 3600s

options:
  env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  volumes:
  - name: go-pkg
    path: /go/pkg
  - name: go-src
    path: /go/src

steps:
- id: gce-windows-upgrade-tests
  name: 'gcr.io/kaniko-project/executor:v0.22.0'
  args:
  - --destination=gcr.io/$PROJECT_ID/gce-windows-upgrade-tests:latest
  - --destination=gcr.io/$PROJECT_ID/gce-windows-upgrade-tests:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_windows_upgrade_tests.Dockerfile
  - --build-arg=PROJECT_ID=$PROJECT_ID
