timeout: 3600s

options:
  env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  volumes:
  - name: go-pkg
    path: /go/pkg
  - name: go-src
    path: /go/src

steps:
- id: e2e-test-base
  name: 'gcr.io/kaniko-project/executor:v0.22.0'
  args:
  - --destination=gcr.io/$PROJECT_ID/e2e-test-base:latest
  - --destination=gcr.io/$PROJECT_ID/e2e-test-base:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=e2e_test_base.Dockerfile
- id: gce-image-import-export-tests
  name: 'gcr.io/kaniko-project/executor:v0.22.0'
  args:
  - --destination=gcr.io/$PROJECT_ID/gce-image-import-export-tests:latest
  - --destination=gcr.io/$PROJECT_ID/gce-image-import-export-tests:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_image_import_export_tests.Dockerfile
  - --build-arg=PROJECT_ID=$PROJECT_ID
- id: gce-ovf-import-tests
  name: 'gcr.io/kaniko-project/executor:v0.22.0'
  args:
  - --destination=gcr.io/$PROJECT_ID/gce-ovf-import-tests:latest
  - --destination=gcr.io/$PROJECT_ID/gce-ovf-import-tests:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_ovf_import_tests.Dockerfile
  - --build-arg=PROJECT_ID=$PROJECT_ID
- id: gce-ovf-export-tests
  name: 'gcr.io/kaniko-project/executor:v0.22.0'
  args:
  - --destination=gcr.io/$PROJECT_ID/gce-ovf-export-tests:latest
  - --destination=gcr.io/$PROJECT_ID/gce-ovf-export-tests:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_ovf_export_tests.Dockerfile
  - --build-arg=PROJECT_ID=$PROJECT_ID
- id: gce-windows-upgrade-tests
  name: 'gcr.io/kaniko-project/executor:v0.22.0'
  args:
  - --destination=gcr.io/$PROJECT_ID/gce-windows-upgrade-tests:latest
  - --destination=gcr.io/$PROJECT_ID/gce-windows-upgrade-tests:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_windows_upgrade_tests.Dockerfile
  - --build-arg=PROJECT_ID=$PROJECT_ID
