// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/osconfig/v1alpha1/os_configs.proto

package osconfig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Type of archive. Deb indicates that the archive contains binary files.
// Deb-src indicates that the archive contains source files.
type AptRepository_ArchiveType int32

const (
	// Unspecified.
	AptRepository_ARCHIVE_TYPE_UNSPECIFIED AptRepository_ArchiveType = 0
	// Deb.
	AptRepository_DEB AptRepository_ArchiveType = 1
	// Deb-src.
	AptRepository_DEB_SRC AptRepository_ArchiveType = 2
)

var AptRepository_ArchiveType_name = map[int32]string{
	0: "ARCHIVE_TYPE_UNSPECIFIED",
	1: "DEB",
	2: "DEB_SRC",
}

var AptRepository_ArchiveType_value = map[string]int32{
	"ARCHIVE_TYPE_UNSPECIFIED": 0,
	"DEB":     1,
	"DEB_SRC": 2,
}

func (x AptRepository_ArchiveType) String() string {
	return proto.EnumName(AptRepository_ArchiveType_name, int32(x))
}

func (AptRepository_ArchiveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{7, 0}
}

// An OS Config resource describing a set of OS configs that should be set
// on a group of instances.
type OsConfig struct {
	// Identifying name for this OsConfig.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the OsConfig. Length of the description is limited
	// to 1024 characters.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Output only. Time this OsConfig was created.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. Last time this OsConfig was updated.
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Represents cloud resource labels.
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Optional package manager configurations for apt.
	Apt *AptPackageConfig `protobuf:"bytes,6,opt,name=apt,proto3" json:"apt,omitempty"`
	// Optional package manager configurations for yum.
	Yum *YumPackageConfig `protobuf:"bytes,7,opt,name=yum,proto3" json:"yum,omitempty"`
	// Optional package manager configurations for windows.
	Goo *GooPackageConfig `protobuf:"bytes,8,opt,name=goo,proto3" json:"goo,omitempty"`
	// Optional Windows Update configurations.
	WindowsUpdate *WindowsUpdateConfig `protobuf:"bytes,9,opt,name=windows_update,json=windowsUpdate,proto3" json:"windows_update,omitempty"`
	// Optional package manager configuration for zypper.
	Zypper               *ZypperPackageConfig `protobuf:"bytes,10,opt,name=zypper,proto3" json:"zypper,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OsConfig) Reset()         { *m = OsConfig{} }
func (m *OsConfig) String() string { return proto.CompactTextString(m) }
func (*OsConfig) ProtoMessage()    {}
func (*OsConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{0}
}
func (m *OsConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OsConfig.Unmarshal(m, b)
}
func (m *OsConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OsConfig.Marshal(b, m, deterministic)
}
func (m *OsConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OsConfig.Merge(m, src)
}
func (m *OsConfig) XXX_Size() int {
	return xxx_messageInfo_OsConfig.Size(m)
}
func (m *OsConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OsConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OsConfig proto.InternalMessageInfo

func (m *OsConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OsConfig) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *OsConfig) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *OsConfig) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *OsConfig) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *OsConfig) GetApt() *AptPackageConfig {
	if m != nil {
		return m.Apt
	}
	return nil
}

func (m *OsConfig) GetYum() *YumPackageConfig {
	if m != nil {
		return m.Yum
	}
	return nil
}

func (m *OsConfig) GetGoo() *GooPackageConfig {
	if m != nil {
		return m.Goo
	}
	return nil
}

func (m *OsConfig) GetWindowsUpdate() *WindowsUpdateConfig {
	if m != nil {
		return m.WindowsUpdate
	}
	return nil
}

func (m *OsConfig) GetZypper() *ZypperPackageConfig {
	if m != nil {
		return m.Zypper
	}
	return nil
}

// A list of packages to install, remove, and their repos for a given
// package manager type.
type AptPackageConfig struct {
	// Packages to install.
	// apt-get update && apt-get -y install package1 package2 package3
	PackageInstalls []*Package `protobuf:"bytes,1,rep,name=package_installs,json=packageInstalls,proto3" json:"package_installs,omitempty"`
	// Packages to remove.
	// apt-get -y remove package1 package2 package3
	PackageRemovals []*Package `protobuf:"bytes,2,rep,name=package_removals,json=packageRemovals,proto3" json:"package_removals,omitempty"`
	// Package repositories to configure in the package manager. The instance
	// likely already has some defaults set and duplicates are acceptable but
	// ignored.
	Repositories         []*AptRepository `protobuf:"bytes,3,rep,name=repositories,proto3" json:"repositories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AptPackageConfig) Reset()         { *m = AptPackageConfig{} }
func (m *AptPackageConfig) String() string { return proto.CompactTextString(m) }
func (*AptPackageConfig) ProtoMessage()    {}
func (*AptPackageConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{1}
}
func (m *AptPackageConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AptPackageConfig.Unmarshal(m, b)
}
func (m *AptPackageConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AptPackageConfig.Marshal(b, m, deterministic)
}
func (m *AptPackageConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AptPackageConfig.Merge(m, src)
}
func (m *AptPackageConfig) XXX_Size() int {
	return xxx_messageInfo_AptPackageConfig.Size(m)
}
func (m *AptPackageConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AptPackageConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AptPackageConfig proto.InternalMessageInfo

func (m *AptPackageConfig) GetPackageInstalls() []*Package {
	if m != nil {
		return m.PackageInstalls
	}
	return nil
}

func (m *AptPackageConfig) GetPackageRemovals() []*Package {
	if m != nil {
		return m.PackageRemovals
	}
	return nil
}

func (m *AptPackageConfig) GetRepositories() []*AptRepository {
	if m != nil {
		return m.Repositories
	}
	return nil
}

// A list of packages to install, remove, and their repos for a given
// package manager type.
type YumPackageConfig struct {
	// Packages to install.
	// yum -y install package1 package2 package3
	PackageInstalls []*Package `protobuf:"bytes,1,rep,name=package_installs,json=packageInstalls,proto3" json:"package_installs,omitempty"`
	// Packages to remove.
	// yum -y remove package1 package2 package3
	PackageRemovals []*Package `protobuf:"bytes,2,rep,name=package_removals,json=packageRemovals,proto3" json:"package_removals,omitempty"`
	// Package repositories to configure in the package manager. The instance
	// likely already has some defaults set and duplicates are acceptable but
	// ignored.
	Repositories         []*YumRepository `protobuf:"bytes,3,rep,name=repositories,proto3" json:"repositories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *YumPackageConfig) Reset()         { *m = YumPackageConfig{} }
func (m *YumPackageConfig) String() string { return proto.CompactTextString(m) }
func (*YumPackageConfig) ProtoMessage()    {}
func (*YumPackageConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{2}
}
func (m *YumPackageConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YumPackageConfig.Unmarshal(m, b)
}
func (m *YumPackageConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YumPackageConfig.Marshal(b, m, deterministic)
}
func (m *YumPackageConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YumPackageConfig.Merge(m, src)
}
func (m *YumPackageConfig) XXX_Size() int {
	return xxx_messageInfo_YumPackageConfig.Size(m)
}
func (m *YumPackageConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_YumPackageConfig.DiscardUnknown(m)
}

var xxx_messageInfo_YumPackageConfig proto.InternalMessageInfo

func (m *YumPackageConfig) GetPackageInstalls() []*Package {
	if m != nil {
		return m.PackageInstalls
	}
	return nil
}

func (m *YumPackageConfig) GetPackageRemovals() []*Package {
	if m != nil {
		return m.PackageRemovals
	}
	return nil
}

func (m *YumPackageConfig) GetRepositories() []*YumRepository {
	if m != nil {
		return m.Repositories
	}
	return nil
}

// A list of packages to install, remove, and their repos for a given
// package manager type.
type ZypperPackageConfig struct {
	// Packages to install.
	// zypper install package1 package2 package3
	PackageInstalls []*Package `protobuf:"bytes,1,rep,name=package_installs,json=packageInstalls,proto3" json:"package_installs,omitempty"`
	// Packages to remove.
	// zypper rm package1 package2
	PackageRemovals []*Package `protobuf:"bytes,2,rep,name=package_removals,json=packageRemovals,proto3" json:"package_removals,omitempty"`
	// Package repositories to configure in the package manager. The instance
	// likely already has some defaults set and duplicates are acceptable but
	// ignored.
	Repositories         []*ZypperRepository `protobuf:"bytes,3,rep,name=repositories,proto3" json:"repositories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ZypperPackageConfig) Reset()         { *m = ZypperPackageConfig{} }
func (m *ZypperPackageConfig) String() string { return proto.CompactTextString(m) }
func (*ZypperPackageConfig) ProtoMessage()    {}
func (*ZypperPackageConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{3}
}
func (m *ZypperPackageConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZypperPackageConfig.Unmarshal(m, b)
}
func (m *ZypperPackageConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZypperPackageConfig.Marshal(b, m, deterministic)
}
func (m *ZypperPackageConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZypperPackageConfig.Merge(m, src)
}
func (m *ZypperPackageConfig) XXX_Size() int {
	return xxx_messageInfo_ZypperPackageConfig.Size(m)
}
func (m *ZypperPackageConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ZypperPackageConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ZypperPackageConfig proto.InternalMessageInfo

func (m *ZypperPackageConfig) GetPackageInstalls() []*Package {
	if m != nil {
		return m.PackageInstalls
	}
	return nil
}

func (m *ZypperPackageConfig) GetPackageRemovals() []*Package {
	if m != nil {
		return m.PackageRemovals
	}
	return nil
}

func (m *ZypperPackageConfig) GetRepositories() []*ZypperRepository {
	if m != nil {
		return m.Repositories
	}
	return nil
}

// A list of packages to install, remove, and their repos for a given
// package manager type.
type GooPackageConfig struct {
	// Packages to install.
	// googet -noconfirm install package1 package2 package3
	PackageInstalls []*Package `protobuf:"bytes,1,rep,name=package_installs,json=packageInstalls,proto3" json:"package_installs,omitempty"`
	// Packages to remove.
	// googet -noconfirm remove package1 package2 package3
	PackageRemovals []*Package `protobuf:"bytes,2,rep,name=package_removals,json=packageRemovals,proto3" json:"package_removals,omitempty"`
	// Package repositories to configure in the package manager. The instance
	// likely already has some defaults set and duplicates are acceptable but
	// ignored.
	Repositories         []*GooRepository `protobuf:"bytes,3,rep,name=repositories,proto3" json:"repositories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GooPackageConfig) Reset()         { *m = GooPackageConfig{} }
func (m *GooPackageConfig) String() string { return proto.CompactTextString(m) }
func (*GooPackageConfig) ProtoMessage()    {}
func (*GooPackageConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{4}
}
func (m *GooPackageConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GooPackageConfig.Unmarshal(m, b)
}
func (m *GooPackageConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GooPackageConfig.Marshal(b, m, deterministic)
}
func (m *GooPackageConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GooPackageConfig.Merge(m, src)
}
func (m *GooPackageConfig) XXX_Size() int {
	return xxx_messageInfo_GooPackageConfig.Size(m)
}
func (m *GooPackageConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GooPackageConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GooPackageConfig proto.InternalMessageInfo

func (m *GooPackageConfig) GetPackageInstalls() []*Package {
	if m != nil {
		return m.PackageInstalls
	}
	return nil
}

func (m *GooPackageConfig) GetPackageRemovals() []*Package {
	if m != nil {
		return m.PackageRemovals
	}
	return nil
}

func (m *GooPackageConfig) GetRepositories() []*GooRepository {
	if m != nil {
		return m.Repositories
	}
	return nil
}

// Configuration settings for the Windows update.
type WindowsUpdateConfig struct {
	// Optional URI of Windows update server. This sets the registry value
	// `WUServer` under `HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate`.
	WindowsUpdateServerUri string   `protobuf:"bytes,9,opt,name=windows_update_server_uri,json=windowsUpdateServerUri,proto3" json:"windows_update_server_uri,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *WindowsUpdateConfig) Reset()         { *m = WindowsUpdateConfig{} }
func (m *WindowsUpdateConfig) String() string { return proto.CompactTextString(m) }
func (*WindowsUpdateConfig) ProtoMessage()    {}
func (*WindowsUpdateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{5}
}
func (m *WindowsUpdateConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowsUpdateConfig.Unmarshal(m, b)
}
func (m *WindowsUpdateConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowsUpdateConfig.Marshal(b, m, deterministic)
}
func (m *WindowsUpdateConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowsUpdateConfig.Merge(m, src)
}
func (m *WindowsUpdateConfig) XXX_Size() int {
	return xxx_messageInfo_WindowsUpdateConfig.Size(m)
}
func (m *WindowsUpdateConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowsUpdateConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WindowsUpdateConfig proto.InternalMessageInfo

func (m *WindowsUpdateConfig) GetWindowsUpdateServerUri() string {
	if m != nil {
		return m.WindowsUpdateServerUri
	}
	return ""
}

// Package is a reference to the actual package to be installed or removed.
type Package struct {
	// The name of the package.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{6}
}
func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Represents a single apt package repository. These will be added to a repo
// file that will be managed at /etc/apt/sources.list.d/google_osconfig.list
type AptRepository struct {
	// Type of archive files in this repository. Unspecified will default to DEB.
	ArchiveType AptRepository_ArchiveType `protobuf:"varint,1,opt,name=archive_type,json=archiveType,proto3,enum=google.cloud.osconfig.v1alpha1.AptRepository_ArchiveType" json:"archive_type,omitempty"`
	// URI for this repository.
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// Distribution of this repository.
	Distribution string `protobuf:"bytes,3,opt,name=distribution,proto3" json:"distribution,omitempty"`
	// List of components for this repository. Must contain at least one item.
	Components []string `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	// Optional. URI of the key file for this repository. The agent will ensure
	// that this key has been downloaded.
	KeyUri               string   `protobuf:"bytes,5,opt,name=key_uri,json=keyUri,proto3" json:"key_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AptRepository) Reset()         { *m = AptRepository{} }
func (m *AptRepository) String() string { return proto.CompactTextString(m) }
func (*AptRepository) ProtoMessage()    {}
func (*AptRepository) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{7}
}
func (m *AptRepository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AptRepository.Unmarshal(m, b)
}
func (m *AptRepository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AptRepository.Marshal(b, m, deterministic)
}
func (m *AptRepository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AptRepository.Merge(m, src)
}
func (m *AptRepository) XXX_Size() int {
	return xxx_messageInfo_AptRepository.Size(m)
}
func (m *AptRepository) XXX_DiscardUnknown() {
	xxx_messageInfo_AptRepository.DiscardUnknown(m)
}

var xxx_messageInfo_AptRepository proto.InternalMessageInfo

func (m *AptRepository) GetArchiveType() AptRepository_ArchiveType {
	if m != nil {
		return m.ArchiveType
	}
	return AptRepository_ARCHIVE_TYPE_UNSPECIFIED
}

func (m *AptRepository) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *AptRepository) GetDistribution() string {
	if m != nil {
		return m.Distribution
	}
	return ""
}

func (m *AptRepository) GetComponents() []string {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *AptRepository) GetKeyUri() string {
	if m != nil {
		return m.KeyUri
	}
	return ""
}

// Represents a single yum package repository. These will be added to a repo
// file that will be managed a /etc/yum.repos.d/google_osconfig.repo
type YumRepository struct {
	// Required. A one word, unique name for this repository. This will be
	// the `repo id` in the yum config file and also the `display_name` if
	// `display_name` is omitted.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional. If omitted, the id will be used for the name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Required. The location of the repository directory.
	BaseUrl string `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// Optional. URIs of GPG keys.
	GpgKeys              []string `protobuf:"bytes,4,rep,name=gpg_keys,json=gpgKeys,proto3" json:"gpg_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YumRepository) Reset()         { *m = YumRepository{} }
func (m *YumRepository) String() string { return proto.CompactTextString(m) }
func (*YumRepository) ProtoMessage()    {}
func (*YumRepository) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{8}
}
func (m *YumRepository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YumRepository.Unmarshal(m, b)
}
func (m *YumRepository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YumRepository.Marshal(b, m, deterministic)
}
func (m *YumRepository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YumRepository.Merge(m, src)
}
func (m *YumRepository) XXX_Size() int {
	return xxx_messageInfo_YumRepository.Size(m)
}
func (m *YumRepository) XXX_DiscardUnknown() {
	xxx_messageInfo_YumRepository.DiscardUnknown(m)
}

var xxx_messageInfo_YumRepository proto.InternalMessageInfo

func (m *YumRepository) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *YumRepository) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *YumRepository) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *YumRepository) GetGpgKeys() []string {
	if m != nil {
		return m.GpgKeys
	}
	return nil
}

// Represents a single zypper package repository. These will be added to a repo
// file that will be managed a /etc/zypp/repos.d/google_osconfig.repo
type ZypperRepository struct {
	// Required. A one word, unique name for this repository. This will be
	// the `repo id` in the zypper config file and also the `display_name` if
	// `display_name` is omitted.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional. If omitted, the id will be used for the name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Required. The location of the repository directory.
	BaseUrl string `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// Optional. URIs of GPG keys.
	GpgKeys              []string `protobuf:"bytes,4,rep,name=gpg_keys,json=gpgKeys,proto3" json:"gpg_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZypperRepository) Reset()         { *m = ZypperRepository{} }
func (m *ZypperRepository) String() string { return proto.CompactTextString(m) }
func (*ZypperRepository) ProtoMessage()    {}
func (*ZypperRepository) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{9}
}
func (m *ZypperRepository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZypperRepository.Unmarshal(m, b)
}
func (m *ZypperRepository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZypperRepository.Marshal(b, m, deterministic)
}
func (m *ZypperRepository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZypperRepository.Merge(m, src)
}
func (m *ZypperRepository) XXX_Size() int {
	return xxx_messageInfo_ZypperRepository.Size(m)
}
func (m *ZypperRepository) XXX_DiscardUnknown() {
	xxx_messageInfo_ZypperRepository.DiscardUnknown(m)
}

var xxx_messageInfo_ZypperRepository proto.InternalMessageInfo

func (m *ZypperRepository) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ZypperRepository) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ZypperRepository) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *ZypperRepository) GetGpgKeys() []string {
	if m != nil {
		return m.GpgKeys
	}
	return nil
}

// Represents a Goo package repository. These will be added to a repo file that
// will be managed at C:/ProgramData/GooGet/repos/google_osconfig.repo
type GooRepository struct {
	// The name of the repository.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The url of the repository.
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GooRepository) Reset()         { *m = GooRepository{} }
func (m *GooRepository) String() string { return proto.CompactTextString(m) }
func (*GooRepository) ProtoMessage()    {}
func (*GooRepository) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{10}
}
func (m *GooRepository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GooRepository.Unmarshal(m, b)
}
func (m *GooRepository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GooRepository.Marshal(b, m, deterministic)
}
func (m *GooRepository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GooRepository.Merge(m, src)
}
func (m *GooRepository) XXX_Size() int {
	return xxx_messageInfo_GooRepository.Size(m)
}
func (m *GooRepository) XXX_DiscardUnknown() {
	xxx_messageInfo_GooRepository.DiscardUnknown(m)
}

var xxx_messageInfo_GooRepository proto.InternalMessageInfo

func (m *GooRepository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GooRepository) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// A request message for creating an OsConfig.
type CreateOsConfigRequest struct {
	// The resource name of the parent.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The OsConfig to create.
	OsConfig             *OsConfig `protobuf:"bytes,2,opt,name=os_config,json=osConfig,proto3" json:"os_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateOsConfigRequest) Reset()         { *m = CreateOsConfigRequest{} }
func (m *CreateOsConfigRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOsConfigRequest) ProtoMessage()    {}
func (*CreateOsConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{11}
}
func (m *CreateOsConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOsConfigRequest.Unmarshal(m, b)
}
func (m *CreateOsConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOsConfigRequest.Marshal(b, m, deterministic)
}
func (m *CreateOsConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOsConfigRequest.Merge(m, src)
}
func (m *CreateOsConfigRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOsConfigRequest.Size(m)
}
func (m *CreateOsConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOsConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOsConfigRequest proto.InternalMessageInfo

func (m *CreateOsConfigRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateOsConfigRequest) GetOsConfig() *OsConfig {
	if m != nil {
		return m.OsConfig
	}
	return nil
}

// A request message for retrieving a OsConfig.
type GetOsConfigRequest struct {
	// The resource name of the OsConfig.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOsConfigRequest) Reset()         { *m = GetOsConfigRequest{} }
func (m *GetOsConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetOsConfigRequest) ProtoMessage()    {}
func (*GetOsConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{12}
}
func (m *GetOsConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOsConfigRequest.Unmarshal(m, b)
}
func (m *GetOsConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOsConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetOsConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOsConfigRequest.Merge(m, src)
}
func (m *GetOsConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetOsConfigRequest.Size(m)
}
func (m *GetOsConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOsConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOsConfigRequest proto.InternalMessageInfo

func (m *GetOsConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// A request message for listing OsConfigs.
type ListOsConfigsRequest struct {
	// The resource name of the parent.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of OsConfigs to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A pagination token returned from a previous call to ListOsConfigs
	// that indicates where this listing should continue from.
	// This field is optional.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOsConfigsRequest) Reset()         { *m = ListOsConfigsRequest{} }
func (m *ListOsConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*ListOsConfigsRequest) ProtoMessage()    {}
func (*ListOsConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{13}
}
func (m *ListOsConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOsConfigsRequest.Unmarshal(m, b)
}
func (m *ListOsConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOsConfigsRequest.Marshal(b, m, deterministic)
}
func (m *ListOsConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOsConfigsRequest.Merge(m, src)
}
func (m *ListOsConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_ListOsConfigsRequest.Size(m)
}
func (m *ListOsConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOsConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOsConfigsRequest proto.InternalMessageInfo

func (m *ListOsConfigsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListOsConfigsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOsConfigsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// A response message for listing OsConfigs.
type ListOsConfigsResponse struct {
	// The list of OsConfigs.
	OsConfigs []*OsConfig `protobuf:"bytes,1,rep,name=os_configs,json=osConfigs,proto3" json:"os_configs,omitempty"`
	// A pagination token that can be used to get the next page
	// of OsConfigs.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOsConfigsResponse) Reset()         { *m = ListOsConfigsResponse{} }
func (m *ListOsConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*ListOsConfigsResponse) ProtoMessage()    {}
func (*ListOsConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{14}
}
func (m *ListOsConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOsConfigsResponse.Unmarshal(m, b)
}
func (m *ListOsConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOsConfigsResponse.Marshal(b, m, deterministic)
}
func (m *ListOsConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOsConfigsResponse.Merge(m, src)
}
func (m *ListOsConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_ListOsConfigsResponse.Size(m)
}
func (m *ListOsConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOsConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOsConfigsResponse proto.InternalMessageInfo

func (m *ListOsConfigsResponse) GetOsConfigs() []*OsConfig {
	if m != nil {
		return m.OsConfigs
	}
	return nil
}

func (m *ListOsConfigsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// A request message for updating a OsConfig.
type UpdateOsConfigRequest struct {
	// The resource name of the OsConfig.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The updated OsConfig.
	OsConfig *OsConfig `protobuf:"bytes,2,opt,name=os_config,json=osConfig,proto3" json:"os_config,omitempty"`
	// Field mask that controls which fields of the OsConfig should be updated.
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateOsConfigRequest) Reset()         { *m = UpdateOsConfigRequest{} }
func (m *UpdateOsConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOsConfigRequest) ProtoMessage()    {}
func (*UpdateOsConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{15}
}
func (m *UpdateOsConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOsConfigRequest.Unmarshal(m, b)
}
func (m *UpdateOsConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOsConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateOsConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOsConfigRequest.Merge(m, src)
}
func (m *UpdateOsConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOsConfigRequest.Size(m)
}
func (m *UpdateOsConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOsConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOsConfigRequest proto.InternalMessageInfo

func (m *UpdateOsConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateOsConfigRequest) GetOsConfig() *OsConfig {
	if m != nil {
		return m.OsConfig
	}
	return nil
}

func (m *UpdateOsConfigRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// A request message for deleting a OsConfig.
type DeleteOsConfigRequest struct {
	// The resource name of the OsConfig.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOsConfigRequest) Reset()         { *m = DeleteOsConfigRequest{} }
func (m *DeleteOsConfigRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOsConfigRequest) ProtoMessage()    {}
func (*DeleteOsConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_734d7e4527b6d512, []int{16}
}
func (m *DeleteOsConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOsConfigRequest.Unmarshal(m, b)
}
func (m *DeleteOsConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOsConfigRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOsConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOsConfigRequest.Merge(m, src)
}
func (m *DeleteOsConfigRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOsConfigRequest.Size(m)
}
func (m *DeleteOsConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOsConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOsConfigRequest proto.InternalMessageInfo

func (m *DeleteOsConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*OsConfig)(nil), "google.cloud.osconfig.v1alpha1.OsConfig")
	proto.RegisterMapType((map[string]string)(nil), "google.cloud.osconfig.v1alpha1.OsConfig.LabelsEntry")
	proto.RegisterType((*AptPackageConfig)(nil), "google.cloud.osconfig.v1alpha1.AptPackageConfig")
	proto.RegisterType((*YumPackageConfig)(nil), "google.cloud.osconfig.v1alpha1.YumPackageConfig")
	proto.RegisterType((*ZypperPackageConfig)(nil), "google.cloud.osconfig.v1alpha1.ZypperPackageConfig")
	proto.RegisterType((*GooPackageConfig)(nil), "google.cloud.osconfig.v1alpha1.GooPackageConfig")
	proto.RegisterType((*WindowsUpdateConfig)(nil), "google.cloud.osconfig.v1alpha1.WindowsUpdateConfig")
	proto.RegisterType((*Package)(nil), "google.cloud.osconfig.v1alpha1.Package")
	proto.RegisterType((*AptRepository)(nil), "google.cloud.osconfig.v1alpha1.AptRepository")
	proto.RegisterType((*YumRepository)(nil), "google.cloud.osconfig.v1alpha1.YumRepository")
	proto.RegisterType((*ZypperRepository)(nil), "google.cloud.osconfig.v1alpha1.ZypperRepository")
	proto.RegisterType((*GooRepository)(nil), "google.cloud.osconfig.v1alpha1.GooRepository")
	proto.RegisterType((*CreateOsConfigRequest)(nil), "google.cloud.osconfig.v1alpha1.CreateOsConfigRequest")
	proto.RegisterType((*GetOsConfigRequest)(nil), "google.cloud.osconfig.v1alpha1.GetOsConfigRequest")
	proto.RegisterType((*ListOsConfigsRequest)(nil), "google.cloud.osconfig.v1alpha1.ListOsConfigsRequest")
	proto.RegisterType((*ListOsConfigsResponse)(nil), "google.cloud.osconfig.v1alpha1.ListOsConfigsResponse")
	proto.RegisterType((*UpdateOsConfigRequest)(nil), "google.cloud.osconfig.v1alpha1.UpdateOsConfigRequest")
	proto.RegisterType((*DeleteOsConfigRequest)(nil), "google.cloud.osconfig.v1alpha1.DeleteOsConfigRequest")
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.AptRepository_ArchiveType", AptRepository_ArchiveType_name, AptRepository_ArchiveType_value)
}

func init() {
	proto.RegisterFile("google/cloud/osconfig/v1alpha1/os_configs.proto", fileDescriptor_734d7e4527b6d512)
}

var fileDescriptor_734d7e4527b6d512 = []byte{
	// 1017 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xc6, 0x76, 0xe3, 0x9f, 0xe3, 0x38, 0xb5, 0xa6, 0x4d, 0xd9, 0x06, 0x5a, 0xcc, 0x5e, 0x80,
	0x25, 0xc4, 0xba, 0x4d, 0x41, 0x22, 0xf4, 0x2a, 0x76, 0x9c, 0x10, 0x35, 0x14, 0xb3, 0x71, 0x40,
	0x89, 0x90, 0x56, 0x63, 0x7b, 0xb2, 0x1d, 0xbc, 0xbb, 0x33, 0xec, 0xec, 0x3a, 0xdd, 0xf0, 0x02,
	0xdc, 0x70, 0xc5, 0x03, 0xf0, 0x08, 0xdc, 0xf2, 0x78, 0x68, 0x66, 0x67, 0x1d, 0xdb, 0x72, 0x6a,
	0x83, 0x10, 0x12, 0xbd, 0x9b, 0x3d, 0x73, 0xbe, 0x6f, 0xce, 0xdf, 0x9c, 0x3d, 0x03, 0x2d, 0x97,
	0x31, 0xd7, 0x23, 0xad, 0xa1, 0xc7, 0xe2, 0x51, 0x8b, 0x89, 0x21, 0x0b, 0x2e, 0xa9, 0xdb, 0x9a,
	0x3c, 0xc5, 0x1e, 0x7f, 0x85, 0x9f, 0xb6, 0x98, 0x70, 0x52, 0x91, 0xb0, 0x78, 0xc8, 0x22, 0x86,
	0x1e, 0xa7, 0x00, 0x4b, 0x01, 0xac, 0x0c, 0x60, 0x65, 0x80, 0x9d, 0x86, 0x26, 0x54, 0xda, 0x83,
	0xf8, 0xb2, 0x75, 0x49, 0x89, 0x37, 0x72, 0x7c, 0x2c, 0xc6, 0x29, 0xc3, 0xce, 0x07, 0x8b, 0x1a,
	0x11, 0xf5, 0x89, 0x88, 0xb0, 0xcf, 0x53, 0x05, 0xf3, 0xcf, 0x0d, 0x28, 0x7f, 0x23, 0x3a, 0x8a,
	0x18, 0x21, 0xb8, 0x13, 0x60, 0x9f, 0x18, 0xb9, 0x46, 0xae, 0x59, 0xb1, 0xd5, 0x1a, 0x35, 0xa0,
	0x3a, 0x22, 0x62, 0x18, 0x52, 0x1e, 0x51, 0x16, 0x18, 0x79, 0xb5, 0x35, 0x2b, 0x42, 0xcf, 0xa1,
	0x3a, 0x0c, 0x09, 0x8e, 0x88, 0x23, 0xc9, 0x8d, 0x42, 0x23, 0xd7, 0xac, 0xee, 0xee, 0x58, 0xda,
	0xf6, 0xec, 0x64, 0xab, 0x9f, 0x9d, 0x6c, 0x43, 0xaa, 0x2e, 0x05, 0x12, 0x1c, 0xf3, 0xd1, 0x14,
	0x7c, 0x67, 0x35, 0x38, 0x55, 0x57, 0xe0, 0x13, 0x28, 0x7a, 0x78, 0x40, 0x3c, 0x61, 0x6c, 0x34,
	0x0a, 0xcd, 0xea, 0xee, 0x67, 0xd6, 0x9b, 0x03, 0x66, 0x65, 0x9e, 0x5a, 0x27, 0x0a, 0xd6, 0x0d,
	0xa2, 0x30, 0xb1, 0x35, 0x07, 0x6a, 0x43, 0x01, 0xf3, 0xc8, 0x28, 0x2a, 0x13, 0x9e, 0xac, 0xa2,
	0xda, 0xe7, 0x51, 0x0f, 0x0f, 0xc7, 0xd8, 0x25, 0x29, 0xa5, 0x2d, 0xc1, 0x92, 0x23, 0x89, 0x7d,
	0xa3, 0xb4, 0x1e, 0xc7, 0x79, 0xec, 0x2f, 0x70, 0x24, 0xb1, 0x2f, 0x39, 0x5c, 0xc6, 0x8c, 0xf2,
	0x7a, 0x1c, 0x47, 0x8c, 0x2d, 0x70, 0xb8, 0x8c, 0xa1, 0x0b, 0xd8, 0xba, 0xa2, 0xc1, 0x88, 0x5d,
	0x09, 0x27, 0x8d, 0x97, 0x51, 0x51, 0x74, 0xcf, 0x56, 0xd1, 0x7d, 0x9f, 0xa2, 0xce, 0x14, 0x48,
	0x33, 0xd6, 0xae, 0x66, 0x85, 0xe8, 0x05, 0x14, 0xaf, 0x13, 0xce, 0x49, 0x68, 0xc0, 0x7a, 0x9c,
	0x17, 0x4a, 0x7b, 0xde, 0x4a, 0x4d, 0xb1, 0xb3, 0x07, 0xd5, 0x99, 0x5c, 0xa0, 0x3a, 0x14, 0xc6,
	0x24, 0xd1, 0x05, 0x28, 0x97, 0xe8, 0x3e, 0x6c, 0x4c, 0xb0, 0x17, 0x13, 0x5d, 0x79, 0xe9, 0xc7,
	0x97, 0xf9, 0x2f, 0x72, 0xe6, 0xaf, 0x79, 0xa8, 0x2f, 0x66, 0x01, 0xd9, 0x50, 0xe7, 0xa9, 0xc0,
	0xa1, 0x81, 0x88, 0xb0, 0xe7, 0x09, 0x23, 0xa7, 0x8a, 0xe3, 0xe3, 0x55, 0x66, 0x6a, 0x22, 0xfb,
	0xae, 0x26, 0x38, 0xd6, 0xf8, 0x59, 0xce, 0x90, 0xf8, 0x6c, 0x82, 0x3d, 0x61, 0xe4, 0xff, 0x19,
	0xa7, 0xad, 0xf1, 0xe8, 0x5b, 0xd8, 0x0c, 0x09, 0x67, 0x82, 0x46, 0x2c, 0xa4, 0x44, 0x18, 0x05,
	0xc5, 0xf7, 0xe9, 0x1a, 0x55, 0x67, 0x67, 0xb0, 0xc4, 0x9e, 0xa3, 0x50, 0xf1, 0x58, 0xac, 0xa8,
	0xb7, 0x3d, 0x1e, 0xe7, 0xb1, 0x7f, 0x6b, 0x3c, 0x7e, 0xcb, 0xc3, 0xbd, 0x25, 0xa5, 0xf7, 0xbf,
	0x09, 0x49, 0x7f, 0x69, 0x48, 0x9e, 0xac, 0x77, 0xdb, 0xde, 0x58, 0x25, 0x8b, 0x3d, 0xe3, 0x6d,
	0xaf, 0x92, 0x23, 0xc6, 0x6e, 0x8d, 0x47, 0x0f, 0xee, 0x2d, 0xe9, 0x79, 0x68, 0x0f, 0x1e, 0xce,
	0x37, 0x50, 0x47, 0x90, 0x70, 0x42, 0x42, 0x27, 0x0e, 0xa9, 0xea, 0xa5, 0x15, 0xfb, 0xc1, 0x5c,
	0x5b, 0x3c, 0x55, 0xdb, 0x67, 0x21, 0x35, 0x1f, 0x41, 0x49, 0x3b, 0xb0, 0xec, 0x87, 0x6a, 0xfe,
	0x9e, 0x87, 0xda, 0xdc, 0x35, 0x46, 0x3f, 0xc0, 0x26, 0x0e, 0x87, 0xaf, 0xe8, 0x84, 0x38, 0x51,
	0xc2, 0x53, 0xed, 0xad, 0xdd, 0xbd, 0xbf, 0xd5, 0x0b, 0xac, 0xfd, 0x94, 0xa1, 0x9f, 0x70, 0x62,
	0x57, 0xf1, 0xcd, 0x87, 0x6c, 0xa9, 0xd2, 0xe6, 0xb4, 0x7d, 0xca, 0x25, 0x32, 0x61, 0x73, 0x44,
	0x45, 0x14, 0xd2, 0x41, 0xac, 0xfe, 0xe9, 0x05, 0xb5, 0x35, 0x27, 0x43, 0x8f, 0x01, 0x86, 0xcc,
	0xe7, 0x2c, 0x20, 0x41, 0x24, 0x8c, 0x3b, 0x8d, 0x42, 0xb3, 0x62, 0xcf, 0x48, 0xd0, 0xbb, 0x50,
	0x1a, 0x93, 0x44, 0x45, 0x63, 0x43, 0xc1, 0x8b, 0x63, 0x92, 0x48, 0xef, 0xf7, 0xa1, 0x3a, 0x63,
	0x0a, 0x7a, 0x1f, 0x8c, 0x7d, 0xbb, 0xf3, 0xd5, 0xf1, 0x77, 0x5d, 0xa7, 0x7f, 0xde, 0xeb, 0x3a,
	0x67, 0x2f, 0x4f, 0x7b, 0xdd, 0xce, 0xf1, 0xe1, 0x71, 0xf7, 0xa0, 0xfe, 0x0e, 0x2a, 0x41, 0xe1,
	0xa0, 0xdb, 0xae, 0xe7, 0x50, 0x15, 0x4a, 0x07, 0xdd, 0xb6, 0x73, 0x6a, 0x77, 0xea, 0x79, 0xf3,
	0x35, 0xd4, 0xe6, 0xee, 0x35, 0xda, 0x82, 0x3c, 0x1d, 0xe9, 0x20, 0xe6, 0xe9, 0x08, 0x7d, 0xa8,
	0x1c, 0xe0, 0x1e, 0x4e, 0x1c, 0x15, 0xde, 0x6c, 0x28, 0x49, 0x65, 0x2f, 0xe5, 0xd8, 0xf2, 0x10,
	0xca, 0x03, 0x2c, 0x88, 0x13, 0x87, 0x9e, 0xf6, 0xaf, 0x24, 0xbf, 0xcf, 0x42, 0x4f, 0x6e, 0xb9,
	0xdc, 0x75, 0xc6, 0x24, 0xc9, 0x1c, 0x2b, 0xb9, 0xdc, 0x7d, 0x41, 0x12, 0x61, 0xfe, 0x0c, 0xf5,
	0xc5, 0xeb, 0xf3, 0xdf, 0x1d, 0xfe, 0x39, 0xd4, 0xe6, 0x0a, 0x75, 0xe9, 0x38, 0xa6, 0xb2, 0xe9,
	0xdd, 0x64, 0xd3, 0x33, 0x27, 0xb0, 0xdd, 0x51, 0xf3, 0x54, 0x36, 0xdc, 0xd8, 0xe4, 0xa7, 0x98,
	0x88, 0x08, 0x3d, 0x80, 0x22, 0xc7, 0x21, 0x09, 0x22, 0x4d, 0xa0, 0xbf, 0x50, 0x17, 0x2a, 0xd3,
	0x49, 0x53, 0x11, 0x55, 0x77, 0x9b, 0xeb, 0x0e, 0x4e, 0x76, 0x99, 0xe9, 0x95, 0xd9, 0x04, 0x74,
	0x44, 0xa2, 0xc5, 0x43, 0x97, 0x55, 0xfc, 0x8f, 0x70, 0xff, 0x84, 0x8a, 0xa9, 0xaa, 0x58, 0x65,
	0xe0, 0x7b, 0x50, 0xe1, 0xb2, 0x6d, 0x08, 0x7a, 0x9d, 0x86, 0x77, 0xc3, 0x2e, 0x4b, 0xc1, 0x29,
	0xbd, 0x26, 0xe8, 0x11, 0x80, 0xda, 0x8c, 0xd8, 0x98, 0x64, 0xa5, 0xab, 0xd4, 0xfb, 0x52, 0x60,
	0xfe, 0x92, 0x83, 0xed, 0x85, 0xc3, 0x04, 0x67, 0x81, 0x20, 0xe8, 0x08, 0xe0, 0x66, 0xc0, 0xd6,
	0xdd, 0x6d, 0x7d, 0xbf, 0x2b, 0x99, 0xdf, 0x02, 0x7d, 0x04, 0x77, 0x03, 0xf2, 0x3a, 0x72, 0x66,
	0xcc, 0x48, 0xd3, 0x51, 0x93, 0xe2, 0xde, 0xd4, 0x94, 0x3f, 0x72, 0xb0, 0x9d, 0xf6, 0x86, 0x35,
	0x82, 0xf4, 0x2f, 0x65, 0x65, 0x66, 0x9e, 0x96, 0xaf, 0x80, 0x5b, 0x87, 0xf1, 0x43, 0xf9, 0x50,
	0xf8, 0x1a, 0x8b, 0x71, 0x36, 0x4f, 0xcb, 0xb5, 0xf9, 0x09, 0x6c, 0x1f, 0x10, 0x8f, 0xac, 0x65,
	0x70, 0xfb, 0x0a, 0xcc, 0x21, 0xf3, 0x57, 0x98, 0xd8, 0xae, 0x4c, 0x13, 0x71, 0x71, 0xa8, 0x55,
	0x5d, 0xe6, 0xe1, 0xc0, 0xb5, 0x58, 0xe8, 0xb6, 0x5c, 0x12, 0x28, 0x93, 0xf4, 0xcb, 0x08, 0x73,
	0x2a, 0x6e, 0x7b, 0x1d, 0x3d, 0xcf, 0x24, 0x83, 0xa2, 0x82, 0x3c, 0xfb, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0xb4, 0x93, 0x66, 0x8a, 0x4f, 0x0d, 0x00, 0x00,
}
