// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/osconfig/v1alpha1/osconfig_service.proto

package osconfig

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	v1 "google.golang.org/genproto/googleapis/iam/v1"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Type of configuration system(s) the instance is using.
type LookupConfigsRequest_ConfigType int32

const (
	// Invalid. Config type must be specified.
	LookupConfigsRequest_CONFIG_TYPE_UNSPECIFIED LookupConfigsRequest_ConfigType = 0
	// This instance runs apt.
	LookupConfigsRequest_APT LookupConfigsRequest_ConfigType = 1
	// This instance runs yum.
	LookupConfigsRequest_YUM LookupConfigsRequest_ConfigType = 2
	// This instance runs googet.
	LookupConfigsRequest_GOO LookupConfigsRequest_ConfigType = 3
	// This instance runs Windows Update.
	LookupConfigsRequest_WINDOWS_UPDATE LookupConfigsRequest_ConfigType = 4
	// This instance runs zypper.
	LookupConfigsRequest_ZYPPER LookupConfigsRequest_ConfigType = 5
)

var LookupConfigsRequest_ConfigType_name = map[int32]string{
	0: "CONFIG_TYPE_UNSPECIFIED",
	1: "APT",
	2: "YUM",
	3: "GOO",
	4: "WINDOWS_UPDATE",
	5: "ZYPPER",
}

var LookupConfigsRequest_ConfigType_value = map[string]int32{
	"CONFIG_TYPE_UNSPECIFIED": 0,
	"APT":                     1,
	"YUM":                     2,
	"GOO":                     3,
	"WINDOWS_UPDATE":          4,
	"ZYPPER":                  5,
}

func (x LookupConfigsRequest_ConfigType) String() string {
	return proto.EnumName(LookupConfigsRequest_ConfigType_name, int32(x))
}

func (LookupConfigsRequest_ConfigType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f9b585862e928ce, []int{0, 0}
}

// A request message for getting the configs assigned to the instance.
type LookupConfigsRequest struct {
	// The resource name for the instance.
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Optional. OS info about the instance that can be used to filter its
	// configs. If none is provided, the API will return the configs for this
	// instance regardless of its OS.
	OsInfo *LookupConfigsRequest_OsInfo `protobuf:"bytes,2,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	// Types of configuration system the instance is using. Only configs relevant
	// to these configuration types will be returned.
	ConfigTypes          []LookupConfigsRequest_ConfigType `protobuf:"varint,5,rep,packed,name=config_types,json=configTypes,proto3,enum=google.cloud.osconfig.v1alpha1.LookupConfigsRequest_ConfigType" json:"config_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *LookupConfigsRequest) Reset()         { *m = LookupConfigsRequest{} }
func (m *LookupConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*LookupConfigsRequest) ProtoMessage()    {}
func (*LookupConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f9b585862e928ce, []int{0}
}

func (m *LookupConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupConfigsRequest.Unmarshal(m, b)
}
func (m *LookupConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupConfigsRequest.Marshal(b, m, deterministic)
}
func (m *LookupConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupConfigsRequest.Merge(m, src)
}
func (m *LookupConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_LookupConfigsRequest.Size(m)
}
func (m *LookupConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupConfigsRequest proto.InternalMessageInfo

func (m *LookupConfigsRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *LookupConfigsRequest) GetOsInfo() *LookupConfigsRequest_OsInfo {
	if m != nil {
		return m.OsInfo
	}
	return nil
}

func (m *LookupConfigsRequest) GetConfigTypes() []LookupConfigsRequest_ConfigType {
	if m != nil {
		return m.ConfigTypes
	}
	return nil
}

// Guest information provided to service by agent when requesting
// configurations.
type LookupConfigsRequest_OsInfo struct {
	// OS long name. Optional.
	OsLongName string `protobuf:"bytes,1,opt,name=os_long_name,json=osLongName,proto3" json:"os_long_name,omitempty"`
	// OS short name. Optional.
	OsShortName string `protobuf:"bytes,2,opt,name=os_short_name,json=osShortName,proto3" json:"os_short_name,omitempty"`
	// OS version. Optional.
	OsVersion string `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	// OS kernel name. Optional.
	OsKernel string `protobuf:"bytes,4,opt,name=os_kernel,json=osKernel,proto3" json:"os_kernel,omitempty"`
	// Architecture of the OS. Optional.
	OsArchitecture       string   `protobuf:"bytes,5,opt,name=os_architecture,json=osArchitecture,proto3" json:"os_architecture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupConfigsRequest_OsInfo) Reset()         { *m = LookupConfigsRequest_OsInfo{} }
func (m *LookupConfigsRequest_OsInfo) String() string { return proto.CompactTextString(m) }
func (*LookupConfigsRequest_OsInfo) ProtoMessage()    {}
func (*LookupConfigsRequest_OsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f9b585862e928ce, []int{0, 0}
}

func (m *LookupConfigsRequest_OsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupConfigsRequest_OsInfo.Unmarshal(m, b)
}
func (m *LookupConfigsRequest_OsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupConfigsRequest_OsInfo.Marshal(b, m, deterministic)
}
func (m *LookupConfigsRequest_OsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupConfigsRequest_OsInfo.Merge(m, src)
}
func (m *LookupConfigsRequest_OsInfo) XXX_Size() int {
	return xxx_messageInfo_LookupConfigsRequest_OsInfo.Size(m)
}
func (m *LookupConfigsRequest_OsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupConfigsRequest_OsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LookupConfigsRequest_OsInfo proto.InternalMessageInfo

func (m *LookupConfigsRequest_OsInfo) GetOsLongName() string {
	if m != nil {
		return m.OsLongName
	}
	return ""
}

func (m *LookupConfigsRequest_OsInfo) GetOsShortName() string {
	if m != nil {
		return m.OsShortName
	}
	return ""
}

func (m *LookupConfigsRequest_OsInfo) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *LookupConfigsRequest_OsInfo) GetOsKernel() string {
	if m != nil {
		return m.OsKernel
	}
	return ""
}

func (m *LookupConfigsRequest_OsInfo) GetOsArchitecture() string {
	if m != nil {
		return m.OsArchitecture
	}
	return ""
}

// Response with assigned configs for the instance.
type LookupConfigsResponse struct {
	// Configs for apt.
	Apt *AptPackageConfig `protobuf:"bytes,1,opt,name=apt,proto3" json:"apt,omitempty"`
	// Configs for yum.
	Yum *YumPackageConfig `protobuf:"bytes,2,opt,name=yum,proto3" json:"yum,omitempty"`
	// Configs for windows.
	Goo *GooPackageConfig `protobuf:"bytes,3,opt,name=goo,proto3" json:"goo,omitempty"`
	// Configs for Windows Update.
	WindowsUpdate *WindowsUpdateConfig `protobuf:"bytes,4,opt,name=windows_update,json=windowsUpdate,proto3" json:"windows_update,omitempty"`
	// Configs for Zypper.
	Zypper               *ZypperPackageConfig `protobuf:"bytes,5,opt,name=zypper,proto3" json:"zypper,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LookupConfigsResponse) Reset()         { *m = LookupConfigsResponse{} }
func (m *LookupConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*LookupConfigsResponse) ProtoMessage()    {}
func (*LookupConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f9b585862e928ce, []int{1}
}

func (m *LookupConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupConfigsResponse.Unmarshal(m, b)
}
func (m *LookupConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupConfigsResponse.Marshal(b, m, deterministic)
}
func (m *LookupConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupConfigsResponse.Merge(m, src)
}
func (m *LookupConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_LookupConfigsResponse.Size(m)
}
func (m *LookupConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupConfigsResponse proto.InternalMessageInfo

func (m *LookupConfigsResponse) GetApt() *AptPackageConfig {
	if m != nil {
		return m.Apt
	}
	return nil
}

func (m *LookupConfigsResponse) GetYum() *YumPackageConfig {
	if m != nil {
		return m.Yum
	}
	return nil
}

func (m *LookupConfigsResponse) GetGoo() *GooPackageConfig {
	if m != nil {
		return m.Goo
	}
	return nil
}

func (m *LookupConfigsResponse) GetWindowsUpdate() *WindowsUpdateConfig {
	if m != nil {
		return m.WindowsUpdate
	}
	return nil
}

func (m *LookupConfigsResponse) GetZypper() *ZypperPackageConfig {
	if m != nil {
		return m.Zypper
	}
	return nil
}

func init() {
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.LookupConfigsRequest_ConfigType", LookupConfigsRequest_ConfigType_name, LookupConfigsRequest_ConfigType_value)
	proto.RegisterType((*LookupConfigsRequest)(nil), "google.cloud.osconfig.v1alpha1.LookupConfigsRequest")
	proto.RegisterType((*LookupConfigsRequest_OsInfo)(nil), "google.cloud.osconfig.v1alpha1.LookupConfigsRequest.OsInfo")
	proto.RegisterType((*LookupConfigsResponse)(nil), "google.cloud.osconfig.v1alpha1.LookupConfigsResponse")
}

func init() {
	proto.RegisterFile("google/cloud/osconfig/v1alpha1/osconfig_service.proto", fileDescriptor_3f9b585862e928ce)
}

var fileDescriptor_3f9b585862e928ce = []byte{
	// 1535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcf, 0x6f, 0xdc, 0xc4,
	0x17, 0xff, 0x7a, 0xd3, 0xa6, 0xdf, 0x4c, 0x9a, 0xcd, 0x6a, 0x44, 0x21, 0x4a, 0x28, 0x8a, 0x7c,
	0x68, 0x37, 0x0b, 0xac, 0x1b, 0x27, 0x6d, 0xda, 0xad, 0x10, 0xda, 0x24, 0x9b, 0x68, 0x69, 0x48,
	0x96, 0x4d, 0xd2, 0x2a, 0x2b, 0x24, 0xcb, 0x71, 0x26, 0x8e, 0xdb, 0x5d, 0x8f, 0xf1, 0xcc, 0xa6,
	0xa4, 0x55, 0x2e, 0xc0, 0x81, 0x56, 0x1c, 0x90, 0x10, 0x37, 0x04, 0x07, 0xe0, 0x04, 0x05, 0x24,
	0x90, 0xf8, 0x1b, 0xe0, 0xca, 0xbf, 0xc0, 0x05, 0x89, 0x0b, 0x17, 0xc4, 0x11, 0x79, 0xc6, 0xf6,
	0xda, 0xce, 0xae, 0x7f, 0x24, 0xe2, 0xb4, 0xeb, 0x99, 0xf7, 0x79, 0xf3, 0x3e, 0x9f, 0x79, 0xef,
	0x79, 0xc6, 0xe0, 0xba, 0x8e, 0xb1, 0xde, 0x46, 0x92, 0xd6, 0xc6, 0xdd, 0x3d, 0x09, 0x13, 0x0d,
	0x9b, 0xfb, 0x86, 0x2e, 0x1d, 0xce, 0xaa, 0x6d, 0xeb, 0x40, 0x9d, 0xf5, 0x47, 0x14, 0x82, 0xec,
	0x43, 0x43, 0x43, 0x65, 0xcb, 0xc6, 0x14, 0xc3, 0x97, 0x38, 0xac, 0xcc, 0x60, 0x65, 0xcf, 0xa8,
	0xec, 0xc1, 0x26, 0x5f, 0x74, 0xdd, 0xaa, 0x96, 0x21, 0xa9, 0xa6, 0x89, 0xa9, 0x4a, 0x0d, 0x6c,
	0x12, 0x8e, 0x9e, 0xbc, 0x96, 0xb0, 0xa8, 0x4a, 0x88, 0xa1, 0x9b, 0x1d, 0x64, 0x52, 0x0f, 0x21,
	0x25, 0x86, 0xa9, 0xf0, 0xa1, 0xb4, 0x00, 0x4b, 0xa5, 0xda, 0x81, 0x72, 0x1f, 0xef, 0x7a, 0x00,
	0x97, 0x91, 0x64, 0xa8, 0x1d, 0xe9, 0x70, 0xd6, 0xf9, 0x51, 0x2c, 0xdc, 0x36, 0xb4, 0x23, 0x77,
	0x7e, 0x32, 0x3c, 0x1f, 0x9a, 0x9b, 0x72, 0xe7, 0xd8, 0xd3, 0x6e, 0x77, 0x5f, 0x42, 0x1d, 0x8b,
	0xba, 0x93, 0xe2, 0x87, 0xe7, 0xc0, 0x73, 0x6b, 0x18, 0x3f, 0xe8, 0x5a, 0x4b, 0x3c, 0xc2, 0x26,
	0x7a, 0xa7, 0x8b, 0x08, 0x85, 0x93, 0xe0, 0xff, 0x36, 0x22, 0xb8, 0x6b, 0x6b, 0x68, 0x42, 0x98,
	0x16, 0x8a, 0x23, 0x4d, 0xff, 0x19, 0x6e, 0x81, 0x0b, 0x98, 0x28, 0x86, 0xb9, 0x8f, 0x27, 0x72,
	0xd3, 0x42, 0x71, 0x54, 0xbe, 0x5d, 0x8e, 0x57, 0xbc, 0xdc, 0x6f, 0x89, 0xf2, 0x06, 0xa9, 0x9b,
	0xfb, 0xb8, 0x39, 0x8c, 0xd9, 0x2f, 0xdc, 0x05, 0x17, 0xdd, 0xdd, 0xa4, 0x47, 0x16, 0x22, 0x13,
	0xe7, 0xa7, 0x87, 0x8a, 0x79, 0xf9, 0xf5, 0x53, 0xb9, 0xe6, 0x8f, 0x5b, 0x47, 0x16, 0x6a, 0x8e,
	0x6a, 0xfe, 0x7f, 0x32, 0xf9, 0xa3, 0x00, 0x86, 0xf9, 0xb2, 0x70, 0x1a, 0x5c, 0xc4, 0x44, 0x69,
	0x63, 0x53, 0x57, 0x4c, 0xb5, 0xe3, 0x91, 0x04, 0x98, 0xac, 0x61, 0x53, 0x5f, 0x57, 0x3b, 0x08,
	0x8a, 0x60, 0x0c, 0x13, 0x85, 0x1c, 0x60, 0x9b, 0x72, 0x93, 0x1c, 0x33, 0x19, 0xc5, 0x64, 0xd3,
	0x19, 0x63, 0x36, 0x97, 0x01, 0xc0, 0x44, 0x39, 0x44, 0x36, 0x31, 0xb0, 0x39, 0x31, 0xc4, 0x0c,
	0x46, 0x30, 0xb9, 0xcb, 0x07, 0xe0, 0x14, 0x18, 0xc1, 0x44, 0x79, 0x80, 0x6c, 0x13, 0xb5, 0x27,
	0xce, 0x71, 0x19, 0x31, 0xb9, 0xc3, 0x9e, 0xe1, 0x55, 0x30, 0x8e, 0x89, 0xa2, 0xda, 0xda, 0x81,
	0x41, 0x91, 0x46, 0xbb, 0x36, 0x9a, 0x38, 0xcf, 0x4c, 0xf2, 0x98, 0x54, 0x03, 0xa3, 0xe2, 0x1e,
	0x00, 0x3d, 0x42, 0x70, 0x0a, 0xbc, 0xb0, 0xb4, 0xb1, 0xbe, 0x52, 0x5f, 0x55, 0xb6, 0x76, 0x1a,
	0x35, 0x65, 0x7b, 0x7d, 0xb3, 0x51, 0x5b, 0xaa, 0xaf, 0xd4, 0x6b, 0xcb, 0x85, 0xff, 0xc1, 0x0b,
	0x60, 0xa8, 0xda, 0xd8, 0x2a, 0x08, 0xce, 0x9f, 0x9d, 0xed, 0x37, 0x0b, 0x39, 0xe7, 0xcf, 0xea,
	0xc6, 0x46, 0x61, 0x08, 0x42, 0x90, 0xbf, 0x57, 0x5f, 0x5f, 0xde, 0xb8, 0xb7, 0xa9, 0x6c, 0x37,
	0x96, 0xab, 0x5b, 0xb5, 0xc2, 0x39, 0x08, 0xc0, 0x70, 0x6b, 0xa7, 0xd1, 0xa8, 0x35, 0x0b, 0xe7,
	0xc5, 0x8f, 0x86, 0xc0, 0xa5, 0x88, 0x98, 0xc4, 0xc2, 0x26, 0x41, 0x70, 0x11, 0x0c, 0xa9, 0x16,
	0x65, 0x0a, 0x8d, 0xca, 0xd7, 0x92, 0x36, 0xa4, 0x6a, 0xd1, 0x86, 0xaa, 0x3d, 0x50, 0x75, 0xc4,
	0xfd, 0x34, 0x1d, 0xb0, 0xe3, 0xe3, 0xa8, 0xdb, 0x71, 0xf3, 0x25, 0xd1, 0xc7, 0x4e, 0xb7, 0x13,
	0xf1, 0x71, 0xd4, 0xed, 0x38, 0x3e, 0x74, 0x8c, 0x99, 0xca, 0x29, 0x7c, 0xac, 0x62, 0x1c, 0xf1,
	0xa1, 0x63, 0x0c, 0x5b, 0x20, 0xff, 0xd0, 0x30, 0xf7, 0xf0, 0x43, 0xa2, 0x74, 0xad, 0x3d, 0x95,
	0x22, 0xb6, 0x2d, 0xa3, 0xf2, 0x5c, 0x92, 0xbb, 0x7b, 0x1c, 0xb5, 0xcd, 0x40, 0xae, 0xc7, 0xb1,
	0x87, 0xc1, 0x41, 0x78, 0x07, 0x0c, 0x3f, 0x3a, 0xb2, 0x2c, 0x64, 0xb3, 0x7d, 0x4c, 0xe1, 0xb3,
	0xc5, 0xac, 0xc3, 0x51, 0xba, 0x2e, 0xe4, 0x5f, 0xae, 0x80, 0xf1, 0x0d, 0xc2, 0x07, 0x37, 0x79,
	0x7b, 0x83, 0x5f, 0xe4, 0x40, 0x7e, 0xc9, 0x46, 0x2a, 0x45, 0xde, 0x0c, 0xbc, 0x9e, 0xb4, 0x46,
	0xd8, 0xde, 0x2d, 0x90, 0xc9, 0x62, 0x12, 0xcc, 0x03, 0x88, 0xdf, 0x08, 0xef, 0xfd, 0xf6, 0xfb,
	0x27, 0xb9, 0xaf, 0x04, 0xf1, 0x95, 0x5e, 0x83, 0x7a, 0x6c, 0xa9, 0x36, 0x32, 0xe9, 0x6b, 0xd8,
	0xd6, 0x55, 0xd3, 0x78, 0xc4, 0xfb, 0xa7, 0x54, 0x3a, 0x96, 0xb0, 0x0b, 0x23, 0x95, 0x11, 0xbf,
	0xeb, 0xb5, 0xe6, 0xc5, 0xab, 0x27, 0xa1, 0x96, 0x8d, 0xef, 0x23, 0x8d, 0x0e, 0x46, 0xcd, 0x89,
	0x57, 0x4e, 0xa2, 0xf6, 0x71, 0x7b, 0x0f, 0xd9, 0x03, 0x41, 0xf0, 0x1f, 0x01, 0x8c, 0xae, 0x22,
	0xea, 0xcb, 0x23, 0x27, 0x66, 0x49, 0xcf, 0x38, 0xbb, 0x36, 0x4f, 0xb9, 0x36, 0xef, 0x0b, 0x30,
	0xa8, 0x8d, 0xd3, 0x2b, 0xa2, 0xca, 0xf4, 0xa2, 0x95, 0x4a, 0xc7, 0xad, 0x19, 0x78, 0x35, 0x6a,
	0xdf, 0x93, 0x23, 0x6c, 0x5a, 0x84, 0x57, 0xa2, 0xa6, 0xbe, 0x06, 0x21, 0x4b, 0xf8, 0x24, 0x07,
	0xc6, 0xd6, 0x0c, 0xe2, 0xd3, 0x21, 0x70, 0x3e, 0xb1, 0x77, 0x06, 0xcd, 0x3d, 0xfa, 0xd7, 0x33,
	0xa2, 0x78, 0x93, 0x18, 0xa0, 0x45, 0x62, 0x9e, 0x44, 0xb4, 0x88, 0x4b, 0x8e, 0x88, 0x16, 0x31,
	0x19, 0xc1, 0x0a, 0x85, 0x17, 0x65, 0xfa, 0x42, 0x09, 0xdb, 0x9f, 0xa1, 0x50, 0xe4, 0x4c, 0xc9,
	0x10, 0x2a, 0x14, 0x39, 0x6d, 0x5e, 0x84, 0x0a, 0x45, 0x4e, 0x99, 0x22, 0xc1, 0x42, 0xf9, 0x53,
	0x00, 0xf9, 0x65, 0xd4, 0x46, 0x59, 0x14, 0x0a, 0xdb, 0x7b, 0x0a, 0x3d, 0xef, 0xc1, 0xbc, 0x03,
	0x46, 0xb9, 0xe6, 0x1c, 0x30, 0x7a, 0x09, 0x51, 0xca, 0x58, 0x1c, 0xa5, 0xf4, 0xc5, 0x51, 0x4a,
	0x5b, 0x1c, 0xdf, 0xe5, 0x40, 0x81, 0x77, 0xc2, 0xaa, 0x7f, 0x7c, 0x83, 0x0b, 0xe9, 0x7a, 0x67,
	0x0f, 0xe1, 0x51, 0x2e, 0x25, 0xbe, 0x03, 0x7d, 0x88, 0xf8, 0x13, 0x97, 0xe1, 0x99, 0x20, 0x96,
	0x53, 0xd4, 0x45, 0xe0, 0x70, 0x59, 0x01, 0xbd, 0x87, 0xd6, 0x82, 0x38, 0x13, 0x5f, 0x25, 0x83,
	0x80, 0x37, 0xc4, 0x62, 0x6c, 0xcd, 0x0c, 0xc0, 0xc1, 0x0f, 0x72, 0x60, 0x6c, 0x15, 0xd1, 0x80,
	0x5a, 0xf3, 0x29, 0x5a, 0xe9, 0xd9, 0xa4, 0xfa, 0x98, 0x4b, 0xf5, 0x44, 0x80, 0xe5, 0xa4, 0x8c,
	0x09, 0x84, 0xed, 0x24, 0xc2, 0xcb, 0x70, 0x26, 0x26, 0x67, 0x22, 0xc6, 0x25, 0x58, 0x1c, 0x9c,
	0x35, 0x61, 0x5b, 0xf8, 0x69, 0x0e, 0x8c, 0x3b, 0xfd, 0xae, 0x17, 0x25, 0x81, 0x37, 0xd2, 0x34,
	0xc8, 0x00, 0xc0, 0x93, 0x62, 0x21, 0x33, 0xce, 0x6d, 0xad, 0xfd, 0x75, 0x49, 0x91, 0x42, 0x11,
	0x5d, 0xe2, 0xd3, 0x26, 0xa2, 0x4b, 0x6c, 0xaa, 0xb0, 0x7a, 0xe2, 0x0d, 0x33, 0x4b, 0x3d, 0x45,
	0x11, 0x67, 0xaa, 0x27, 0x39, 0x63, 0x92, 0x84, 0xeb, 0x49, 0x4e, 0x9f, 0x30, 0xe1, 0x7a, 0x92,
	0x53, 0x27, 0x4f, 0xa8, 0x9e, 0xfe, 0x16, 0x40, 0x81, 0xf7, 0xcf, 0x2c, 0x82, 0x45, 0x11, 0x49,
	0x3d, 0xd7, 0xcf, 0x94, 0x52, 0xe6, 0x0a, 0x2a, 0x65, 0xa9, 0xa0, 0x52, 0xfa, 0x0a, 0xfa, 0x4b,
	0x00, 0x17, 0x57, 0x11, 0xad, 0xab, 0x9d, 0x06, 0xbb, 0x95, 0x42, 0xd1, 0x8b, 0xdd, 0x50, 0x3b,
	0xe5, 0x43, 0xd6, 0x36, 0xfc, 0x49, 0x8f, 0xdf, 0xa5, 0x88, 0x0d, 0x9f, 0x15, 0xbf, 0xe6, 0xf4,
	0x3e, 0x17, 0x44, 0x39, 0xb0, 0xbe, 0x77, 0x2f, 0x8d, 0x52, 0x2c, 0x1d, 0x57, 0xf4, 0x80, 0xef,
	0x8a, 0x50, 0x6a, 0xc9, 0xe2, 0xab, 0xfd, 0x80, 0x3d, 0xa6, 0x7d, 0x30, 0xb3, 0xa1, 0x83, 0xaf,
	0x8f, 0xf1, 0x09, 0x9f, 0x84, 0x30, 0xce, 0x9b, 0x71, 0x9c, 0x37, 0xff, 0x43, 0xce, 0xe4, 0x14,
	0x9c, 0x49, 0x76, 0xce, 0x11, 0x08, 0xfc, 0x32, 0x07, 0xe0, 0x16, 0x22, 0x6c, 0x10, 0xd9, 0x1d,
	0x83, 0x38, 0x17, 0x60, 0x02, 0x8b, 0x11, 0x56, 0x27, 0x4d, 0x3c, 0xfe, 0x33, 0x29, 0x2c, 0xdd,
	0x86, 0xf8, 0x33, 0xd7, 0xe4, 0x07, 0x41, 0xbc, 0x99, 0x4e, 0x13, 0x7a, 0xc2, 0x97, 0xc3, 0xf2,
	0xa6, 0x38, 0x97, 0xa8, 0x4c, 0x7f, 0xe4, 0x42, 0xff, 0xcd, 0x08, 0xea, 0xd3, 0x17, 0x08, 0x7f,
	0x15, 0xc0, 0x58, 0xe8, 0x92, 0x9d, 0xe2, 0x90, 0xde, 0xe7, 0x03, 0x47, 0x8a, 0x43, 0x7a, 0xbf,
	0x9b, 0xbc, 0xb8, 0xc6, 0x74, 0x5b, 0x11, 0xab, 0xf1, 0xbc, 0xa5, 0x47, 0xd8, 0x44, 0xce, 0xaf,
	0x61, 0x12, 0xaa, 0x9a, 0x1a, 0x62, 0xed, 0xac, 0x1d, 0x74, 0xe9, 0x90, 0xf9, 0x5e, 0x00, 0xe3,
	0xb5, 0x77, 0x91, 0xd6, 0xa5, 0xa8, 0xa1, 0x52, 0xed, 0xe0, 0x0d, 0xbc, 0x9b, 0xfc, 0x72, 0x8c,
	0x00, 0x52, 0x9f, 0xb3, 0x3d, 0x80, 0x58, 0x61, 0x1c, 0xe6, 0x45, 0x29, 0xfe, 0xcd, 0x66, 0xb9,
	0xf6, 0xa4, 0x82, 0xf8, 0x8a, 0x4e, 0xc4, 0x9f, 0xf1, 0xeb, 0xa1, 0x1f, 0x6d, 0x9a, 0xeb, 0xe1,
	0xe9, 0x23, 0x95, 0x58, 0xa4, 0xf1, 0x97, 0x3d, 0x3f, 0x4c, 0xa7, 0x57, 0x7e, 0x2b, 0x80, 0xfc,
	0x92, 0xa3, 0x77, 0xdb, 0x8f, 0x30, 0xf9, 0x7e, 0x1f, 0xb2, 0xcf, 0x1e, 0xe4, 0x2d, 0x16, 0xe4,
	0x9c, 0x58, 0x4e, 0x19, 0x64, 0x45, 0x63, 0x0b, 0x3a, 0x6a, 0x3e, 0x13, 0xf8, 0x8d, 0xd3, 0xf3,
	0x95, 0xf2, 0xc6, 0xe9, 0x9b, 0x67, 0xba, 0x71, 0x06, 0x50, 0x6e, 0x32, 0xf7, 0x93, 0x37, 0x2e,
	0x11, 0xe0, 0xd3, 0x1c, 0xb8, 0xdc, 0x44, 0x16, 0xb6, 0x7d, 0x67, 0x75, 0x37, 0xbf, 0x97, 0x11,
	0x55, 0x8d, 0x36, 0x81, 0xcb, 0x49, 0x91, 0xc4, 0xc2, 0x3d, 0x3e, 0xb5, 0x33, 0x7a, 0x71, 0xf9,
	0xbd, 0xcd, 0xf8, 0xdd, 0x15, 0xdf, 0x3a, 0x4d, 0xb1, 0xda, 0x71, 0x4b, 0x38, 0x9b, 0xf7, 0x87,
	0x00, 0xa6, 0x82, 0xba, 0x46, 0xa5, 0x58, 0xcc, 0xb2, 0x29, 0x03, 0x84, 0x58, 0x3a, 0x93, 0x0f,
	0x57, 0x86, 0x2a, 0x93, 0xe1, 0x36, 0xbc, 0x15, 0xb7, 0xcd, 0xa1, 0x14, 0xf5, 0x95, 0x70, 0x5d,
	0x2d, 0x3e, 0x06, 0xa2, 0x86, 0x3b, 0x09, 0xc1, 0x2c, 0x8e, 0x79, 0x37, 0xdb, 0x86, 0x73, 0xa8,
	0x6a, 0xad, 0xb8, 0xe6, 0x3a, 0x6e, 0xab, 0xa6, 0x5e, 0xc6, 0xb6, 0x2e, 0xe9, 0xc8, 0x64, 0x07,
	0x2e, 0xf7, 0xfb, 0xbd, 0x6a, 0x19, 0x64, 0xd0, 0x37, 0xfc, 0xdb, 0xde, 0xc8, 0xee, 0x30, 0x83,
	0xcc, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x46, 0x06, 0x22, 0xcd, 0x18, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OsConfigServiceClient is the client API for OsConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OsConfigServiceClient interface {
	// Create an OsConfig.
	CreateOsConfig(ctx context.Context, in *CreateOsConfigRequest, opts ...grpc.CallOption) (*OsConfig, error)
	// Get an OsConfig.
	GetOsConfig(ctx context.Context, in *GetOsConfigRequest, opts ...grpc.CallOption) (*OsConfig, error)
	// Get a page of OsConfigs.
	ListOsConfigs(ctx context.Context, in *ListOsConfigsRequest, opts ...grpc.CallOption) (*ListOsConfigsResponse, error)
	// Update an OsConfig.
	UpdateOsConfig(ctx context.Context, in *UpdateOsConfigRequest, opts ...grpc.CallOption) (*OsConfig, error)
	// Delete an OsConfig.
	DeleteOsConfig(ctx context.Context, in *DeleteOsConfigRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Create an OS Config Assignment.
	CreateAssignment(ctx context.Context, in *CreateAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error)
	// Get an OS Config Assignment.
	GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error)
	// Get a page of OS Config Assignments.
	ListAssignments(ctx context.Context, in *ListAssignmentsRequest, opts ...grpc.CallOption) (*ListAssignmentsResponse, error)
	// Update an OS Config Assignment.
	UpdateAssignment(ctx context.Context, in *UpdateAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error)
	// Delete an OS Config Assignment.
	DeleteAssignment(ctx context.Context, in *DeleteAssignmentRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Gets the access control policy for an OsConfig or an OS Config Assignment.
	// Returns NOT_FOUND error if the OsConfig does not exist. Returns an empty
	// policy if the resource exists but does not have a policy set.
	GetIamPolicy(ctx context.Context, in *v1.GetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Sets the access control policy for an OsConfig or an OS Config Assignment.
	// Replaces any existing policy.
	SetIamPolicy(ctx context.Context, in *v1.SetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error)
	// Test the access control policy for an OsConfig or an OS Config Assignment.
	TestIamPermissions(ctx context.Context, in *v1.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v1.TestIamPermissionsResponse, error)
	// Lookup the configs that are assigned to an instance. This lookup
	// will merge all configs that are assigned to the instance resolving
	// conflicts as necessary.
	// This is usually called by the agent running on the instance but can be
	// called directly to see what configs
	// This
	LookupConfigs(ctx context.Context, in *LookupConfigsRequest, opts ...grpc.CallOption) (*LookupConfigsResponse, error)
	// Patch GCE instances by creating and running a PatchJob.
	ExecutePatchJob(ctx context.Context, in *ExecutePatchJobRequest, opts ...grpc.CallOption) (*PatchJob, error)
	// Get the patch job. This can be used to track the progress of an
	// ongoing patch job or review the details of completed jobs.
	GetPatchJob(ctx context.Context, in *GetPatchJobRequest, opts ...grpc.CallOption) (*PatchJob, error)
	// Cancel a patch job. The patch job must be active. Canceled patch jobs
	// cannot be restarted.
	CancelPatchJob(ctx context.Context, in *CancelPatchJobRequest, opts ...grpc.CallOption) (*PatchJob, error)
	// Get a page of patch jobs.
	ListPatchJobs(ctx context.Context, in *ListPatchJobsRequest, opts ...grpc.CallOption) (*ListPatchJobsResponse, error)
	// Endpoint used by the agent to report back its state during a patch
	// job. This endpoint will also return the patch job's state and
	// configurations that the agent needs to know in order to run or stop
	// patching.
	//
	// This endpoint is only used by the agent. Using it in other ways may
	// affect the state of the active patch job and prevent the patches from
	// being correctly applied to this instance.
	ReportPatchJobInstanceDetails(ctx context.Context, in *ReportPatchJobInstanceDetailsRequest, opts ...grpc.CallOption) (*ReportPatchJobInstanceDetailsResponse, error)
	// Get a page of instances' details for a given patch job.
	ListPatchJobInstanceDetails(ctx context.Context, in *ListPatchJobInstanceDetailsRequest, opts ...grpc.CallOption) (*ListPatchJobInstanceDetailsResponse, error)
}

type osConfigServiceClient struct {
	cc *grpc.ClientConn
}

func NewOsConfigServiceClient(cc *grpc.ClientConn) OsConfigServiceClient {
	return &osConfigServiceClient{cc}
}

func (c *osConfigServiceClient) CreateOsConfig(ctx context.Context, in *CreateOsConfigRequest, opts ...grpc.CallOption) (*OsConfig, error) {
	out := new(OsConfig)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/CreateOsConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) GetOsConfig(ctx context.Context, in *GetOsConfigRequest, opts ...grpc.CallOption) (*OsConfig, error) {
	out := new(OsConfig)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/GetOsConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) ListOsConfigs(ctx context.Context, in *ListOsConfigsRequest, opts ...grpc.CallOption) (*ListOsConfigsResponse, error) {
	out := new(ListOsConfigsResponse)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/ListOsConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) UpdateOsConfig(ctx context.Context, in *UpdateOsConfigRequest, opts ...grpc.CallOption) (*OsConfig, error) {
	out := new(OsConfig)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/UpdateOsConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) DeleteOsConfig(ctx context.Context, in *DeleteOsConfigRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/DeleteOsConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) CreateAssignment(ctx context.Context, in *CreateAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error) {
	out := new(Assignment)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/CreateAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error) {
	out := new(Assignment)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/GetAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) ListAssignments(ctx context.Context, in *ListAssignmentsRequest, opts ...grpc.CallOption) (*ListAssignmentsResponse, error) {
	out := new(ListAssignmentsResponse)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/ListAssignments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) UpdateAssignment(ctx context.Context, in *UpdateAssignmentRequest, opts ...grpc.CallOption) (*Assignment, error) {
	out := new(Assignment)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/UpdateAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) DeleteAssignment(ctx context.Context, in *DeleteAssignmentRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/DeleteAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) GetIamPolicy(ctx context.Context, in *v1.GetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/GetIamPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) SetIamPolicy(ctx context.Context, in *v1.SetIamPolicyRequest, opts ...grpc.CallOption) (*v1.Policy, error) {
	out := new(v1.Policy)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/SetIamPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) TestIamPermissions(ctx context.Context, in *v1.TestIamPermissionsRequest, opts ...grpc.CallOption) (*v1.TestIamPermissionsResponse, error) {
	out := new(v1.TestIamPermissionsResponse)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/TestIamPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) LookupConfigs(ctx context.Context, in *LookupConfigsRequest, opts ...grpc.CallOption) (*LookupConfigsResponse, error) {
	out := new(LookupConfigsResponse)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/LookupConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) ExecutePatchJob(ctx context.Context, in *ExecutePatchJobRequest, opts ...grpc.CallOption) (*PatchJob, error) {
	out := new(PatchJob)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/ExecutePatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) GetPatchJob(ctx context.Context, in *GetPatchJobRequest, opts ...grpc.CallOption) (*PatchJob, error) {
	out := new(PatchJob)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/GetPatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) CancelPatchJob(ctx context.Context, in *CancelPatchJobRequest, opts ...grpc.CallOption) (*PatchJob, error) {
	out := new(PatchJob)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/CancelPatchJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) ListPatchJobs(ctx context.Context, in *ListPatchJobsRequest, opts ...grpc.CallOption) (*ListPatchJobsResponse, error) {
	out := new(ListPatchJobsResponse)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/ListPatchJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) ReportPatchJobInstanceDetails(ctx context.Context, in *ReportPatchJobInstanceDetailsRequest, opts ...grpc.CallOption) (*ReportPatchJobInstanceDetailsResponse, error) {
	out := new(ReportPatchJobInstanceDetailsResponse)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/ReportPatchJobInstanceDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osConfigServiceClient) ListPatchJobInstanceDetails(ctx context.Context, in *ListPatchJobInstanceDetailsRequest, opts ...grpc.CallOption) (*ListPatchJobInstanceDetailsResponse, error) {
	out := new(ListPatchJobInstanceDetailsResponse)
	err := c.cc.Invoke(ctx, "/google.cloud.osconfig.v1alpha1.OsConfigService/ListPatchJobInstanceDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OsConfigServiceServer is the server API for OsConfigService service.
type OsConfigServiceServer interface {
	// Create an OsConfig.
	CreateOsConfig(context.Context, *CreateOsConfigRequest) (*OsConfig, error)
	// Get an OsConfig.
	GetOsConfig(context.Context, *GetOsConfigRequest) (*OsConfig, error)
	// Get a page of OsConfigs.
	ListOsConfigs(context.Context, *ListOsConfigsRequest) (*ListOsConfigsResponse, error)
	// Update an OsConfig.
	UpdateOsConfig(context.Context, *UpdateOsConfigRequest) (*OsConfig, error)
	// Delete an OsConfig.
	DeleteOsConfig(context.Context, *DeleteOsConfigRequest) (*empty.Empty, error)
	// Create an OS Config Assignment.
	CreateAssignment(context.Context, *CreateAssignmentRequest) (*Assignment, error)
	// Get an OS Config Assignment.
	GetAssignment(context.Context, *GetAssignmentRequest) (*Assignment, error)
	// Get a page of OS Config Assignments.
	ListAssignments(context.Context, *ListAssignmentsRequest) (*ListAssignmentsResponse, error)
	// Update an OS Config Assignment.
	UpdateAssignment(context.Context, *UpdateAssignmentRequest) (*Assignment, error)
	// Delete an OS Config Assignment.
	DeleteAssignment(context.Context, *DeleteAssignmentRequest) (*empty.Empty, error)
	// Gets the access control policy for an OsConfig or an OS Config Assignment.
	// Returns NOT_FOUND error if the OsConfig does not exist. Returns an empty
	// policy if the resource exists but does not have a policy set.
	GetIamPolicy(context.Context, *v1.GetIamPolicyRequest) (*v1.Policy, error)
	// Sets the access control policy for an OsConfig or an OS Config Assignment.
	// Replaces any existing policy.
	SetIamPolicy(context.Context, *v1.SetIamPolicyRequest) (*v1.Policy, error)
	// Test the access control policy for an OsConfig or an OS Config Assignment.
	TestIamPermissions(context.Context, *v1.TestIamPermissionsRequest) (*v1.TestIamPermissionsResponse, error)
	// Lookup the configs that are assigned to an instance. This lookup
	// will merge all configs that are assigned to the instance resolving
	// conflicts as necessary.
	// This is usually called by the agent running on the instance but can be
	// called directly to see what configs
	// This
	LookupConfigs(context.Context, *LookupConfigsRequest) (*LookupConfigsResponse, error)
	// Patch GCE instances by creating and running a PatchJob.
	ExecutePatchJob(context.Context, *ExecutePatchJobRequest) (*PatchJob, error)
	// Get the patch job. This can be used to track the progress of an
	// ongoing patch job or review the details of completed jobs.
	GetPatchJob(context.Context, *GetPatchJobRequest) (*PatchJob, error)
	// Cancel a patch job. The patch job must be active. Canceled patch jobs
	// cannot be restarted.
	CancelPatchJob(context.Context, *CancelPatchJobRequest) (*PatchJob, error)
	// Get a page of patch jobs.
	ListPatchJobs(context.Context, *ListPatchJobsRequest) (*ListPatchJobsResponse, error)
	// Endpoint used by the agent to report back its state during a patch
	// job. This endpoint will also return the patch job's state and
	// configurations that the agent needs to know in order to run or stop
	// patching.
	//
	// This endpoint is only used by the agent. Using it in other ways may
	// affect the state of the active patch job and prevent the patches from
	// being correctly applied to this instance.
	ReportPatchJobInstanceDetails(context.Context, *ReportPatchJobInstanceDetailsRequest) (*ReportPatchJobInstanceDetailsResponse, error)
	// Get a page of instances' details for a given patch job.
	ListPatchJobInstanceDetails(context.Context, *ListPatchJobInstanceDetailsRequest) (*ListPatchJobInstanceDetailsResponse, error)
}

func RegisterOsConfigServiceServer(s *grpc.Server, srv OsConfigServiceServer) {
	s.RegisterService(&_OsConfigService_serviceDesc, srv)
}

func _OsConfigService_CreateOsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOsConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).CreateOsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/CreateOsConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).CreateOsConfig(ctx, req.(*CreateOsConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_GetOsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOsConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).GetOsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/GetOsConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).GetOsConfig(ctx, req.(*GetOsConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_ListOsConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOsConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).ListOsConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/ListOsConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).ListOsConfigs(ctx, req.(*ListOsConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_UpdateOsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOsConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).UpdateOsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/UpdateOsConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).UpdateOsConfig(ctx, req.(*UpdateOsConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_DeleteOsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOsConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).DeleteOsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/DeleteOsConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).DeleteOsConfig(ctx, req.(*DeleteOsConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_CreateAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).CreateAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/CreateAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).CreateAssignment(ctx, req.(*CreateAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_GetAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).GetAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/GetAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).GetAssignment(ctx, req.(*GetAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_ListAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).ListAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/ListAssignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).ListAssignments(ctx, req.(*ListAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_UpdateAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).UpdateAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/UpdateAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).UpdateAssignment(ctx, req.(*UpdateAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_DeleteAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).DeleteAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/DeleteAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).DeleteAssignment(ctx, req.(*DeleteAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_GetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).GetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/GetIamPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).GetIamPolicy(ctx, req.(*v1.GetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_SetIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.SetIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).SetIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/SetIamPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).SetIamPolicy(ctx, req.(*v1.SetIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_TestIamPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.TestIamPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).TestIamPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/TestIamPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).TestIamPermissions(ctx, req.(*v1.TestIamPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_LookupConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).LookupConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/LookupConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).LookupConfigs(ctx, req.(*LookupConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_ExecutePatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).ExecutePatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/ExecutePatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).ExecutePatchJob(ctx, req.(*ExecutePatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_GetPatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).GetPatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/GetPatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).GetPatchJob(ctx, req.(*GetPatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_CancelPatchJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPatchJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).CancelPatchJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/CancelPatchJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).CancelPatchJob(ctx, req.(*CancelPatchJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_ListPatchJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPatchJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).ListPatchJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/ListPatchJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).ListPatchJobs(ctx, req.(*ListPatchJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_ReportPatchJobInstanceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPatchJobInstanceDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).ReportPatchJobInstanceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/ReportPatchJobInstanceDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).ReportPatchJobInstanceDetails(ctx, req.(*ReportPatchJobInstanceDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsConfigService_ListPatchJobInstanceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPatchJobInstanceDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsConfigServiceServer).ListPatchJobInstanceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.cloud.osconfig.v1alpha1.OsConfigService/ListPatchJobInstanceDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsConfigServiceServer).ListPatchJobInstanceDetails(ctx, req.(*ListPatchJobInstanceDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OsConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.cloud.osconfig.v1alpha1.OsConfigService",
	HandlerType: (*OsConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOsConfig",
			Handler:    _OsConfigService_CreateOsConfig_Handler,
		},
		{
			MethodName: "GetOsConfig",
			Handler:    _OsConfigService_GetOsConfig_Handler,
		},
		{
			MethodName: "ListOsConfigs",
			Handler:    _OsConfigService_ListOsConfigs_Handler,
		},
		{
			MethodName: "UpdateOsConfig",
			Handler:    _OsConfigService_UpdateOsConfig_Handler,
		},
		{
			MethodName: "DeleteOsConfig",
			Handler:    _OsConfigService_DeleteOsConfig_Handler,
		},
		{
			MethodName: "CreateAssignment",
			Handler:    _OsConfigService_CreateAssignment_Handler,
		},
		{
			MethodName: "GetAssignment",
			Handler:    _OsConfigService_GetAssignment_Handler,
		},
		{
			MethodName: "ListAssignments",
			Handler:    _OsConfigService_ListAssignments_Handler,
		},
		{
			MethodName: "UpdateAssignment",
			Handler:    _OsConfigService_UpdateAssignment_Handler,
		},
		{
			MethodName: "DeleteAssignment",
			Handler:    _OsConfigService_DeleteAssignment_Handler,
		},
		{
			MethodName: "GetIamPolicy",
			Handler:    _OsConfigService_GetIamPolicy_Handler,
		},
		{
			MethodName: "SetIamPolicy",
			Handler:    _OsConfigService_SetIamPolicy_Handler,
		},
		{
			MethodName: "TestIamPermissions",
			Handler:    _OsConfigService_TestIamPermissions_Handler,
		},
		{
			MethodName: "LookupConfigs",
			Handler:    _OsConfigService_LookupConfigs_Handler,
		},
		{
			MethodName: "ExecutePatchJob",
			Handler:    _OsConfigService_ExecutePatchJob_Handler,
		},
		{
			MethodName: "GetPatchJob",
			Handler:    _OsConfigService_GetPatchJob_Handler,
		},
		{
			MethodName: "CancelPatchJob",
			Handler:    _OsConfigService_CancelPatchJob_Handler,
		},
		{
			MethodName: "ListPatchJobs",
			Handler:    _OsConfigService_ListPatchJobs_Handler,
		},
		{
			MethodName: "ReportPatchJobInstanceDetails",
			Handler:    _OsConfigService_ReportPatchJobInstanceDetails_Handler,
		},
		{
			MethodName: "ListPatchJobInstanceDetails",
			Handler:    _OsConfigService_ListPatchJobInstanceDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "google/cloud/osconfig/v1alpha1/osconfig_service.proto",
}
