// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/osconfig/v1alpha1/patch_jobs.proto

package osconfig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/iam/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Overall state of the patch job.
type ReportPatchJobInstanceDetailsResponse_PatchJobState int32

const (
	// Unspecified is invalid.
	ReportPatchJobInstanceDetailsResponse_PATCH_JOB_STATE_UNSPECIFIED ReportPatchJobInstanceDetailsResponse_PatchJobState = 0
	// The patch job is running. Instances will continue to run patch
	// deployment steps.
	ReportPatchJobInstanceDetailsResponse_ACTIVE ReportPatchJobInstanceDetailsResponse_PatchJobState = 1
	// The patch job is complete.
	ReportPatchJobInstanceDetailsResponse_COMPLETED ReportPatchJobInstanceDetailsResponse_PatchJobState = 2
)

var ReportPatchJobInstanceDetailsResponse_PatchJobState_name = map[int32]string{
	0: "PATCH_JOB_STATE_UNSPECIFIED",
	1: "ACTIVE",
	2: "COMPLETED",
}

var ReportPatchJobInstanceDetailsResponse_PatchJobState_value = map[string]int32{
	"PATCH_JOB_STATE_UNSPECIFIED": 0,
	"ACTIVE":                      1,
	"COMPLETED":                   2,
}

func (x ReportPatchJobInstanceDetailsResponse_PatchJobState) String() string {
	return proto.EnumName(ReportPatchJobInstanceDetailsResponse_PatchJobState_name, int32(x))
}

func (ReportPatchJobInstanceDetailsResponse_PatchJobState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{6, 0}
}

// Enumeration of the various states a patch job passes through as it
// executes.
type PatchJob_State int32

const (
	// State must be specified.
	PatchJob_STATE_UNSPECIFIED PatchJob_State = 0
	// The patch job was successfully initiated.
	PatchJob_STARTED PatchJob_State = 1
	// The patch job is looking up instances to run the patch on.
	PatchJob_INSTANCE_LOOKUP PatchJob_State = 2
	// Instances are being patched.
	PatchJob_PATCHING PatchJob_State = 3
	// Patch job completed successfully.
	PatchJob_SUCCEEDED PatchJob_State = 4
	// Patch job completed but there were errors.
	PatchJob_COMPLETED_WITH_ERRORS PatchJob_State = 5
	// The patch job was canceled.
	PatchJob_CANCELED PatchJob_State = 6
	// The patch job has timed out.
	PatchJob_TIMED_OUT PatchJob_State = 7
)

var PatchJob_State_name = map[int32]string{
	0: "STATE_UNSPECIFIED",
	1: "STARTED",
	2: "INSTANCE_LOOKUP",
	3: "PATCHING",
	4: "SUCCEEDED",
	5: "COMPLETED_WITH_ERRORS",
	6: "CANCELED",
	7: "TIMED_OUT",
}

var PatchJob_State_value = map[string]int32{
	"STATE_UNSPECIFIED":     0,
	"STARTED":               1,
	"INSTANCE_LOOKUP":       2,
	"PATCHING":              3,
	"SUCCEEDED":             4,
	"COMPLETED_WITH_ERRORS": 5,
	"CANCELED":              6,
	"TIMED_OUT":             7,
}

func (x PatchJob_State) String() string {
	return proto.EnumName(PatchJob_State_name, int32(x))
}

func (PatchJob_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{9, 0}
}

// Post-patch reboot settings.
type PatchConfig_RebootConfig int32

const (
	// The default behavior is DEFAULT.
	PatchConfig_REBOOT_CONFIG_UNSPECIFIED PatchConfig_RebootConfig = 0
	// The agent will decide if a reboot is necessary by checking well known
	// signals such as registry keys or `/var/run/reboot-required`.
	PatchConfig_DEFAULT PatchConfig_RebootConfig = 1
	// Always reboot the machine after the update has completed.
	PatchConfig_ALWAYS PatchConfig_RebootConfig = 2
	// Never reboot the machine after the update has completed.
	PatchConfig_NEVER PatchConfig_RebootConfig = 3
)

var PatchConfig_RebootConfig_name = map[int32]string{
	0: "REBOOT_CONFIG_UNSPECIFIED",
	1: "DEFAULT",
	2: "ALWAYS",
	3: "NEVER",
}

var PatchConfig_RebootConfig_value = map[string]int32{
	"REBOOT_CONFIG_UNSPECIFIED": 0,
	"DEFAULT":                   1,
	"ALWAYS":                    2,
	"NEVER":                     3,
}

func (x PatchConfig_RebootConfig) String() string {
	return proto.EnumName(PatchConfig_RebootConfig_name, int32(x))
}

func (PatchConfig_RebootConfig) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{10, 0}
}

// Patch state of an instance.
type Instance_PatchState int32

const (
	// Unspecified.
	Instance_PATCH_STATE_UNSPECIFIED Instance_PatchState = 0
	// The instance has not been notified yet.
	Instance_PENDING Instance_PatchState = 1
	// Instance is inactive and cannot be patched.
	Instance_INACTIVE Instance_PatchState = 2
	// The instance has been notified that it should patch.
	Instance_NOTIFIED Instance_PatchState = 3
	// The instance ack'd the notification and will begin shortly.
	Instance_STARTED Instance_PatchState = 4
	// The instance is downloading patches.
	Instance_DOWNLOADING_PATCHES Instance_PatchState = 5
	// The instance is applying patches.
	Instance_APPLYING_PATCHES Instance_PatchState = 6
	// The instance is rebooting.
	Instance_REBOOTING Instance_PatchState = 7
	// The instance has completed applying patches.
	Instance_SUCCEEDED Instance_PatchState = 8
	// The instance has completed applying patches but a reboot is required.
	Instance_REBOOT_REQUIRED Instance_PatchState = 9
	// The instance has failed to apply the patch.
	Instance_FAILED Instance_PatchState = 10
)

var Instance_PatchState_name = map[int32]string{
	0:  "PATCH_STATE_UNSPECIFIED",
	1:  "PENDING",
	2:  "INACTIVE",
	3:  "NOTIFIED",
	4:  "STARTED",
	5:  "DOWNLOADING_PATCHES",
	6:  "APPLYING_PATCHES",
	7:  "REBOOTING",
	8:  "SUCCEEDED",
	9:  "REBOOT_REQUIRED",
	10: "FAILED",
}

var Instance_PatchState_value = map[string]int32{
	"PATCH_STATE_UNSPECIFIED": 0,
	"PENDING":                 1,
	"INACTIVE":                2,
	"NOTIFIED":                3,
	"STARTED":                 4,
	"DOWNLOADING_PATCHES":     5,
	"APPLYING_PATCHES":        6,
	"REBOOTING":               7,
	"SUCCEEDED":               8,
	"REBOOT_REQUIRED":         9,
	"FAILED":                  10,
}

func (x Instance_PatchState) String() string {
	return proto.EnumName(Instance_PatchState_name, int32(x))
}

func (Instance_PatchState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{11, 0}
}

// A request message to initiate patching across GCE instances.
type ExecutePatchJobRequest struct {
	// The project in which to run this patch in the form `projects/*`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Description of the PatchJob. Length of the description is limited
	// to 1024 characters.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Required. There must be at least one instance to patch for this deployment
	// to succeed. This is the same filter used when listing compute instances.
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional. Patch configuration being applied. If omitted, instances will be
	// patched using the default configurations.
	PatchConfig *PatchConfig `protobuf:"bytes,4,opt,name=patch_config,json=patchConfig,proto3" json:"patch_config,omitempty"`
	// Optional. Duration of the patch job. After the duration ends, the
	// patch job will time out.
	Duration             *duration.Duration `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ExecutePatchJobRequest) Reset()         { *m = ExecutePatchJobRequest{} }
func (m *ExecutePatchJobRequest) String() string { return proto.CompactTextString(m) }
func (*ExecutePatchJobRequest) ProtoMessage()    {}
func (*ExecutePatchJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{0}
}

func (m *ExecutePatchJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutePatchJobRequest.Unmarshal(m, b)
}
func (m *ExecutePatchJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutePatchJobRequest.Marshal(b, m, deterministic)
}
func (m *ExecutePatchJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutePatchJobRequest.Merge(m, src)
}
func (m *ExecutePatchJobRequest) XXX_Size() int {
	return xxx_messageInfo_ExecutePatchJobRequest.Size(m)
}
func (m *ExecutePatchJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutePatchJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutePatchJobRequest proto.InternalMessageInfo

func (m *ExecutePatchJobRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ExecutePatchJobRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ExecutePatchJobRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ExecutePatchJobRequest) GetPatchConfig() *PatchConfig {
	if m != nil {
		return m.PatchConfig
	}
	return nil
}

func (m *ExecutePatchJobRequest) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

// Request to get an active or completed patch job.
type GetPatchJobRequest struct {
	// Name of the patch in the form `projects/*/patchJobs/*`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPatchJobRequest) Reset()         { *m = GetPatchJobRequest{} }
func (m *GetPatchJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetPatchJobRequest) ProtoMessage()    {}
func (*GetPatchJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{1}
}

func (m *GetPatchJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPatchJobRequest.Unmarshal(m, b)
}
func (m *GetPatchJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPatchJobRequest.Marshal(b, m, deterministic)
}
func (m *GetPatchJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPatchJobRequest.Merge(m, src)
}
func (m *GetPatchJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetPatchJobRequest.Size(m)
}
func (m *GetPatchJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPatchJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPatchJobRequest proto.InternalMessageInfo

func (m *GetPatchJobRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Request to list the instances' details for a patch job.
type ListPatchJobInstanceDetailsRequest struct {
	// In the form of `projects/*/patchJobs/*`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of instance details records to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A pagination token returned from a previous call
	// that indicates where this listing should continue from.
	// This field is optional.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPatchJobInstanceDetailsRequest) Reset()         { *m = ListPatchJobInstanceDetailsRequest{} }
func (m *ListPatchJobInstanceDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPatchJobInstanceDetailsRequest) ProtoMessage()    {}
func (*ListPatchJobInstanceDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{2}
}

func (m *ListPatchJobInstanceDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPatchJobInstanceDetailsRequest.Unmarshal(m, b)
}
func (m *ListPatchJobInstanceDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPatchJobInstanceDetailsRequest.Marshal(b, m, deterministic)
}
func (m *ListPatchJobInstanceDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPatchJobInstanceDetailsRequest.Merge(m, src)
}
func (m *ListPatchJobInstanceDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPatchJobInstanceDetailsRequest.Size(m)
}
func (m *ListPatchJobInstanceDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPatchJobInstanceDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPatchJobInstanceDetailsRequest proto.InternalMessageInfo

func (m *ListPatchJobInstanceDetailsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListPatchJobInstanceDetailsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPatchJobInstanceDetailsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// A response message for listing the instances' details for a patch job.
type ListPatchJobInstanceDetailsResponse struct {
	// The list of instance status.
	PatchJobInstanceDetails []*PatchJobInstanceDetails `protobuf:"bytes,1,rep,name=patch_job_instance_details,json=patchJobInstanceDetails,proto3" json:"patch_job_instance_details,omitempty"`
	// A pagination token that can be used to get the next page of results.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPatchJobInstanceDetailsResponse) Reset()         { *m = ListPatchJobInstanceDetailsResponse{} }
func (m *ListPatchJobInstanceDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPatchJobInstanceDetailsResponse) ProtoMessage()    {}
func (*ListPatchJobInstanceDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{3}
}

func (m *ListPatchJobInstanceDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPatchJobInstanceDetailsResponse.Unmarshal(m, b)
}
func (m *ListPatchJobInstanceDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPatchJobInstanceDetailsResponse.Marshal(b, m, deterministic)
}
func (m *ListPatchJobInstanceDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPatchJobInstanceDetailsResponse.Merge(m, src)
}
func (m *ListPatchJobInstanceDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPatchJobInstanceDetailsResponse.Size(m)
}
func (m *ListPatchJobInstanceDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPatchJobInstanceDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPatchJobInstanceDetailsResponse proto.InternalMessageInfo

func (m *ListPatchJobInstanceDetailsResponse) GetPatchJobInstanceDetails() []*PatchJobInstanceDetails {
	if m != nil {
		return m.PatchJobInstanceDetails
	}
	return nil
}

func (m *ListPatchJobInstanceDetailsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Patch details of an instance.
type PatchJobInstanceDetails struct {
	// The instance name in the form `projects/*/zones/*/instances/*`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The unique, system-generated identifier for the instance.
	InstanceSystemId string `protobuf:"bytes,2,opt,name=instance_system_id,json=instanceSystemId,proto3" json:"instance_system_id,omitempty"`
	// Current state of instance patch.
	State Instance_PatchState `protobuf:"varint,3,opt,name=state,proto3,enum=google.cloud.osconfig.v1alpha1.Instance_PatchState" json:"state,omitempty"`
	// If the patch has failed, this is the reason.
	FailureReason string `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// Number of times the agent attempted to apply the patch.
	AttemptCount         int64    `protobuf:"varint,5,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchJobInstanceDetails) Reset()         { *m = PatchJobInstanceDetails{} }
func (m *PatchJobInstanceDetails) String() string { return proto.CompactTextString(m) }
func (*PatchJobInstanceDetails) ProtoMessage()    {}
func (*PatchJobInstanceDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{4}
}

func (m *PatchJobInstanceDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchJobInstanceDetails.Unmarshal(m, b)
}
func (m *PatchJobInstanceDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchJobInstanceDetails.Marshal(b, m, deterministic)
}
func (m *PatchJobInstanceDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchJobInstanceDetails.Merge(m, src)
}
func (m *PatchJobInstanceDetails) XXX_Size() int {
	return xxx_messageInfo_PatchJobInstanceDetails.Size(m)
}
func (m *PatchJobInstanceDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchJobInstanceDetails.DiscardUnknown(m)
}

var xxx_messageInfo_PatchJobInstanceDetails proto.InternalMessageInfo

func (m *PatchJobInstanceDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PatchJobInstanceDetails) GetInstanceSystemId() string {
	if m != nil {
		return m.InstanceSystemId
	}
	return ""
}

func (m *PatchJobInstanceDetails) GetState() Instance_PatchState {
	if m != nil {
		return m.State
	}
	return Instance_PATCH_STATE_UNSPECIFIED
}

func (m *PatchJobInstanceDetails) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *PatchJobInstanceDetails) GetAttemptCount() int64 {
	if m != nil {
		return m.AttemptCount
	}
	return 0
}

// Request to report the patch status for an instance.
type ReportPatchJobInstanceDetailsRequest struct {
	// The instance reporting its status in the form
	// `projects/*/zones/*/instances/*`
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Required. The unique, system-generated identifier for the instance.
	//
	// This is the immutable, auto-generated ID assigned to the instance upon
	// creation. This is needed here because GCE instance names are not
	// tombstoned; it is possible to delete an instance and create a new one with
	// the same name; this provides a mechanism for this API to identify distinct
	// instances in this case.
	InstanceSystemId string `protobuf:"bytes,2,opt,name=instance_system_id,json=instanceSystemId,proto3" json:"instance_system_id,omitempty"`
	// Unique identifier of the patch job this request applies to.
	PatchJobName string `protobuf:"bytes,3,opt,name=patch_job_name,json=patchJobName,proto3" json:"patch_job_name,omitempty"`
	// State of current patch execution on the instance.
	State Instance_PatchState `protobuf:"varint,4,opt,name=state,proto3,enum=google.cloud.osconfig.v1alpha1.Instance_PatchState" json:"state,omitempty"`
	// Reason for failure.
	FailureReason string `protobuf:"bytes,6,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	// Number of times the agent attempted to apply the patch.
	AttemptCount         int64    `protobuf:"varint,7,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportPatchJobInstanceDetailsRequest) Reset()         { *m = ReportPatchJobInstanceDetailsRequest{} }
func (m *ReportPatchJobInstanceDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*ReportPatchJobInstanceDetailsRequest) ProtoMessage()    {}
func (*ReportPatchJobInstanceDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{5}
}

func (m *ReportPatchJobInstanceDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportPatchJobInstanceDetailsRequest.Unmarshal(m, b)
}
func (m *ReportPatchJobInstanceDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportPatchJobInstanceDetailsRequest.Marshal(b, m, deterministic)
}
func (m *ReportPatchJobInstanceDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportPatchJobInstanceDetailsRequest.Merge(m, src)
}
func (m *ReportPatchJobInstanceDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_ReportPatchJobInstanceDetailsRequest.Size(m)
}
func (m *ReportPatchJobInstanceDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportPatchJobInstanceDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportPatchJobInstanceDetailsRequest proto.InternalMessageInfo

func (m *ReportPatchJobInstanceDetailsRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *ReportPatchJobInstanceDetailsRequest) GetInstanceSystemId() string {
	if m != nil {
		return m.InstanceSystemId
	}
	return ""
}

func (m *ReportPatchJobInstanceDetailsRequest) GetPatchJobName() string {
	if m != nil {
		return m.PatchJobName
	}
	return ""
}

func (m *ReportPatchJobInstanceDetailsRequest) GetState() Instance_PatchState {
	if m != nil {
		return m.State
	}
	return Instance_PATCH_STATE_UNSPECIFIED
}

func (m *ReportPatchJobInstanceDetailsRequest) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *ReportPatchJobInstanceDetailsRequest) GetAttemptCount() int64 {
	if m != nil {
		return m.AttemptCount
	}
	return 0
}

// Response from reporting instance patch details. Includes information the
// agent needs to continue or stop patching.
type ReportPatchJobInstanceDetailsResponse struct {
	// Unique identifier for the current patch job.
	PatchJobName string `protobuf:"bytes,1,opt,name=patch_job_name,json=patchJobName,proto3" json:"patch_job_name,omitempty"`
	// Patch configuration the agent should apply.
	PatchConfig *PatchConfig `protobuf:"bytes,2,opt,name=patch_config,json=patchConfig,proto3" json:"patch_config,omitempty"`
	// State of the overall patch. If the patch is no longer active, the
	// agent should not begin a new patch step.
	PatchJobState ReportPatchJobInstanceDetailsResponse_PatchJobState `protobuf:"varint,3,opt,name=patch_job_state,json=patchJobState,proto3,enum=google.cloud.osconfig.v1alpha1.ReportPatchJobInstanceDetailsResponse_PatchJobState" json:"patch_job_state,omitempty"`
	// If this patch is a dry run, the agent will report that it has finished
	// without running any updates on the VM.
	DryRun               bool     `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportPatchJobInstanceDetailsResponse) Reset()         { *m = ReportPatchJobInstanceDetailsResponse{} }
func (m *ReportPatchJobInstanceDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*ReportPatchJobInstanceDetailsResponse) ProtoMessage()    {}
func (*ReportPatchJobInstanceDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{6}
}

func (m *ReportPatchJobInstanceDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportPatchJobInstanceDetailsResponse.Unmarshal(m, b)
}
func (m *ReportPatchJobInstanceDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportPatchJobInstanceDetailsResponse.Marshal(b, m, deterministic)
}
func (m *ReportPatchJobInstanceDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportPatchJobInstanceDetailsResponse.Merge(m, src)
}
func (m *ReportPatchJobInstanceDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_ReportPatchJobInstanceDetailsResponse.Size(m)
}
func (m *ReportPatchJobInstanceDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportPatchJobInstanceDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportPatchJobInstanceDetailsResponse proto.InternalMessageInfo

func (m *ReportPatchJobInstanceDetailsResponse) GetPatchJobName() string {
	if m != nil {
		return m.PatchJobName
	}
	return ""
}

func (m *ReportPatchJobInstanceDetailsResponse) GetPatchConfig() *PatchConfig {
	if m != nil {
		return m.PatchConfig
	}
	return nil
}

func (m *ReportPatchJobInstanceDetailsResponse) GetPatchJobState() ReportPatchJobInstanceDetailsResponse_PatchJobState {
	if m != nil {
		return m.PatchJobState
	}
	return ReportPatchJobInstanceDetailsResponse_PATCH_JOB_STATE_UNSPECIFIED
}

func (m *ReportPatchJobInstanceDetailsResponse) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

// A request message for listing patch jobs.
type ListPatchJobsRequest struct {
	// In the form of `projects/*`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of instance status to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A pagination token returned from a previous call
	// that indicates where this listing should continue from.
	// This field is optional.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPatchJobsRequest) Reset()         { *m = ListPatchJobsRequest{} }
func (m *ListPatchJobsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPatchJobsRequest) ProtoMessage()    {}
func (*ListPatchJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{7}
}

func (m *ListPatchJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPatchJobsRequest.Unmarshal(m, b)
}
func (m *ListPatchJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPatchJobsRequest.Marshal(b, m, deterministic)
}
func (m *ListPatchJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPatchJobsRequest.Merge(m, src)
}
func (m *ListPatchJobsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPatchJobsRequest.Size(m)
}
func (m *ListPatchJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPatchJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPatchJobsRequest proto.InternalMessageInfo

func (m *ListPatchJobsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListPatchJobsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPatchJobsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// A response message for listing patch jobs.
type ListPatchJobsResponse struct {
	// The list of patch jobs.
	PatchJobs []*PatchJob `protobuf:"bytes,1,rep,name=patch_jobs,json=patchJobs,proto3" json:"patch_jobs,omitempty"`
	// A pagination token that can be used to get the next page of results.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPatchJobsResponse) Reset()         { *m = ListPatchJobsResponse{} }
func (m *ListPatchJobsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPatchJobsResponse) ProtoMessage()    {}
func (*ListPatchJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{8}
}

func (m *ListPatchJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPatchJobsResponse.Unmarshal(m, b)
}
func (m *ListPatchJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPatchJobsResponse.Marshal(b, m, deterministic)
}
func (m *ListPatchJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPatchJobsResponse.Merge(m, src)
}
func (m *ListPatchJobsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPatchJobsResponse.Size(m)
}
func (m *ListPatchJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPatchJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPatchJobsResponse proto.InternalMessageInfo

func (m *ListPatchJobsResponse) GetPatchJobs() []*PatchJob {
	if m != nil {
		return m.PatchJobs
	}
	return nil
}

func (m *ListPatchJobsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// A high level representation of a patch job that is either in progress
// or has completed.
//
// Instances' details are not included in the job. To paginate through instance
// details, use ListPatchJobInstanceDetails.
type PatchJob struct {
	// Output only. Unique identifier for this patch job in the form
	// `projects/*/patchJobs/*`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the patch job. Length of the description is limited
	// to 1024 characters.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Output only. Time this PatchJob was created.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. Last time this PatchJob was updated.
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Output only. The current state of the PatchJob.
	State PatchJob_State `protobuf:"varint,5,opt,name=state,proto3,enum=google.cloud.osconfig.v1alpha1.PatchJob_State" json:"state,omitempty"`
	// Required. There must be at least one instance to patch for this job
	// to succeed. This is the same filter used when listing compute instances.
	Filter string `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	// Patch configuration being applied.
	PatchConfig *PatchConfig `protobuf:"bytes,7,opt,name=patch_config,json=patchConfig,proto3" json:"patch_config,omitempty"`
	// Duration of the patch job. After the duration ends, the
	// patch job will time out.
	Duration *duration.Duration `protobuf:"bytes,8,opt,name=duration,proto3" json:"duration,omitempty"`
	// Summary of instance details.
	InstanceDetailsSummary *PatchJob_InstanceDetailsSummary `protobuf:"bytes,9,opt,name=instance_details_summary,json=instanceDetailsSummary,proto3" json:"instance_details_summary,omitempty"`
	// If this patch job is a dry run, the agent will report that it has
	// finished without running any updates on the VM.
	DryRun               bool     `protobuf:"varint,10,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchJob) Reset()         { *m = PatchJob{} }
func (m *PatchJob) String() string { return proto.CompactTextString(m) }
func (*PatchJob) ProtoMessage()    {}
func (*PatchJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{9}
}

func (m *PatchJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchJob.Unmarshal(m, b)
}
func (m *PatchJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchJob.Marshal(b, m, deterministic)
}
func (m *PatchJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchJob.Merge(m, src)
}
func (m *PatchJob) XXX_Size() int {
	return xxx_messageInfo_PatchJob.Size(m)
}
func (m *PatchJob) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchJob.DiscardUnknown(m)
}

var xxx_messageInfo_PatchJob proto.InternalMessageInfo

func (m *PatchJob) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PatchJob) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PatchJob) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *PatchJob) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *PatchJob) GetState() PatchJob_State {
	if m != nil {
		return m.State
	}
	return PatchJob_STATE_UNSPECIFIED
}

func (m *PatchJob) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *PatchJob) GetPatchConfig() *PatchConfig {
	if m != nil {
		return m.PatchConfig
	}
	return nil
}

func (m *PatchJob) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *PatchJob) GetInstanceDetailsSummary() *PatchJob_InstanceDetailsSummary {
	if m != nil {
		return m.InstanceDetailsSummary
	}
	return nil
}

func (m *PatchJob) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

// A summary of the current patch state across all instances this patch job
// affects. Contains counts of instances in different states. These states map
// to InstancePatchState. List patch job instance details to see the specific
// states of each instance.
type PatchJob_InstanceDetailsSummary struct {
	// Number of instances pending patch deployment.
	InstancesPending int64 `protobuf:"varint,1,opt,name=instances_pending,json=instancesPending,proto3" json:"instances_pending,omitempty"`
	// Number of instances that are inactive.
	InstancesInactive int64 `protobuf:"varint,2,opt,name=instances_inactive,json=instancesInactive,proto3" json:"instances_inactive,omitempty"`
	// Number of instances notified about patch deployment.
	InstancesNotified int64 `protobuf:"varint,3,opt,name=instances_notified,json=instancesNotified,proto3" json:"instances_notified,omitempty"`
	// Number of instances ack'd and will start shortly.
	InstancesStarted int64 `protobuf:"varint,4,opt,name=instances_started,json=instancesStarted,proto3" json:"instances_started,omitempty"`
	// Number of instances that are downloading patches.
	InstancesDownloadingPatches int64 `protobuf:"varint,5,opt,name=instances_downloading_patches,json=instancesDownloadingPatches,proto3" json:"instances_downloading_patches,omitempty"`
	// Number of instances that are downloading patches.
	InstancesApplyingPatches int64 `protobuf:"varint,6,opt,name=instances_applying_patches,json=instancesApplyingPatches,proto3" json:"instances_applying_patches,omitempty"`
	// Number of instances rebooting.
	InstancesRebooting int64 `protobuf:"varint,7,opt,name=instances_rebooting,json=instancesRebooting,proto3" json:"instances_rebooting,omitempty"`
	// Number of instances that have completed.
	InstancesFinished int64 `protobuf:"varint,8,opt,name=instances_finished,json=instancesFinished,proto3" json:"instances_finished,omitempty"`
	// Number of instances that have completed.
	InstancesFinishedRebootRequired int64 `protobuf:"varint,9,opt,name=instances_finished_reboot_required,json=instancesFinishedRebootRequired,proto3" json:"instances_finished_reboot_required,omitempty"`
	// Number of instances that failed.
	InstancesFailed      int64    `protobuf:"varint,10,opt,name=instances_failed,json=instancesFailed,proto3" json:"instances_failed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchJob_InstanceDetailsSummary) Reset()         { *m = PatchJob_InstanceDetailsSummary{} }
func (m *PatchJob_InstanceDetailsSummary) String() string { return proto.CompactTextString(m) }
func (*PatchJob_InstanceDetailsSummary) ProtoMessage()    {}
func (*PatchJob_InstanceDetailsSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{9, 0}
}

func (m *PatchJob_InstanceDetailsSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchJob_InstanceDetailsSummary.Unmarshal(m, b)
}
func (m *PatchJob_InstanceDetailsSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchJob_InstanceDetailsSummary.Marshal(b, m, deterministic)
}
func (m *PatchJob_InstanceDetailsSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchJob_InstanceDetailsSummary.Merge(m, src)
}
func (m *PatchJob_InstanceDetailsSummary) XXX_Size() int {
	return xxx_messageInfo_PatchJob_InstanceDetailsSummary.Size(m)
}
func (m *PatchJob_InstanceDetailsSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchJob_InstanceDetailsSummary.DiscardUnknown(m)
}

var xxx_messageInfo_PatchJob_InstanceDetailsSummary proto.InternalMessageInfo

func (m *PatchJob_InstanceDetailsSummary) GetInstancesPending() int64 {
	if m != nil {
		return m.InstancesPending
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesInactive() int64 {
	if m != nil {
		return m.InstancesInactive
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesNotified() int64 {
	if m != nil {
		return m.InstancesNotified
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesStarted() int64 {
	if m != nil {
		return m.InstancesStarted
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesDownloadingPatches() int64 {
	if m != nil {
		return m.InstancesDownloadingPatches
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesApplyingPatches() int64 {
	if m != nil {
		return m.InstancesApplyingPatches
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesRebooting() int64 {
	if m != nil {
		return m.InstancesRebooting
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesFinished() int64 {
	if m != nil {
		return m.InstancesFinished
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesFinishedRebootRequired() int64 {
	if m != nil {
		return m.InstancesFinishedRebootRequired
	}
	return 0
}

func (m *PatchJob_InstanceDetailsSummary) GetInstancesFailed() int64 {
	if m != nil {
		return m.InstancesFailed
	}
	return 0
}

// Patch configuration specifications. Contains details on specifically how to
// apply the patch(es) to an instance.
type PatchConfig struct {
	// Optional. Post-patch reboot settings.
	RebootConfig PatchConfig_RebootConfig `protobuf:"varint,1,opt,name=reboot_config,json=rebootConfig,proto3,enum=google.cloud.osconfig.v1alpha1.PatchConfig_RebootConfig" json:"reboot_config,omitempty"`
	// Optional. Retry strategy can be defined to have the agent retry patching
	// during the window if patching fails. If omitted, the agent will use its
	// default retry strategy.
	RetryStrategy *RetryStrategy `protobuf:"bytes,2,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	// Apt update settings. Use this override the default apt patch rules.
	Apt *AptSettings `protobuf:"bytes,3,opt,name=apt,proto3" json:"apt,omitempty"`
	// Yum update settings. Use this override the default yum patch rules.
	Yum *YumSettings `protobuf:"bytes,4,opt,name=yum,proto3" json:"yum,omitempty"`
	// Goo update settings. Use this override the default goo patch rules.
	Goo *GooSettings `protobuf:"bytes,5,opt,name=goo,proto3" json:"goo,omitempty"`
	// Zypper update settings. Use this override the default zypper patch rules.
	Zypper *ZypperSettings `protobuf:"bytes,6,opt,name=zypper,proto3" json:"zypper,omitempty"`
	// Windows update settings. Use this override the default windows patch rules.
	WindowsUpdate        *WindowsUpdateSettings `protobuf:"bytes,7,opt,name=windows_update,json=windowsUpdate,proto3" json:"windows_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PatchConfig) Reset()         { *m = PatchConfig{} }
func (m *PatchConfig) String() string { return proto.CompactTextString(m) }
func (*PatchConfig) ProtoMessage()    {}
func (*PatchConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{10}
}

func (m *PatchConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchConfig.Unmarshal(m, b)
}
func (m *PatchConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchConfig.Marshal(b, m, deterministic)
}
func (m *PatchConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchConfig.Merge(m, src)
}
func (m *PatchConfig) XXX_Size() int {
	return xxx_messageInfo_PatchConfig.Size(m)
}
func (m *PatchConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PatchConfig proto.InternalMessageInfo

func (m *PatchConfig) GetRebootConfig() PatchConfig_RebootConfig {
	if m != nil {
		return m.RebootConfig
	}
	return PatchConfig_REBOOT_CONFIG_UNSPECIFIED
}

func (m *PatchConfig) GetRetryStrategy() *RetryStrategy {
	if m != nil {
		return m.RetryStrategy
	}
	return nil
}

func (m *PatchConfig) GetApt() *AptSettings {
	if m != nil {
		return m.Apt
	}
	return nil
}

func (m *PatchConfig) GetYum() *YumSettings {
	if m != nil {
		return m.Yum
	}
	return nil
}

func (m *PatchConfig) GetGoo() *GooSettings {
	if m != nil {
		return m.Goo
	}
	return nil
}

func (m *PatchConfig) GetZypper() *ZypperSettings {
	if m != nil {
		return m.Zypper
	}
	return nil
}

func (m *PatchConfig) GetWindowsUpdate() *WindowsUpdateSettings {
	if m != nil {
		return m.WindowsUpdate
	}
	return nil
}

// Namespace for Instance state enums.
type Instance struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{11}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

// Message for canceling a patch job.
type CancelPatchJobRequest struct {
	// Name of the patch in the form `projects/*/patchJobs/*`
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPatchJobRequest) Reset()         { *m = CancelPatchJobRequest{} }
func (m *CancelPatchJobRequest) String() string { return proto.CompactTextString(m) }
func (*CancelPatchJobRequest) ProtoMessage()    {}
func (*CancelPatchJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_465201847e28b68d, []int{12}
}

func (m *CancelPatchJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPatchJobRequest.Unmarshal(m, b)
}
func (m *CancelPatchJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPatchJobRequest.Marshal(b, m, deterministic)
}
func (m *CancelPatchJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPatchJobRequest.Merge(m, src)
}
func (m *CancelPatchJobRequest) XXX_Size() int {
	return xxx_messageInfo_CancelPatchJobRequest.Size(m)
}
func (m *CancelPatchJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPatchJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPatchJobRequest proto.InternalMessageInfo

func (m *CancelPatchJobRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.ReportPatchJobInstanceDetailsResponse_PatchJobState", ReportPatchJobInstanceDetailsResponse_PatchJobState_name, ReportPatchJobInstanceDetailsResponse_PatchJobState_value)
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.PatchJob_State", PatchJob_State_name, PatchJob_State_value)
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.PatchConfig_RebootConfig", PatchConfig_RebootConfig_name, PatchConfig_RebootConfig_value)
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.Instance_PatchState", Instance_PatchState_name, Instance_PatchState_value)
	proto.RegisterType((*ExecutePatchJobRequest)(nil), "google.cloud.osconfig.v1alpha1.ExecutePatchJobRequest")
	proto.RegisterType((*GetPatchJobRequest)(nil), "google.cloud.osconfig.v1alpha1.GetPatchJobRequest")
	proto.RegisterType((*ListPatchJobInstanceDetailsRequest)(nil), "google.cloud.osconfig.v1alpha1.ListPatchJobInstanceDetailsRequest")
	proto.RegisterType((*ListPatchJobInstanceDetailsResponse)(nil), "google.cloud.osconfig.v1alpha1.ListPatchJobInstanceDetailsResponse")
	proto.RegisterType((*PatchJobInstanceDetails)(nil), "google.cloud.osconfig.v1alpha1.PatchJobInstanceDetails")
	proto.RegisterType((*ReportPatchJobInstanceDetailsRequest)(nil), "google.cloud.osconfig.v1alpha1.ReportPatchJobInstanceDetailsRequest")
	proto.RegisterType((*ReportPatchJobInstanceDetailsResponse)(nil), "google.cloud.osconfig.v1alpha1.ReportPatchJobInstanceDetailsResponse")
	proto.RegisterType((*ListPatchJobsRequest)(nil), "google.cloud.osconfig.v1alpha1.ListPatchJobsRequest")
	proto.RegisterType((*ListPatchJobsResponse)(nil), "google.cloud.osconfig.v1alpha1.ListPatchJobsResponse")
	proto.RegisterType((*PatchJob)(nil), "google.cloud.osconfig.v1alpha1.PatchJob")
	proto.RegisterType((*PatchJob_InstanceDetailsSummary)(nil), "google.cloud.osconfig.v1alpha1.PatchJob.InstanceDetailsSummary")
	proto.RegisterType((*PatchConfig)(nil), "google.cloud.osconfig.v1alpha1.PatchConfig")
	proto.RegisterType((*Instance)(nil), "google.cloud.osconfig.v1alpha1.Instance")
	proto.RegisterType((*CancelPatchJobRequest)(nil), "google.cloud.osconfig.v1alpha1.CancelPatchJobRequest")
}

func init() {
	proto.RegisterFile("google/cloud/osconfig/v1alpha1/patch_jobs.proto", fileDescriptor_465201847e28b68d)
}

var fileDescriptor_465201847e28b68d = []byte{
	// 1518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x5f, 0x73, 0xd3, 0x46,
	0x10, 0xaf, 0x62, 0xc7, 0xb1, 0xd7, 0x71, 0x22, 0x0e, 0x92, 0x18, 0xa7, 0x94, 0x8c, 0x80, 0x4e,
	0x3a, 0x14, 0x7b, 0x08, 0xc3, 0xb4, 0x33, 0xb4, 0xd3, 0x71, 0x6c, 0x25, 0x18, 0x8c, 0x6d, 0x64,
	0x85, 0x0c, 0x4c, 0x3b, 0x1a, 0xc5, 0xba, 0x18, 0x51, 0x5b, 0x27, 0xa4, 0x13, 0xc1, 0xf4, 0xa5,
	0x8f, 0xfd, 0x02, 0xfd, 0x12, 0x9d, 0xe9, 0xa7, 0xe8, 0x73, 0xbf, 0x40, 0xbf, 0x45, 0xfb, 0xc4,
	0x63, 0xe7, 0x4e, 0xa7, 0x3f, 0x49, 0x0c, 0x36, 0xd3, 0xf2, 0x96, 0xdb, 0xdd, 0xdf, 0xee, 0xed,
	0xde, 0xee, 0x6f, 0xe5, 0x40, 0x6d, 0x48, 0xc8, 0x70, 0x84, 0x6b, 0x83, 0x11, 0x09, 0xac, 0x1a,
	0xf1, 0x07, 0xc4, 0x39, 0xb6, 0x87, 0xb5, 0x57, 0xb7, 0xcd, 0x91, 0xfb, 0xdc, 0xbc, 0x5d, 0x73,
	0x4d, 0x3a, 0x78, 0x6e, 0xbc, 0x20, 0x47, 0x7e, 0xd5, 0xf5, 0x08, 0x25, 0xe8, 0xb3, 0x10, 0x50,
	0xe5, 0x80, 0x6a, 0x04, 0xa8, 0x46, 0x80, 0xca, 0xa7, 0xc2, 0xa1, 0xe9, 0xda, 0x35, 0xd3, 0x71,
	0x08, 0x35, 0xa9, 0x4d, 0x1c, 0x81, 0xae, 0xdc, 0x99, 0x2b, 0x9c, 0x4b, 0x46, 0xf6, 0xc0, 0xc6,
	0x11, 0xa8, 0x22, 0x40, 0xb6, 0x39, 0xae, 0xbd, 0xba, 0x5d, 0xe3, 0xda, 0x89, 0xd0, 0x89, 0xeb,
	0xd4, 0xf8, 0xe9, 0x28, 0x38, 0xae, 0x59, 0x81, 0xc7, 0x23, 0x0a, 0xfd, 0xd5, 0xb3, 0x7a, 0x6a,
	0x8f, 0xb1, 0x4f, 0xcd, 0xb1, 0x1b, 0x1a, 0x28, 0x7f, 0x4b, 0xb0, 0xae, 0xbe, 0xc6, 0x83, 0x80,
	0xe2, 0x1e, 0x0b, 0xfe, 0x80, 0x1c, 0x69, 0xf8, 0x65, 0x80, 0x7d, 0x8a, 0xd6, 0x21, 0xe7, 0x9a,
	0x1e, 0x76, 0x68, 0x59, 0xda, 0x92, 0xb6, 0x0b, 0x9a, 0x38, 0xa1, 0x2d, 0x28, 0x5a, 0xd8, 0x1f,
	0x78, 0xb6, 0xcb, 0x02, 0x95, 0x17, 0xb8, 0x32, 0x2d, 0x62, 0xc8, 0x63, 0x7b, 0x44, 0xb1, 0x57,
	0xce, 0x84, 0xc8, 0xf0, 0x84, 0x3a, 0xb0, 0x1c, 0x66, 0x18, 0xe6, 0x5d, 0xce, 0x6e, 0x49, 0xdb,
	0xc5, 0x9d, 0x9b, 0xd5, 0xf7, 0xd7, 0xb4, 0xca, 0x2f, 0xd6, 0xe0, 0x42, 0xad, 0xe8, 0x26, 0x07,
	0x74, 0x17, 0xf2, 0x51, 0xbe, 0xe5, 0x45, 0xee, 0xeb, 0x72, 0xe4, 0x2b, 0x4a, 0xb8, 0xda, 0x14,
	0x06, 0x5a, 0x6c, 0xaa, 0x6c, 0x03, 0xda, 0xc7, 0xf4, 0x6c, 0xba, 0x08, 0xb2, 0x8e, 0x39, 0xc6,
	0x22, 0x59, 0xfe, 0xb7, 0xf2, 0x1a, 0x94, 0xb6, 0xed, 0xc7, 0xa6, 0x2d, 0xc7, 0xa7, 0xa6, 0x33,
	0xc0, 0x4d, 0x4c, 0x4d, 0x7b, 0xe4, 0xcf, 0x2a, 0xd4, 0x26, 0x14, 0x5c, 0x73, 0x88, 0x0d, 0xdf,
	0x7e, 0x83, 0x79, 0x99, 0x16, 0xb5, 0x3c, 0x13, 0xf4, 0xed, 0x37, 0x18, 0x5d, 0x01, 0xe0, 0x4a,
	0x4a, 0x7e, 0xc4, 0x8e, 0xa8, 0x13, 0x37, 0xd7, 0x99, 0x40, 0xf9, 0x43, 0x82, 0x6b, 0xef, 0x0d,
	0xed, 0xbb, 0xc4, 0xf1, 0x31, 0xa2, 0x50, 0x89, 0x7b, 0xd4, 0xb0, 0x85, 0x91, 0x61, 0x85, 0x56,
	0x65, 0x69, 0x2b, 0xb3, 0x5d, 0xdc, 0xf9, 0x6a, 0xae, 0x02, 0x4f, 0x09, 0xb2, 0xe1, 0x4e, 0x57,
	0xa0, 0xcf, 0x61, 0xd5, 0xc1, 0xaf, 0xa9, 0x91, 0xca, 0x20, 0x6c, 0x83, 0x12, 0x13, 0xf7, 0xe2,
	0x2c, 0xfe, 0x91, 0x60, 0xe3, 0x1d, 0xce, 0xa7, 0xd5, 0x1b, 0x7d, 0x09, 0x28, 0xce, 0xc1, 0x9f,
	0xf8, 0x14, 0x8f, 0x0d, 0xdb, 0x12, 0xae, 0xe5, 0x48, 0xd3, 0xe7, 0x8a, 0x96, 0x85, 0x5a, 0xb0,
	0xe8, 0x53, 0x93, 0x62, 0x5e, 0xbd, 0x95, 0x9d, 0x3b, 0xb3, 0xd2, 0x8c, 0x6e, 0x10, 0xe6, 0xdb,
	0x67, 0x50, 0x2d, 0xf4, 0x80, 0x6e, 0xc0, 0xca, 0xb1, 0x69, 0x8f, 0x02, 0x0f, 0x1b, 0x1e, 0x36,
	0x7d, 0xe2, 0xf0, 0xde, 0x2c, 0x68, 0x25, 0x21, 0xd5, 0xb8, 0x10, 0x5d, 0x83, 0x92, 0x49, 0x29,
	0x1e, 0xbb, 0xd4, 0x18, 0x90, 0xc0, 0xa1, 0xbc, 0xeb, 0x32, 0xda, 0xb2, 0x10, 0x36, 0x98, 0x4c,
	0xf9, 0x7d, 0x01, 0xae, 0x6b, 0xd8, 0x25, 0xde, 0xac, 0xbe, 0xa9, 0x40, 0xde, 0xc3, 0x3e, 0x09,
	0xbc, 0x41, 0x54, 0x85, 0xf8, 0xfc, 0x81, 0x95, 0xb8, 0x0e, 0x2b, 0x49, 0x17, 0xf0, 0xaa, 0x86,
	0x0d, 0xb5, 0x1c, 0x3d, 0x60, 0x87, 0x55, 0x37, 0xae, 0x57, 0xf6, 0x23, 0xd4, 0x2b, 0x37, 0x57,
	0xbd, 0x96, 0xa6, 0xd4, 0xeb, 0xe7, 0x0c, 0xdc, 0x98, 0x51, 0x2f, 0xd1, 0xec, 0xe7, 0xd3, 0x94,
	0xa6, 0xa4, 0x79, 0x96, 0x65, 0x16, 0xfe, 0x23, 0xcb, 0xfc, 0x04, 0xab, 0x49, 0xd4, 0x74, 0xc3,
	0xf5, 0x67, 0xb9, 0x9c, 0x2b, 0xab, 0x78, 0xfa, 0xc2, 0x02, 0x97, 0xdc, 0xf4, 0x11, 0x6d, 0xc0,
	0x92, 0xe5, 0x4d, 0x0c, 0x2f, 0x08, 0x3b, 0x32, 0xaf, 0xe5, 0x2c, 0x6f, 0xa2, 0x05, 0x8e, 0xf2,
	0x10, 0x4a, 0xa7, 0x80, 0xe8, 0x2a, 0x6c, 0xf6, 0xea, 0x7a, 0xe3, 0xbe, 0xf1, 0xa0, 0xbb, 0x6b,
	0xf4, 0xf5, 0xba, 0xae, 0x1a, 0x07, 0x9d, 0x7e, 0x4f, 0x6d, 0xb4, 0xf6, 0x5a, 0x6a, 0x53, 0xfe,
	0x04, 0x01, 0xe4, 0xea, 0x0d, 0xbd, 0xf5, 0x44, 0x95, 0x25, 0x54, 0x82, 0x42, 0xa3, 0xfb, 0xa8,
	0xd7, 0x56, 0x75, 0xb5, 0x29, 0x2f, 0x28, 0x2f, 0xe0, 0x52, 0x9a, 0x6c, 0x3e, 0x2a, 0xb3, 0xfd,
	0x22, 0xc1, 0xda, 0x99, 0x60, 0xe2, 0x79, 0xf7, 0x19, 0x30, 0xda, 0xb7, 0x82, 0xbb, 0xb6, 0xe7,
	0xe5, 0x2e, 0x16, 0x42, 0x38, 0x9c, 0x9b, 0x9e, 0xde, 0x16, 0x20, 0x1f, 0xe1, 0xa7, 0xf2, 0xd1,
	0xec, 0x55, 0x77, 0x0f, 0x8a, 0x03, 0x0f, 0x9b, 0x14, 0x1b, 0x6c, 0xb3, 0xf2, 0x6c, 0x8b, 0x3b,
	0x95, 0x73, 0x5b, 0x48, 0x8f, 0xd6, 0xae, 0x06, 0xa1, 0x39, 0x13, 0x30, 0x70, 0xe0, 0x5a, 0x31,
	0x38, 0x3b, 0x1b, 0x1c, 0x9a, 0x73, 0x70, 0x33, 0x9a, 0xe6, 0x45, 0xde, 0x8c, 0xd5, 0x79, 0x0b,
	0x55, 0x3d, 0x35, 0xc8, 0xc9, 0xaa, 0xce, 0xbd, 0x77, 0x55, 0x2f, 0xfd, 0x8f, 0xab, 0x3a, 0x3f,
	0xf7, 0xaa, 0x46, 0x13, 0x28, 0x9f, 0x5d, 0x6a, 0x86, 0x1f, 0x8c, 0xc7, 0xa6, 0x37, 0x29, 0x17,
	0xb8, 0x9b, 0xef, 0xe6, 0xce, 0xfb, 0xcc, 0xfc, 0xf5, 0x43, 0x37, 0xda, 0xba, 0x3d, 0x55, 0x9e,
	0x9e, 0x3c, 0x48, 0x4f, 0x5e, 0xe5, 0xb7, 0x2c, 0xac, 0x4f, 0xf7, 0x85, 0x6e, 0xc2, 0x85, 0xc8,
	0x9b, 0x6f, 0xb8, 0xd8, 0xb1, 0x6c, 0x67, 0xc8, 0x1b, 0x2a, 0x93, 0x90, 0xb6, 0xdf, 0x0b, 0xe5,
	0xe8, 0x56, 0x42, 0xf1, 0xbe, 0x61, 0x3b, 0xe6, 0x80, 0xda, 0xaf, 0xc2, 0x69, 0xca, 0x68, 0x89,
	0x9b, 0x96, 0x50, 0x9c, 0x36, 0x77, 0x08, 0xb5, 0x8f, 0x6d, 0x6c, 0xf1, 0x86, 0x4b, 0x9b, 0x77,
	0x84, 0xe2, 0xf4, 0x55, 0x7c, 0x6a, 0x7a, 0x14, 0x5b, 0xbc, 0xc3, 0xd2, 0x57, 0xe9, 0x87, 0x72,
	0xb4, 0x0b, 0x57, 0x12, 0x63, 0x8b, 0x9c, 0x38, 0x23, 0x62, 0xb2, 0x3b, 0x1a, 0xfc, 0x09, 0xb1,
	0x2f, 0xf6, 0xdc, 0x66, 0x6c, 0xd4, 0x4c, 0x6c, 0x7a, 0xa1, 0x09, 0xfa, 0x06, 0x2a, 0x89, 0x0f,
	0xd3, 0x75, 0x47, 0x93, 0xb4, 0x83, 0x1c, 0x77, 0x10, 0x3f, 0xa6, 0x5f, 0x17, 0x06, 0x11, 0xba,
	0x06, 0x17, 0x13, 0xb4, 0x87, 0x8f, 0x08, 0xa1, 0xac, 0x76, 0xe1, 0xbe, 0x48, 0x12, 0xd7, 0x22,
	0xcd, 0xe9, 0x72, 0x1c, 0xdb, 0x8e, 0xed, 0x3f, 0xc7, 0x16, 0x6f, 0xad, 0x74, 0x39, 0xf6, 0x84,
	0x02, 0x3d, 0x04, 0xe5, 0xbc, 0xb9, 0x08, 0x64, 0x78, 0xf8, 0x65, 0x60, 0x7b, 0xd8, 0xe2, 0x2d,
	0x95, 0xd1, 0xae, 0x9e, 0x83, 0x87, 0x61, 0x35, 0x61, 0x86, 0xbe, 0x00, 0x39, 0xe5, 0xcc, 0xb4,
	0x47, 0xd8, 0xe2, 0x3d, 0x92, 0xd1, 0x56, 0x13, 0x28, 0x17, 0x2b, 0xbf, 0x4a, 0xb0, 0x18, 0xf2,
	0xf3, 0x1a, 0x5c, 0x98, 0xc6, 0xca, 0x45, 0x58, 0xea, 0xeb, 0x75, 0x8d, 0xf1, 0xb0, 0x84, 0x2e,
	0xc2, 0x6a, 0xab, 0xd3, 0xd7, 0xeb, 0x9d, 0x86, 0x6a, 0xb4, 0xbb, 0xdd, 0x87, 0x07, 0x3d, 0x79,
	0x01, 0x2d, 0x43, 0x9e, 0x13, 0x7b, 0xab, 0xb3, 0x2f, 0x67, 0x18, 0x73, 0xf7, 0x0f, 0x1a, 0x0d,
	0x55, 0x6d, 0xaa, 0x4d, 0x39, 0x8b, 0x2e, 0xc3, 0x5a, 0x4c, 0xe4, 0xc6, 0x61, 0x4b, 0xbf, 0x6f,
	0xa8, 0x9a, 0xd6, 0xd5, 0xfa, 0xf2, 0x22, 0xc3, 0x35, 0x98, 0xa7, 0xb6, 0xda, 0x94, 0x73, 0x0c,
	0xa7, 0xb7, 0x1e, 0xa9, 0x4d, 0xa3, 0x7b, 0xa0, 0xcb, 0x4b, 0xca, 0xdb, 0x2c, 0x14, 0x53, 0xc3,
	0x8a, 0x7e, 0x80, 0x92, 0x28, 0x86, 0x18, 0x78, 0x89, 0xb3, 0xca, 0xd7, 0x1f, 0x30, 0xf0, 0xd5,
	0xb0, 0x4a, 0x62, 0xfa, 0x97, 0xbd, 0xd4, 0x09, 0xe9, 0xb0, 0xe2, 0x61, 0xea, 0x4d, 0x0c, 0x9f,
	0x7a, 0x26, 0xc5, 0xc3, 0x89, 0xd8, 0xca, 0xb7, 0x66, 0xaf, 0x50, 0xea, 0x4d, 0xfa, 0x02, 0xa4,
	0x95, 0xbc, 0xf4, 0x11, 0x7d, 0x0b, 0x19, 0xd3, 0xa5, 0x82, 0x74, 0x67, 0x72, 0x53, 0xdd, 0xa5,
	0x7d, 0x4c, 0x59, 0xf3, 0xf8, 0x1a, 0xc3, 0x31, 0xf8, 0x24, 0x18, 0xcf, 0xfb, 0x2b, 0xe4, 0x69,
	0x30, 0x4e, 0xe0, 0x93, 0x60, 0xcc, 0xe0, 0x43, 0x42, 0xc4, 0x0f, 0x8f, 0x99, 0xf0, 0x7d, 0x42,
	0x12, 0xf8, 0x90, 0x10, 0xb4, 0x07, 0xb9, 0x37, 0x13, 0xd7, 0x15, 0xcc, 0x5b, 0x9c, 0x4d, 0xe0,
	0xcf, 0xb8, 0x75, 0xec, 0x44, 0xa0, 0xd1, 0xf7, 0xb0, 0x72, 0x62, 0x3b, 0x16, 0x39, 0xf1, 0x8d,
	0x70, 0x3b, 0x08, 0xae, 0xbe, 0x3b, 0xcb, 0xdf, 0x61, 0x88, 0x3a, 0xe0, 0xa0, 0xd8, 0x6d, 0xe9,
	0x24, 0x2d, 0x56, 0x1e, 0xc3, 0x72, 0xfa, 0x59, 0xd1, 0x15, 0xb8, 0xac, 0xa9, 0xbb, 0xdd, 0xae,
	0x6e, 0x34, 0xba, 0x9d, 0xbd, 0xd6, 0xfe, 0xf9, 0x6e, 0x6e, 0xaa, 0x7b, 0xf5, 0x83, 0xb6, 0x2e,
	0x4b, 0xfc, 0x83, 0xa3, 0x7d, 0x58, 0x7f, 0xda, 0x97, 0x17, 0x50, 0x01, 0x16, 0x3b, 0xea, 0x13,
	0x55, 0x93, 0x33, 0xca, 0x5f, 0x12, 0xe4, 0x23, 0xfe, 0x54, 0xfe, 0x94, 0x00, 0x92, 0xcf, 0x4b,
	0xb4, 0x09, 0x1b, 0xe1, 0x47, 0xcc, 0x3b, 0x46, 0xa5, 0xa7, 0x76, 0x9a, 0x6c, 0x0e, 0x24, 0xd6,
	0xdd, 0xad, 0x8e, 0xf8, 0x9e, 0xe1, 0x33, 0xd2, 0xe9, 0xea, 0xa1, 0x61, 0x26, 0x3d, 0x53, 0x59,
	0xb4, 0x01, 0x17, 0x9b, 0xdd, 0xc3, 0x4e, 0xbb, 0x5b, 0x67, 0x48, 0x83, 0xbb, 0x57, 0xd9, 0x7c,
	0x5c, 0x02, 0xb9, 0xde, 0xeb, 0xb5, 0x9f, 0xa6, 0xa5, 0x7c, 0x4e, 0xc2, 0x04, 0x59, 0x98, 0xa5,
	0xd3, 0xe3, 0x96, 0x67, 0x03, 0x2a, 0xd2, 0xd7, 0xd4, 0xc7, 0x07, 0x2d, 0x4d, 0x6d, 0xca, 0x05,
	0x96, 0xe7, 0x5e, 0xbd, 0xc5, 0xc6, 0x0c, 0x94, 0x9b, 0xb0, 0xd6, 0x60, 0x89, 0x8d, 0xe6, 0xf8,
	0x79, 0xb9, 0x7b, 0x02, 0xca, 0x80, 0x8c, 0x67, 0xbc, 0xd3, 0x6e, 0x21, 0xfe, 0x52, 0x7a, 0xb6,
	0x27, 0x4c, 0x87, 0x64, 0x64, 0x3a, 0xc3, 0x2a, 0xf1, 0x86, 0xb5, 0x21, 0x76, 0xf8, 0x02, 0x15,
	0xff, 0xc9, 0x30, 0x5d, 0xdb, 0x7f, 0xd7, 0xbf, 0x17, 0xee, 0x45, 0x92, 0xa3, 0x1c, 0x87, 0xdc,
	0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xbd, 0x77, 0x29, 0xff, 0x10, 0x00, 0x00,
}
