// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/cloud/osconfig/v1alpha1/patch_policies.proto

package osconfig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	date "google.golang.org/genproto/googleapis/type/date"
	dayofweek "google.golang.org/genproto/googleapis/type/dayofweek"
	timeofday "google.golang.org/genproto/googleapis/type/timeofday"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// State of the PatchPolicy.
type PatchPolicy_State int32

const (
	// When unspecified, the PatchPolicy will be considered ACTIVE.
	PatchPolicy_STATE_UNSPECIFIED PatchPolicy_State = 0
	// The PatchPolicy is being applied to VMs.
	PatchPolicy_ACTIVE PatchPolicy_State = 1
	// The PatchPolicy will not be applied to VMs.
	PatchPolicy_INACTIVE PatchPolicy_State = 2
)

var PatchPolicy_State_name = map[int32]string{
	0: "STATE_UNSPECIFIED",
	1: "ACTIVE",
	2: "INACTIVE",
}

var PatchPolicy_State_value = map[string]int32{
	"STATE_UNSPECIFIED": 0,
	"ACTIVE":            1,
	"INACTIVE":          2,
}

func (x PatchPolicy_State) String() string {
	return proto.EnumName(PatchPolicy_State_name, int32(x))
}

func (PatchPolicy_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{0, 0}
}

// Post-patch reboot settings.
type PatchPolicy_RebootConfig int32

const (
	// Default value is DEFAULT.
	PatchPolicy_REBOOT_CONFIG_UNSPECIFIED PatchPolicy_RebootConfig = 0
	// The agent will decide if a reboot is necessary by checking well known
	// signals such as registry keys or `/var/run/reboot-required`.
	PatchPolicy_DEFAULT PatchPolicy_RebootConfig = 1
	// Always reboot the machine after the update has completed.
	PatchPolicy_ALWAYS PatchPolicy_RebootConfig = 2
	// Never reboot the machine after the update has completed.
	PatchPolicy_NEVER PatchPolicy_RebootConfig = 3
)

var PatchPolicy_RebootConfig_name = map[int32]string{
	0: "REBOOT_CONFIG_UNSPECIFIED",
	1: "DEFAULT",
	2: "ALWAYS",
	3: "NEVER",
}

var PatchPolicy_RebootConfig_value = map[string]int32{
	"REBOOT_CONFIG_UNSPECIFIED": 0,
	"DEFAULT":                   1,
	"ALWAYS":                    2,
	"NEVER":                     3,
}

func (x PatchPolicy_RebootConfig) String() string {
	return proto.EnumName(PatchPolicy_RebootConfig_name, int32(x))
}

func (PatchPolicy_RebootConfig) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{0, 1}
}

// Apt patch type.
type AptSettings_Type int32

const (
	// By default, a full upgrade will be performed.
	AptSettings_TYPE_UNSPECIFIED AptSettings_Type = 0
	// run `apt-get dist-upgrade` instead.
	AptSettings_DIST AptSettings_Type = 1
)

var AptSettings_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "DIST",
}

var AptSettings_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"DIST":             1,
}

func (x AptSettings_Type) String() string {
	return proto.EnumName(AptSettings_Type_name, int32(x))
}

func (AptSettings_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{3, 0}
}

// Microsoft Windows update classifications as defined in
// [1]
// https://support.microsoft.com/en-us/help/824684/description-of-the-standard-terminology-that-is-used-to-describe-micro
type WindowsUpdateSettings_Classification int32

const (
	// Invalid. If classifications are included, they must be specified.
	WindowsUpdateSettings_CLASSIFICATION_UNSPECIFIED WindowsUpdateSettings_Classification = 0
	// "A widely released fix for a specific problem that addresses a critical,
	// non-security-related bug." [1]
	WindowsUpdateSettings_CRITICAL WindowsUpdateSettings_Classification = 1
	// "A widely released fix for a product-specific, security-related
	// vulnerability. Security vulnerabilities are rated by their severity. The
	// severity rating is indicated in the Microsoft security bulletin as
	// critical, important, moderate, or low." [1]
	WindowsUpdateSettings_SECURITY WindowsUpdateSettings_Classification = 2
	// "A widely released and frequent software update that contains additions
	// to a product’s definition database. Definition databases are often used
	// to detect objects that have specific attributes, such as malicious code,
	// phishing websites, or junk mail." [1]
	WindowsUpdateSettings_DEFINITION WindowsUpdateSettings_Classification = 3
	// "Software that controls the input and output of a device." [1]
	WindowsUpdateSettings_DRIVER WindowsUpdateSettings_Classification = 4
	// "New product functionality that is first distributed outside the context
	// of a product release and that is typically included in the next full
	// product release." [1]
	WindowsUpdateSettings_FEATURE_PACK WindowsUpdateSettings_Classification = 5
	// "A tested, cumulative set of all hotfixes, security updates, critical
	// updates, and updates. Additionally, service packs may contain additional
	// fixes for problems that are found internally since the release of the
	// product. Service packs my also contain a limited number of
	// customer-requested design changes or features." [1]
	WindowsUpdateSettings_SERVICE_PACK WindowsUpdateSettings_Classification = 6
	// "A utility or feature that helps complete a task or set of tasks." [1]
	WindowsUpdateSettings_TOOL WindowsUpdateSettings_Classification = 7
	// "A tested, cumulative set of hotfixes, security updates, critical
	// updates, and updates that are packaged together for easy deployment. A
	// rollup generally targets a specific area, such as security, or a
	// component of a product, such as Internet Information Services (IIS)." [1]
	WindowsUpdateSettings_UPDATE_ROLLUP WindowsUpdateSettings_Classification = 8
	// "A widely released fix for a specific problem. An update addresses a
	// noncritical, non-security-related bug." [1]
	WindowsUpdateSettings_UPDATE WindowsUpdateSettings_Classification = 9
)

var WindowsUpdateSettings_Classification_name = map[int32]string{
	0: "CLASSIFICATION_UNSPECIFIED",
	1: "CRITICAL",
	2: "SECURITY",
	3: "DEFINITION",
	4: "DRIVER",
	5: "FEATURE_PACK",
	6: "SERVICE_PACK",
	7: "TOOL",
	8: "UPDATE_ROLLUP",
	9: "UPDATE",
}

var WindowsUpdateSettings_Classification_value = map[string]int32{
	"CLASSIFICATION_UNSPECIFIED": 0,
	"CRITICAL":                   1,
	"SECURITY":                   2,
	"DEFINITION":                 3,
	"DRIVER":                     4,
	"FEATURE_PACK":               5,
	"SERVICE_PACK":               6,
	"TOOL":                       7,
	"UPDATE_ROLLUP":              8,
	"UPDATE":                     9,
}

func (x WindowsUpdateSettings_Classification) String() string {
	return proto.EnumName(WindowsUpdateSettings_Classification_name, int32(x))
}

func (WindowsUpdateSettings_Classification) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{7, 0}
}

// A PatchPolicy enables recurring, scheduled patching for groups of VMs. To
// patch a set of VMs, create a PatchPolicy, then create an Assignment mapping
// this policy to one or more VMs.
type PatchPolicy struct {
	// Identifying name for this PatchConfig.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the PatchConfig. Length of the description is limited
	// to 1024 characters.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Output only. Time this PatchPolicy was created.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. Last time this PatchPolicy was updated.
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Represents cloud resource labels.
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The PatchPolicy will stop being applied when its state is INACTIVE.
	State PatchPolicy_State `protobuf:"varint,6,opt,name=state,proto3,enum=google.cloud.osconfig.v1alpha1.PatchPolicy_State" json:"state,omitempty"`
	// Windows update settings. Set this if this policy should update Windows VMs.
	WindowsUpdate *WindowsUpdateSettings `protobuf:"bytes,7,opt,name=windows_update,json=windowsUpdate,proto3" json:"windows_update,omitempty"`
	// The frequency this patch will be applied. When left unspecified, the patch
	// will not be automatically applied to any VMs.
	PatchWindow *PatchWindow `protobuf:"bytes,8,opt,name=patch_window,json=patchWindow,proto3" json:"patch_window,omitempty"`
	// Optional. Post-patch reboot settings.
	RebootConfig PatchPolicy_RebootConfig `protobuf:"varint,9,opt,name=reboot_config,json=rebootConfig,proto3,enum=google.cloud.osconfig.v1alpha1.PatchPolicy_RebootConfig" json:"reboot_config,omitempty"`
	// Optional. Retry strategy can be defined to have the agent retry patching
	// during the window if patching fails. If omitted, the agent will not retry
	// failed patches.
	RetryStrategy *RetryStrategy `protobuf:"bytes,10,opt,name=retry_strategy,json=retryStrategy,proto3" json:"retry_strategy,omitempty"`
	// Apt update settings. Set this if this policy should update VMs that use
	// apt.
	Apt *AptSettings `protobuf:"bytes,11,opt,name=apt,proto3" json:"apt,omitempty"`
	// Yum update settings. Set this if this policy should update VMs that use
	// yum.
	Yum *YumSettings `protobuf:"bytes,12,opt,name=yum,proto3" json:"yum,omitempty"`
	// Goo update settings. Set this if this policy should update VMs that use
	// googet.
	Goo *GooSettings `protobuf:"bytes,13,opt,name=goo,proto3" json:"goo,omitempty"`
	// Zypper update settings. Set this if this policy should update VMs that use
	// zypper.
	Zypper *ZypperSettings `protobuf:"bytes,14,opt,name=zypper,proto3" json:"zypper,omitempty"`
	// Output only. The unique version of this patch policy.
	Version              int64    `protobuf:"varint,15,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchPolicy) Reset()         { *m = PatchPolicy{} }
func (m *PatchPolicy) String() string { return proto.CompactTextString(m) }
func (*PatchPolicy) ProtoMessage()    {}
func (*PatchPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{0}
}

func (m *PatchPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchPolicy.Unmarshal(m, b)
}
func (m *PatchPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchPolicy.Marshal(b, m, deterministic)
}
func (m *PatchPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchPolicy.Merge(m, src)
}
func (m *PatchPolicy) XXX_Size() int {
	return xxx_messageInfo_PatchPolicy.Size(m)
}
func (m *PatchPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_PatchPolicy proto.InternalMessageInfo

func (m *PatchPolicy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PatchPolicy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PatchPolicy) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *PatchPolicy) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *PatchPolicy) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *PatchPolicy) GetState() PatchPolicy_State {
	if m != nil {
		return m.State
	}
	return PatchPolicy_STATE_UNSPECIFIED
}

func (m *PatchPolicy) GetWindowsUpdate() *WindowsUpdateSettings {
	if m != nil {
		return m.WindowsUpdate
	}
	return nil
}

func (m *PatchPolicy) GetPatchWindow() *PatchWindow {
	if m != nil {
		return m.PatchWindow
	}
	return nil
}

func (m *PatchPolicy) GetRebootConfig() PatchPolicy_RebootConfig {
	if m != nil {
		return m.RebootConfig
	}
	return PatchPolicy_REBOOT_CONFIG_UNSPECIFIED
}

func (m *PatchPolicy) GetRetryStrategy() *RetryStrategy {
	if m != nil {
		return m.RetryStrategy
	}
	return nil
}

func (m *PatchPolicy) GetApt() *AptSettings {
	if m != nil {
		return m.Apt
	}
	return nil
}

func (m *PatchPolicy) GetYum() *YumSettings {
	if m != nil {
		return m.Yum
	}
	return nil
}

func (m *PatchPolicy) GetGoo() *GooSettings {
	if m != nil {
		return m.Goo
	}
	return nil
}

func (m *PatchPolicy) GetZypper() *ZypperSettings {
	if m != nil {
		return m.Zypper
	}
	return nil
}

func (m *PatchPolicy) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

// The strategy for retrying failed patches during the patch window.
type RetryStrategy struct {
	// If true, the agent will continue to try and patch until the window has
	// ended.
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryStrategy) Reset()         { *m = RetryStrategy{} }
func (m *RetryStrategy) String() string { return proto.CompactTextString(m) }
func (*RetryStrategy) ProtoMessage()    {}
func (*RetryStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{1}
}

func (m *RetryStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryStrategy.Unmarshal(m, b)
}
func (m *RetryStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryStrategy.Marshal(b, m, deterministic)
}
func (m *RetryStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryStrategy.Merge(m, src)
}
func (m *RetryStrategy) XXX_Size() int {
	return xxx_messageInfo_RetryStrategy.Size(m)
}
func (m *RetryStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_RetryStrategy proto.InternalMessageInfo

func (m *RetryStrategy) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// Specifies a recurring window of time. This window can recur daily, weekly, or
// monthly and must last for at least one hour.
type PatchWindow struct {
	// Time to start the maintenance operations.
	// It must include hours and minutes but not seconds or nanos.
	StartTime *timeofday.TimeOfDay `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Duration of the patch window. Must be at least 60 minutes and an
	// interval of 30 minutes.
	Duration *duration.Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// How often the patch window will reoccur.
	//
	// Types that are valid to be assigned to Frequency:
	//	*PatchWindow_Daily_
	//	*PatchWindow_Weekly_
	//	*PatchWindow_Monthly_
	//	*PatchWindow_RunOnce_
	Frequency            isPatchWindow_Frequency `protobuf_oneof:"frequency"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PatchWindow) Reset()         { *m = PatchWindow{} }
func (m *PatchWindow) String() string { return proto.CompactTextString(m) }
func (*PatchWindow) ProtoMessage()    {}
func (*PatchWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{2}
}

func (m *PatchWindow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchWindow.Unmarshal(m, b)
}
func (m *PatchWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchWindow.Marshal(b, m, deterministic)
}
func (m *PatchWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchWindow.Merge(m, src)
}
func (m *PatchWindow) XXX_Size() int {
	return xxx_messageInfo_PatchWindow.Size(m)
}
func (m *PatchWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchWindow.DiscardUnknown(m)
}

var xxx_messageInfo_PatchWindow proto.InternalMessageInfo

func (m *PatchWindow) GetStartTime() *timeofday.TimeOfDay {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *PatchWindow) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type isPatchWindow_Frequency interface {
	isPatchWindow_Frequency()
}

type PatchWindow_Daily_ struct {
	Daily *PatchWindow_Daily `protobuf:"bytes,3,opt,name=daily,proto3,oneof"`
}

type PatchWindow_Weekly_ struct {
	Weekly *PatchWindow_Weekly `protobuf:"bytes,4,opt,name=weekly,proto3,oneof"`
}

type PatchWindow_Monthly_ struct {
	Monthly *PatchWindow_Monthly `protobuf:"bytes,5,opt,name=monthly,proto3,oneof"`
}

type PatchWindow_RunOnce_ struct {
	RunOnce *PatchWindow_RunOnce `protobuf:"bytes,6,opt,name=run_once,json=runOnce,proto3,oneof"`
}

func (*PatchWindow_Daily_) isPatchWindow_Frequency() {}

func (*PatchWindow_Weekly_) isPatchWindow_Frequency() {}

func (*PatchWindow_Monthly_) isPatchWindow_Frequency() {}

func (*PatchWindow_RunOnce_) isPatchWindow_Frequency() {}

func (m *PatchWindow) GetFrequency() isPatchWindow_Frequency {
	if m != nil {
		return m.Frequency
	}
	return nil
}

func (m *PatchWindow) GetDaily() *PatchWindow_Daily {
	if x, ok := m.GetFrequency().(*PatchWindow_Daily_); ok {
		return x.Daily
	}
	return nil
}

func (m *PatchWindow) GetWeekly() *PatchWindow_Weekly {
	if x, ok := m.GetFrequency().(*PatchWindow_Weekly_); ok {
		return x.Weekly
	}
	return nil
}

func (m *PatchWindow) GetMonthly() *PatchWindow_Monthly {
	if x, ok := m.GetFrequency().(*PatchWindow_Monthly_); ok {
		return x.Monthly
	}
	return nil
}

func (m *PatchWindow) GetRunOnce() *PatchWindow_RunOnce {
	if x, ok := m.GetFrequency().(*PatchWindow_RunOnce_); ok {
		return x.RunOnce
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PatchWindow) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PatchWindow_OneofMarshaler, _PatchWindow_OneofUnmarshaler, _PatchWindow_OneofSizer, []interface{}{
		(*PatchWindow_Daily_)(nil),
		(*PatchWindow_Weekly_)(nil),
		(*PatchWindow_Monthly_)(nil),
		(*PatchWindow_RunOnce_)(nil),
	}
}

func _PatchWindow_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PatchWindow)
	// frequency
	switch x := m.Frequency.(type) {
	case *PatchWindow_Daily_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Daily); err != nil {
			return err
		}
	case *PatchWindow_Weekly_:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Weekly); err != nil {
			return err
		}
	case *PatchWindow_Monthly_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Monthly); err != nil {
			return err
		}
	case *PatchWindow_RunOnce_:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RunOnce); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PatchWindow.Frequency has unexpected type %T", x)
	}
	return nil
}

func _PatchWindow_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PatchWindow)
	switch tag {
	case 3: // frequency.daily
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PatchWindow_Daily)
		err := b.DecodeMessage(msg)
		m.Frequency = &PatchWindow_Daily_{msg}
		return true, err
	case 4: // frequency.weekly
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PatchWindow_Weekly)
		err := b.DecodeMessage(msg)
		m.Frequency = &PatchWindow_Weekly_{msg}
		return true, err
	case 5: // frequency.monthly
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PatchWindow_Monthly)
		err := b.DecodeMessage(msg)
		m.Frequency = &PatchWindow_Monthly_{msg}
		return true, err
	case 6: // frequency.run_once
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PatchWindow_RunOnce)
		err := b.DecodeMessage(msg)
		m.Frequency = &PatchWindow_RunOnce_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PatchWindow_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PatchWindow)
	// frequency
	switch x := m.Frequency.(type) {
	case *PatchWindow_Daily_:
		s := proto.Size(x.Daily)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PatchWindow_Weekly_:
		s := proto.Size(x.Weekly)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PatchWindow_Monthly_:
		s := proto.Size(x.Monthly)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PatchWindow_RunOnce_:
		s := proto.Size(x.RunOnce)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// The patch window should run daily.
type PatchWindow_Daily struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchWindow_Daily) Reset()         { *m = PatchWindow_Daily{} }
func (m *PatchWindow_Daily) String() string { return proto.CompactTextString(m) }
func (*PatchWindow_Daily) ProtoMessage()    {}
func (*PatchWindow_Daily) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{2, 0}
}

func (m *PatchWindow_Daily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchWindow_Daily.Unmarshal(m, b)
}
func (m *PatchWindow_Daily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchWindow_Daily.Marshal(b, m, deterministic)
}
func (m *PatchWindow_Daily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchWindow_Daily.Merge(m, src)
}
func (m *PatchWindow_Daily) XXX_Size() int {
	return xxx_messageInfo_PatchWindow_Daily.Size(m)
}
func (m *PatchWindow_Daily) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchWindow_Daily.DiscardUnknown(m)
}

var xxx_messageInfo_PatchWindow_Daily proto.InternalMessageInfo

// The patch window should run weekly.
type PatchWindow_Weekly struct {
	// Day of the week to run the patch. An unspecified days are invalid.
	Day                  dayofweek.DayOfWeek `protobuf:"varint,1,opt,name=day,proto3,enum=google.type.DayOfWeek" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PatchWindow_Weekly) Reset()         { *m = PatchWindow_Weekly{} }
func (m *PatchWindow_Weekly) String() string { return proto.CompactTextString(m) }
func (*PatchWindow_Weekly) ProtoMessage()    {}
func (*PatchWindow_Weekly) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{2, 1}
}

func (m *PatchWindow_Weekly) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchWindow_Weekly.Unmarshal(m, b)
}
func (m *PatchWindow_Weekly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchWindow_Weekly.Marshal(b, m, deterministic)
}
func (m *PatchWindow_Weekly) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchWindow_Weekly.Merge(m, src)
}
func (m *PatchWindow_Weekly) XXX_Size() int {
	return xxx_messageInfo_PatchWindow_Weekly.Size(m)
}
func (m *PatchWindow_Weekly) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchWindow_Weekly.DiscardUnknown(m)
}

var xxx_messageInfo_PatchWindow_Weekly proto.InternalMessageInfo

func (m *PatchWindow_Weekly) GetDay() dayofweek.DayOfWeek {
	if m != nil {
		return m.Day
	}
	return dayofweek.DayOfWeek_DAY_OF_WEEK_UNSPECIFIED
}

// The patch window should reoccur monthly.
type PatchWindow_Monthly struct {
	// Which day of the month to patch. This can either be a day of the week
	// in a month or a specific day in the month.
	//
	// Types that are valid to be assigned to Day:
	//	*PatchWindow_Monthly_OccurrenceOfDay_
	//	*PatchWindow_Monthly_DayOfMonth
	Day                  isPatchWindow_Monthly_Day `protobuf_oneof:"day"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PatchWindow_Monthly) Reset()         { *m = PatchWindow_Monthly{} }
func (m *PatchWindow_Monthly) String() string { return proto.CompactTextString(m) }
func (*PatchWindow_Monthly) ProtoMessage()    {}
func (*PatchWindow_Monthly) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{2, 2}
}

func (m *PatchWindow_Monthly) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchWindow_Monthly.Unmarshal(m, b)
}
func (m *PatchWindow_Monthly) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchWindow_Monthly.Marshal(b, m, deterministic)
}
func (m *PatchWindow_Monthly) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchWindow_Monthly.Merge(m, src)
}
func (m *PatchWindow_Monthly) XXX_Size() int {
	return xxx_messageInfo_PatchWindow_Monthly.Size(m)
}
func (m *PatchWindow_Monthly) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchWindow_Monthly.DiscardUnknown(m)
}

var xxx_messageInfo_PatchWindow_Monthly proto.InternalMessageInfo

type isPatchWindow_Monthly_Day interface {
	isPatchWindow_Monthly_Day()
}

type PatchWindow_Monthly_OccurrenceOfDay_ struct {
	OccurrenceOfDay *PatchWindow_Monthly_OccurrenceOfDay `protobuf:"bytes,1,opt,name=occurrence_of_day,json=occurrenceOfDay,proto3,oneof"`
}

type PatchWindow_Monthly_DayOfMonth struct {
	DayOfMonth int32 `protobuf:"varint,2,opt,name=day_of_month,json=dayOfMonth,proto3,oneof"`
}

func (*PatchWindow_Monthly_OccurrenceOfDay_) isPatchWindow_Monthly_Day() {}

func (*PatchWindow_Monthly_DayOfMonth) isPatchWindow_Monthly_Day() {}

func (m *PatchWindow_Monthly) GetDay() isPatchWindow_Monthly_Day {
	if m != nil {
		return m.Day
	}
	return nil
}

func (m *PatchWindow_Monthly) GetOccurrenceOfDay() *PatchWindow_Monthly_OccurrenceOfDay {
	if x, ok := m.GetDay().(*PatchWindow_Monthly_OccurrenceOfDay_); ok {
		return x.OccurrenceOfDay
	}
	return nil
}

func (m *PatchWindow_Monthly) GetDayOfMonth() int32 {
	if x, ok := m.GetDay().(*PatchWindow_Monthly_DayOfMonth); ok {
		return x.DayOfMonth
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PatchWindow_Monthly) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PatchWindow_Monthly_OneofMarshaler, _PatchWindow_Monthly_OneofUnmarshaler, _PatchWindow_Monthly_OneofSizer, []interface{}{
		(*PatchWindow_Monthly_OccurrenceOfDay_)(nil),
		(*PatchWindow_Monthly_DayOfMonth)(nil),
	}
}

func _PatchWindow_Monthly_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PatchWindow_Monthly)
	// day
	switch x := m.Day.(type) {
	case *PatchWindow_Monthly_OccurrenceOfDay_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OccurrenceOfDay); err != nil {
			return err
		}
	case *PatchWindow_Monthly_DayOfMonth:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.DayOfMonth))
	case nil:
	default:
		return fmt.Errorf("PatchWindow_Monthly.Day has unexpected type %T", x)
	}
	return nil
}

func _PatchWindow_Monthly_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PatchWindow_Monthly)
	switch tag {
	case 1: // day.occurrence_of_day
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PatchWindow_Monthly_OccurrenceOfDay)
		err := b.DecodeMessage(msg)
		m.Day = &PatchWindow_Monthly_OccurrenceOfDay_{msg}
		return true, err
	case 2: // day.day_of_month
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Day = &PatchWindow_Monthly_DayOfMonth{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _PatchWindow_Monthly_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PatchWindow_Monthly)
	// day
	switch x := m.Day.(type) {
	case *PatchWindow_Monthly_OccurrenceOfDay_:
		s := proto.Size(x.OccurrenceOfDay)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PatchWindow_Monthly_DayOfMonth:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.DayOfMonth))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Represents a day of the week in a month such as the
// third monday of the month.
type PatchWindow_Monthly_OccurrenceOfDay struct {
	// Day of the week to run the patch.
	Day dayofweek.DayOfWeek `protobuf:"varint,1,opt,name=day,proto3,enum=google.type.DayOfWeek" json:"day,omitempty"`
	// Occurrence within the month. Valid values are -1 and from 1 to 4
	// inclusive. Use -1 to signify that this should be the "last" occurrence
	// of this day in the month.
	Occurrence           int32    `protobuf:"varint,2,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchWindow_Monthly_OccurrenceOfDay) Reset()         { *m = PatchWindow_Monthly_OccurrenceOfDay{} }
func (m *PatchWindow_Monthly_OccurrenceOfDay) String() string { return proto.CompactTextString(m) }
func (*PatchWindow_Monthly_OccurrenceOfDay) ProtoMessage()    {}
func (*PatchWindow_Monthly_OccurrenceOfDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{2, 2, 0}
}

func (m *PatchWindow_Monthly_OccurrenceOfDay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchWindow_Monthly_OccurrenceOfDay.Unmarshal(m, b)
}
func (m *PatchWindow_Monthly_OccurrenceOfDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchWindow_Monthly_OccurrenceOfDay.Marshal(b, m, deterministic)
}
func (m *PatchWindow_Monthly_OccurrenceOfDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchWindow_Monthly_OccurrenceOfDay.Merge(m, src)
}
func (m *PatchWindow_Monthly_OccurrenceOfDay) XXX_Size() int {
	return xxx_messageInfo_PatchWindow_Monthly_OccurrenceOfDay.Size(m)
}
func (m *PatchWindow_Monthly_OccurrenceOfDay) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchWindow_Monthly_OccurrenceOfDay.DiscardUnknown(m)
}

var xxx_messageInfo_PatchWindow_Monthly_OccurrenceOfDay proto.InternalMessageInfo

func (m *PatchWindow_Monthly_OccurrenceOfDay) GetDay() dayofweek.DayOfWeek {
	if m != nil {
		return m.Day
	}
	return dayofweek.DayOfWeek_DAY_OF_WEEK_UNSPECIFIED
}

func (m *PatchWindow_Monthly_OccurrenceOfDay) GetOccurrence() int32 {
	if m != nil {
		return m.Occurrence
	}
	return 0
}

// The patch window will not reoccur. The patch window will only start on the
// date specified.
type PatchWindow_RunOnce struct {
	// The date when the patch window starts.
	Date                 *date.Date `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PatchWindow_RunOnce) Reset()         { *m = PatchWindow_RunOnce{} }
func (m *PatchWindow_RunOnce) String() string { return proto.CompactTextString(m) }
func (*PatchWindow_RunOnce) ProtoMessage()    {}
func (*PatchWindow_RunOnce) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{2, 3}
}

func (m *PatchWindow_RunOnce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchWindow_RunOnce.Unmarshal(m, b)
}
func (m *PatchWindow_RunOnce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchWindow_RunOnce.Marshal(b, m, deterministic)
}
func (m *PatchWindow_RunOnce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchWindow_RunOnce.Merge(m, src)
}
func (m *PatchWindow_RunOnce) XXX_Size() int {
	return xxx_messageInfo_PatchWindow_RunOnce.Size(m)
}
func (m *PatchWindow_RunOnce) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchWindow_RunOnce.DiscardUnknown(m)
}

var xxx_messageInfo_PatchWindow_RunOnce proto.InternalMessageInfo

func (m *PatchWindow_RunOnce) GetDate() *date.Date {
	if m != nil {
		return m.Date
	}
	return nil
}

// Apt patching will be performed by executing `apt-get update && apt-get
// upgrade`. Additional options can be set to control how this is executed.
type AptSettings struct {
	// Optional. By changing the type to DIST, the patching will be performed
	// using `apt-get dist-upgrade` instead.
	Type                 AptSettings_Type `protobuf:"varint,1,opt,name=type,proto3,enum=google.cloud.osconfig.v1alpha1.AptSettings_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AptSettings) Reset()         { *m = AptSettings{} }
func (m *AptSettings) String() string { return proto.CompactTextString(m) }
func (*AptSettings) ProtoMessage()    {}
func (*AptSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{3}
}

func (m *AptSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AptSettings.Unmarshal(m, b)
}
func (m *AptSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AptSettings.Marshal(b, m, deterministic)
}
func (m *AptSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AptSettings.Merge(m, src)
}
func (m *AptSettings) XXX_Size() int {
	return xxx_messageInfo_AptSettings.Size(m)
}
func (m *AptSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_AptSettings.DiscardUnknown(m)
}

var xxx_messageInfo_AptSettings proto.InternalMessageInfo

func (m *AptSettings) GetType() AptSettings_Type {
	if m != nil {
		return m.Type
	}
	return AptSettings_TYPE_UNSPECIFIED
}

// Yum patching will be performed by executing `yum update`. Additional options
// can be set to control how this is executed.
//
// Note that not all settings are supported on all platforms.
type YumSettings struct {
	// Optional. Adds the `--security` flag to `yum update`. Not supported on
	// all platforms.
	Security bool `protobuf:"varint,1,opt,name=security,proto3" json:"security,omitempty"`
	// Optional. Will cause patch to run `yum update-minimal` instead.
	Minimal bool `protobuf:"varint,2,opt,name=minimal,proto3" json:"minimal,omitempty"`
	// List of packages to exclude from update. These packages will be excluded by
	// using the yum `--exclude` flag.
	Excludes             []string `protobuf:"bytes,3,rep,name=excludes,proto3" json:"excludes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YumSettings) Reset()         { *m = YumSettings{} }
func (m *YumSettings) String() string { return proto.CompactTextString(m) }
func (*YumSettings) ProtoMessage()    {}
func (*YumSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{4}
}

func (m *YumSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YumSettings.Unmarshal(m, b)
}
func (m *YumSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YumSettings.Marshal(b, m, deterministic)
}
func (m *YumSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YumSettings.Merge(m, src)
}
func (m *YumSettings) XXX_Size() int {
	return xxx_messageInfo_YumSettings.Size(m)
}
func (m *YumSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_YumSettings.DiscardUnknown(m)
}

var xxx_messageInfo_YumSettings proto.InternalMessageInfo

func (m *YumSettings) GetSecurity() bool {
	if m != nil {
		return m.Security
	}
	return false
}

func (m *YumSettings) GetMinimal() bool {
	if m != nil {
		return m.Minimal
	}
	return false
}

func (m *YumSettings) GetExcludes() []string {
	if m != nil {
		return m.Excludes
	}
	return nil
}

// Googet patching is performed by running `googet update`.
type GooSettings struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GooSettings) Reset()         { *m = GooSettings{} }
func (m *GooSettings) String() string { return proto.CompactTextString(m) }
func (*GooSettings) ProtoMessage()    {}
func (*GooSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{5}
}

func (m *GooSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GooSettings.Unmarshal(m, b)
}
func (m *GooSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GooSettings.Marshal(b, m, deterministic)
}
func (m *GooSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GooSettings.Merge(m, src)
}
func (m *GooSettings) XXX_Size() int {
	return xxx_messageInfo_GooSettings.Size(m)
}
func (m *GooSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_GooSettings.DiscardUnknown(m)
}

var xxx_messageInfo_GooSettings proto.InternalMessageInfo

// Zypper patching is performed by running `zypper refresh && zypper update`
type ZypperSettings struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZypperSettings) Reset()         { *m = ZypperSettings{} }
func (m *ZypperSettings) String() string { return proto.CompactTextString(m) }
func (*ZypperSettings) ProtoMessage()    {}
func (*ZypperSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{6}
}

func (m *ZypperSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZypperSettings.Unmarshal(m, b)
}
func (m *ZypperSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZypperSettings.Marshal(b, m, deterministic)
}
func (m *ZypperSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZypperSettings.Merge(m, src)
}
func (m *ZypperSettings) XXX_Size() int {
	return xxx_messageInfo_ZypperSettings.Size(m)
}
func (m *ZypperSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_ZypperSettings.DiscardUnknown(m)
}

var xxx_messageInfo_ZypperSettings proto.InternalMessageInfo

// Windows patching is performed using the Windows Update Agent.
type WindowsUpdateSettings struct {
	// Only apply updates of these windows update classifications. If empty, all
	// updates will be applied.
	Classifications []WindowsUpdateSettings_Classification `protobuf:"varint,1,rep,packed,name=classifications,proto3,enum=google.cloud.osconfig.v1alpha1.WindowsUpdateSettings_Classification" json:"classifications,omitempty"`
	// Optional list of KBs to exclude from update.
	Excludes             []string `protobuf:"bytes,2,rep,name=excludes,proto3" json:"excludes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindowsUpdateSettings) Reset()         { *m = WindowsUpdateSettings{} }
func (m *WindowsUpdateSettings) String() string { return proto.CompactTextString(m) }
func (*WindowsUpdateSettings) ProtoMessage()    {}
func (*WindowsUpdateSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{7}
}

func (m *WindowsUpdateSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowsUpdateSettings.Unmarshal(m, b)
}
func (m *WindowsUpdateSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowsUpdateSettings.Marshal(b, m, deterministic)
}
func (m *WindowsUpdateSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowsUpdateSettings.Merge(m, src)
}
func (m *WindowsUpdateSettings) XXX_Size() int {
	return xxx_messageInfo_WindowsUpdateSettings.Size(m)
}
func (m *WindowsUpdateSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowsUpdateSettings.DiscardUnknown(m)
}

var xxx_messageInfo_WindowsUpdateSettings proto.InternalMessageInfo

func (m *WindowsUpdateSettings) GetClassifications() []WindowsUpdateSettings_Classification {
	if m != nil {
		return m.Classifications
	}
	return nil
}

func (m *WindowsUpdateSettings) GetExcludes() []string {
	if m != nil {
		return m.Excludes
	}
	return nil
}

// A request message for creating a PatchPolicy.
type CreatePatchPolicyRequest struct {
	// The resource name of the parent.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The PatchPolicy to create.
	PatchPolicy          *PatchPolicy `protobuf:"bytes,2,opt,name=patch_policy,json=patchPolicy,proto3" json:"patch_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreatePatchPolicyRequest) Reset()         { *m = CreatePatchPolicyRequest{} }
func (m *CreatePatchPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePatchPolicyRequest) ProtoMessage()    {}
func (*CreatePatchPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{8}
}

func (m *CreatePatchPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePatchPolicyRequest.Unmarshal(m, b)
}
func (m *CreatePatchPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePatchPolicyRequest.Marshal(b, m, deterministic)
}
func (m *CreatePatchPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePatchPolicyRequest.Merge(m, src)
}
func (m *CreatePatchPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePatchPolicyRequest.Size(m)
}
func (m *CreatePatchPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePatchPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePatchPolicyRequest proto.InternalMessageInfo

func (m *CreatePatchPolicyRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreatePatchPolicyRequest) GetPatchPolicy() *PatchPolicy {
	if m != nil {
		return m.PatchPolicy
	}
	return nil
}

// A request message for retrieving a PatchPolicy.
type GetPatchPolicyRequest struct {
	// The resource name of the PatchPolicy.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional patch_version to get a specific version of the PatchPolicy. If
	// omitted, it returns the latest version.
	PatchVersion         int64    `protobuf:"varint,2,opt,name=patch_version,json=patchVersion,proto3" json:"patch_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPatchPolicyRequest) Reset()         { *m = GetPatchPolicyRequest{} }
func (m *GetPatchPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*GetPatchPolicyRequest) ProtoMessage()    {}
func (*GetPatchPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{9}
}

func (m *GetPatchPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPatchPolicyRequest.Unmarshal(m, b)
}
func (m *GetPatchPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPatchPolicyRequest.Marshal(b, m, deterministic)
}
func (m *GetPatchPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPatchPolicyRequest.Merge(m, src)
}
func (m *GetPatchPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_GetPatchPolicyRequest.Size(m)
}
func (m *GetPatchPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPatchPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPatchPolicyRequest proto.InternalMessageInfo

func (m *GetPatchPolicyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPatchPolicyRequest) GetPatchVersion() int64 {
	if m != nil {
		return m.PatchVersion
	}
	return 0
}

// A request message for listing PatchPolicy.
type ListPatchPoliciesRequest struct {
	// The resource name of the parent.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The maximum number of PatchPolicies to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A pagination token returned from a previous call to ListPatchPolicies
	// that indicates where this listing should continue from.
	// This field is optional.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPatchPoliciesRequest) Reset()         { *m = ListPatchPoliciesRequest{} }
func (m *ListPatchPoliciesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPatchPoliciesRequest) ProtoMessage()    {}
func (*ListPatchPoliciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{10}
}

func (m *ListPatchPoliciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPatchPoliciesRequest.Unmarshal(m, b)
}
func (m *ListPatchPoliciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPatchPoliciesRequest.Marshal(b, m, deterministic)
}
func (m *ListPatchPoliciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPatchPoliciesRequest.Merge(m, src)
}
func (m *ListPatchPoliciesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPatchPoliciesRequest.Size(m)
}
func (m *ListPatchPoliciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPatchPoliciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPatchPoliciesRequest proto.InternalMessageInfo

func (m *ListPatchPoliciesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListPatchPoliciesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPatchPoliciesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

// A response message for listing PatchPolicies.
type ListPatchPoliciesResponse struct {
	// The list of PatchPolicies.
	PatchPolicies []*PatchPolicy `protobuf:"bytes,1,rep,name=patch_policies,json=patchPolicies,proto3" json:"patch_policies,omitempty"`
	// A pagination token that can be used to get the next page
	// of PatchPolicies.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPatchPoliciesResponse) Reset()         { *m = ListPatchPoliciesResponse{} }
func (m *ListPatchPoliciesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPatchPoliciesResponse) ProtoMessage()    {}
func (*ListPatchPoliciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{11}
}

func (m *ListPatchPoliciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPatchPoliciesResponse.Unmarshal(m, b)
}
func (m *ListPatchPoliciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPatchPoliciesResponse.Marshal(b, m, deterministic)
}
func (m *ListPatchPoliciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPatchPoliciesResponse.Merge(m, src)
}
func (m *ListPatchPoliciesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPatchPoliciesResponse.Size(m)
}
func (m *ListPatchPoliciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPatchPoliciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPatchPoliciesResponse proto.InternalMessageInfo

func (m *ListPatchPoliciesResponse) GetPatchPolicies() []*PatchPolicy {
	if m != nil {
		return m.PatchPolicies
	}
	return nil
}

func (m *ListPatchPoliciesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// A request message for updating a PatchPolicy.
type UpdatePatchPolicyRequest struct {
	// The resource name of the PatchPolicy.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The updated PatchPolicy.
	PatchPolicy *PatchPolicy `protobuf:"bytes,2,opt,name=patch_policy,json=patchPolicy,proto3" json:"patch_policy,omitempty"`
	// Field mask that controls which fields of the PatchPolicy should be updated.
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdatePatchPolicyRequest) Reset()         { *m = UpdatePatchPolicyRequest{} }
func (m *UpdatePatchPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePatchPolicyRequest) ProtoMessage()    {}
func (*UpdatePatchPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{12}
}

func (m *UpdatePatchPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePatchPolicyRequest.Unmarshal(m, b)
}
func (m *UpdatePatchPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePatchPolicyRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePatchPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePatchPolicyRequest.Merge(m, src)
}
func (m *UpdatePatchPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePatchPolicyRequest.Size(m)
}
func (m *UpdatePatchPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePatchPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePatchPolicyRequest proto.InternalMessageInfo

func (m *UpdatePatchPolicyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePatchPolicyRequest) GetPatchPolicy() *PatchPolicy {
	if m != nil {
		return m.PatchPolicy
	}
	return nil
}

func (m *UpdatePatchPolicyRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

// A request message for deleting a PatchPolicy.
type DeletePatchPolicyRequest struct {
	// The resource name of the PatchPolicy.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePatchPolicyRequest) Reset()         { *m = DeletePatchPolicyRequest{} }
func (m *DeletePatchPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePatchPolicyRequest) ProtoMessage()    {}
func (*DeletePatchPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f33c49af1d47de3, []int{13}
}

func (m *DeletePatchPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePatchPolicyRequest.Unmarshal(m, b)
}
func (m *DeletePatchPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePatchPolicyRequest.Marshal(b, m, deterministic)
}
func (m *DeletePatchPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePatchPolicyRequest.Merge(m, src)
}
func (m *DeletePatchPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePatchPolicyRequest.Size(m)
}
func (m *DeletePatchPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePatchPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePatchPolicyRequest proto.InternalMessageInfo

func (m *DeletePatchPolicyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.PatchPolicy_State", PatchPolicy_State_name, PatchPolicy_State_value)
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.PatchPolicy_RebootConfig", PatchPolicy_RebootConfig_name, PatchPolicy_RebootConfig_value)
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.AptSettings_Type", AptSettings_Type_name, AptSettings_Type_value)
	proto.RegisterEnum("google.cloud.osconfig.v1alpha1.WindowsUpdateSettings_Classification", WindowsUpdateSettings_Classification_name, WindowsUpdateSettings_Classification_value)
	proto.RegisterType((*PatchPolicy)(nil), "google.cloud.osconfig.v1alpha1.PatchPolicy")
	proto.RegisterMapType((map[string]string)(nil), "google.cloud.osconfig.v1alpha1.PatchPolicy.LabelsEntry")
	proto.RegisterType((*RetryStrategy)(nil), "google.cloud.osconfig.v1alpha1.RetryStrategy")
	proto.RegisterType((*PatchWindow)(nil), "google.cloud.osconfig.v1alpha1.PatchWindow")
	proto.RegisterType((*PatchWindow_Daily)(nil), "google.cloud.osconfig.v1alpha1.PatchWindow.Daily")
	proto.RegisterType((*PatchWindow_Weekly)(nil), "google.cloud.osconfig.v1alpha1.PatchWindow.Weekly")
	proto.RegisterType((*PatchWindow_Monthly)(nil), "google.cloud.osconfig.v1alpha1.PatchWindow.Monthly")
	proto.RegisterType((*PatchWindow_Monthly_OccurrenceOfDay)(nil), "google.cloud.osconfig.v1alpha1.PatchWindow.Monthly.OccurrenceOfDay")
	proto.RegisterType((*PatchWindow_RunOnce)(nil), "google.cloud.osconfig.v1alpha1.PatchWindow.RunOnce")
	proto.RegisterType((*AptSettings)(nil), "google.cloud.osconfig.v1alpha1.AptSettings")
	proto.RegisterType((*YumSettings)(nil), "google.cloud.osconfig.v1alpha1.YumSettings")
	proto.RegisterType((*GooSettings)(nil), "google.cloud.osconfig.v1alpha1.GooSettings")
	proto.RegisterType((*ZypperSettings)(nil), "google.cloud.osconfig.v1alpha1.ZypperSettings")
	proto.RegisterType((*WindowsUpdateSettings)(nil), "google.cloud.osconfig.v1alpha1.WindowsUpdateSettings")
	proto.RegisterType((*CreatePatchPolicyRequest)(nil), "google.cloud.osconfig.v1alpha1.CreatePatchPolicyRequest")
	proto.RegisterType((*GetPatchPolicyRequest)(nil), "google.cloud.osconfig.v1alpha1.GetPatchPolicyRequest")
	proto.RegisterType((*ListPatchPoliciesRequest)(nil), "google.cloud.osconfig.v1alpha1.ListPatchPoliciesRequest")
	proto.RegisterType((*ListPatchPoliciesResponse)(nil), "google.cloud.osconfig.v1alpha1.ListPatchPoliciesResponse")
	proto.RegisterType((*UpdatePatchPolicyRequest)(nil), "google.cloud.osconfig.v1alpha1.UpdatePatchPolicyRequest")
	proto.RegisterType((*DeletePatchPolicyRequest)(nil), "google.cloud.osconfig.v1alpha1.DeletePatchPolicyRequest")
}

func init() {
	proto.RegisterFile("google/cloud/osconfig/v1alpha1/patch_policies.proto", fileDescriptor_5f33c49af1d47de3)
}

var fileDescriptor_5f33c49af1d47de3 = []byte{
	// 1457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0xb5, 0x24, 0xeb, 0x36, 0xba, 0x98, 0x5e, 0x24, 0x01, 0xa3, 0x20, 0xa9, 0xc0, 0xa2, 0x81,
	0x8a, 0xa0, 0x54, 0xac, 0x20, 0x68, 0xda, 0xa0, 0x0f, 0xb2, 0x2e, 0x36, 0x51, 0xc5, 0x52, 0x57,
	0xb4, 0x03, 0xa7, 0x2d, 0x04, 0x9a, 0x5a, 0x29, 0x84, 0x29, 0x2e, 0x43, 0x52, 0x71, 0x98, 0xbc,
	0x15, 0xfd, 0x87, 0x3e, 0xf7, 0x23, 0xfa, 0xd2, 0x7e, 0x4a, 0x7f, 0xa6, 0xd8, 0x5d, 0x4a, 0xa6,
	0x54, 0xa7, 0xb6, 0x82, 0xbe, 0x71, 0x66, 0xe7, 0x1c, 0xce, 0x0c, 0x67, 0xcf, 0x2e, 0xe1, 0xc9,
	0x94, 0xd2, 0xa9, 0x4d, 0xea, 0xa6, 0x4d, 0xe7, 0xe3, 0x3a, 0xf5, 0x4d, 0xea, 0x4c, 0xac, 0x69,
	0xfd, 0xed, 0x9e, 0x61, 0xbb, 0xaf, 0x8d, 0xbd, 0xba, 0x6b, 0x04, 0xe6, 0xeb, 0x91, 0x4b, 0x6d,
	0xcb, 0xb4, 0x88, 0xaf, 0xba, 0x1e, 0x0d, 0x28, 0x7a, 0x20, 0x40, 0x2a, 0x07, 0xa9, 0x0b, 0x90,
	0xba, 0x00, 0x55, 0xa2, 0xf5, 0x3a, 0x8f, 0x3e, 0x9b, 0x4f, 0xea, 0xe3, 0xb9, 0x67, 0x04, 0x16,
	0x75, 0x04, 0xbe, 0x52, 0x5d, 0x5f, 0x9f, 0x58, 0xc4, 0x1e, 0x8f, 0x66, 0x86, 0x7f, 0x1e, 0x45,
	0x7c, 0xb6, 0x1e, 0x11, 0x58, 0x33, 0xe2, 0x07, 0xc6, 0xcc, 0x8d, 0x02, 0xee, 0x44, 0x01, 0x41,
	0xe8, 0x92, 0xfa, 0xd8, 0x08, 0x48, 0xe4, 0xbf, 0xb7, 0xea, 0x0f, 0xe9, 0xe4, 0x82, 0x90, 0xf3,
	0xab, 0x16, 0x19, 0x23, 0x9d, 0x8c, 0x8d, 0x50, 0x2c, 0x2a, 0xbf, 0xe7, 0xa1, 0x30, 0x60, 0xd5,
	0x0e, 0x58, 0xb1, 0x21, 0x42, 0xb0, 0xed, 0x18, 0x33, 0x22, 0x27, 0xaa, 0x89, 0x5a, 0x1e, 0xf3,
	0x67, 0x54, 0x85, 0xc2, 0x98, 0xf8, 0xa6, 0x67, 0xb9, 0xac, 0x1a, 0x39, 0xc9, 0x97, 0xe2, 0x2e,
	0xf4, 0x1c, 0x0a, 0xa6, 0x47, 0x8c, 0x80, 0x8c, 0x18, 0xbf, 0x9c, 0xaa, 0x26, 0x6a, 0x85, 0x46,
	0x45, 0x8d, 0x1a, 0xb6, 0x28, 0x47, 0xd5, 0x17, 0xe5, 0x60, 0x10, 0xe1, 0xcc, 0xc1, 0xc0, 0x73,
	0x77, 0xbc, 0x04, 0x6f, 0x5f, 0x0f, 0x16, 0xe1, 0x1c, 0xdc, 0x87, 0x8c, 0x6d, 0x9c, 0x11, 0xdb,
	0x97, 0xd3, 0xd5, 0x54, 0xad, 0xd0, 0xf8, 0x5a, 0xfd, 0xef, 0xaf, 0xa4, 0xc6, 0x8a, 0x55, 0x7b,
	0x1c, 0xd9, 0x71, 0x02, 0x2f, 0xc4, 0x11, 0x0d, 0x3a, 0x80, 0xb4, 0x1f, 0x18, 0x01, 0x91, 0x33,
	0xd5, 0x44, 0xad, 0xdc, 0xd8, 0xdb, 0x84, 0x6f, 0xc8, 0x80, 0x58, 0xe0, 0xd1, 0x4f, 0x50, 0xbe,
	0xb0, 0x9c, 0x31, 0xbd, 0xf0, 0x47, 0x22, 0x5f, 0x39, 0xcb, 0x2b, 0x7b, 0x7a, 0x1d, 0xe3, 0x4b,
	0x81, 0x3a, 0xe6, 0xa0, 0x21, 0x09, 0x02, 0xcb, 0x99, 0xfa, 0xb8, 0x74, 0x11, 0x77, 0xa3, 0x23,
	0x28, 0x8a, 0x21, 0x15, 0x6e, 0x39, 0xc7, 0xb9, 0x1f, 0xdd, 0x28, 0x5b, 0xf1, 0x02, 0x5c, 0x70,
	0x2f, 0x0d, 0xf4, 0x33, 0x94, 0x3c, 0x72, 0x46, 0x69, 0x30, 0x12, 0x10, 0x39, 0xcf, 0xcb, 0x7f,
	0xb6, 0x49, 0xf9, 0x98, 0x13, 0xb4, 0x78, 0x04, 0x2e, 0x7a, 0x31, 0x0b, 0xe9, 0x50, 0xf6, 0x48,
	0xe0, 0x85, 0x23, 0x3f, 0xf0, 0x8c, 0x80, 0x4c, 0x43, 0x19, 0x78, 0xc2, 0x5f, 0x5d, 0xc7, 0x8f,
	0x19, 0x6a, 0x18, 0x81, 0x70, 0xc9, 0x8b, 0x9b, 0xe8, 0x3b, 0x48, 0x19, 0x6e, 0x20, 0x17, 0x6e,
	0x56, 0x7b, 0xd3, 0x0d, 0x96, 0xdd, 0x64, 0x38, 0x06, 0x0f, 0xe7, 0x33, 0xb9, 0x78, 0x33, 0xf8,
	0xe9, 0x7c, 0x76, 0x09, 0x0f, 0xe7, 0x33, 0x06, 0x9f, 0x52, 0x2a, 0x97, 0x6e, 0x06, 0x3f, 0xa0,
	0xf4, 0x12, 0x3e, 0xa5, 0x14, 0x75, 0x21, 0xf3, 0x3e, 0x74, 0x5d, 0xe2, 0xc9, 0x65, 0xce, 0xa0,
	0x5e, 0xc7, 0xf0, 0x8a, 0x47, 0x2f, 0x49, 0x22, 0x34, 0x92, 0x21, 0xfb, 0x96, 0x78, 0x3e, 0xdb,
	0x99, 0x3b, 0xd5, 0x44, 0x2d, 0x85, 0x17, 0x66, 0xe5, 0x1b, 0x28, 0xc4, 0x26, 0x1c, 0x49, 0x90,
	0x3a, 0x27, 0x61, 0xb4, 0xb3, 0xd9, 0x23, 0xba, 0x05, 0xe9, 0xb7, 0x86, 0x3d, 0x27, 0xd1, 0x96,
	0x16, 0xc6, 0xb7, 0xc9, 0x67, 0x09, 0xe5, 0x19, 0xa4, 0xf9, 0x30, 0xa3, 0xdb, 0xb0, 0x3b, 0xd4,
	0x9b, 0x7a, 0x67, 0x74, 0x7c, 0x34, 0x1c, 0x74, 0x5a, 0x5a, 0x57, 0xeb, 0xb4, 0xa5, 0x2d, 0x04,
	0x90, 0x69, 0xb6, 0x74, 0xed, 0xa4, 0x23, 0x25, 0x50, 0x11, 0x72, 0xda, 0x51, 0x64, 0x25, 0x95,
	0x1f, 0xa0, 0x18, 0x9f, 0x03, 0x74, 0x1f, 0xee, 0xe2, 0xce, 0x7e, 0xbf, 0xaf, 0x8f, 0x5a, 0xfd,
	0xa3, 0xae, 0x76, 0xb0, 0x46, 0x54, 0x80, 0x6c, 0xbb, 0xd3, 0x6d, 0x1e, 0xf7, 0x74, 0x29, 0xc1,
	0x59, 0x7b, 0x2f, 0x9b, 0xa7, 0x43, 0x29, 0x89, 0xf2, 0x90, 0x3e, 0xea, 0x9c, 0x74, 0xb0, 0x94,
	0x52, 0xbe, 0x84, 0xd2, 0xca, 0x18, 0xb0, 0x92, 0x89, 0x63, 0x9c, 0xd9, 0x64, 0xcc, 0xab, 0xc9,
	0xe1, 0x85, 0xa9, 0xfc, 0x99, 0x89, 0xe4, 0x2c, 0x1a, 0xeb, 0xa7, 0x00, 0x7e, 0x60, 0x78, 0x81,
	0x90, 0x96, 0x04, 0x6f, 0xf4, 0x9d, 0x45, 0xa3, 0x99, 0x20, 0x72, 0x59, 0xe9, 0x4f, 0xda, 0x46,
	0x88, 0xf3, 0x3c, 0x92, 0xab, 0xca, 0x53, 0xc8, 0x2d, 0xc4, 0x9b, 0xf7, 0xa6, 0xd0, 0xb8, 0xfb,
	0x2f, 0x3d, 0x6a, 0x47, 0x01, 0x78, 0x19, 0x8a, 0x34, 0x48, 0x8f, 0x0d, 0xcb, 0x0e, 0x23, 0x01,
	0xdc, 0xdb, 0x60, 0x37, 0xaa, 0x6d, 0x06, 0x3c, 0xdc, 0xc2, 0x82, 0x01, 0xf5, 0x20, 0xc3, 0x24,
	0xdc, 0x0e, 0x23, 0x3d, 0x6c, 0x6c, 0xc2, 0xf5, 0x92, 0x23, 0x0f, 0xb7, 0x70, 0xc4, 0x81, 0xfa,
	0x90, 0x9d, 0x51, 0x27, 0x78, 0x6d, 0x87, 0x72, 0x9a, 0xd3, 0x3d, 0xd9, 0x84, 0xee, 0x85, 0x80,
	0x1e, 0x6e, 0xe1, 0x05, 0x0b, 0x1a, 0x40, 0xce, 0x9b, 0x3b, 0x23, 0xea, 0x98, 0x42, 0x28, 0x37,
	0x64, 0xc4, 0x73, 0xa7, 0xef, 0x98, 0x84, 0x31, 0x7a, 0xe2, 0xb1, 0x92, 0x85, 0x34, 0x6f, 0x41,
	0xa5, 0x01, 0x19, 0x91, 0x3f, 0xaa, 0x41, 0x6a, 0x6c, 0x88, 0x81, 0x2d, 0xaf, 0x7d, 0xb5, 0xb6,
	0x11, 0xf6, 0x27, 0x2c, 0x0c, 0xb3, 0x90, 0xca, 0xaf, 0x49, 0xc8, 0x46, 0x59, 0xa2, 0x37, 0xb0,
	0x4b, 0x4d, 0x73, 0xee, 0x79, 0xc4, 0x31, 0xc9, 0x88, 0x4e, 0x46, 0x0b, 0x8e, 0x42, 0xa3, 0xf5,
	0x09, 0x55, 0xab, 0xfd, 0x25, 0x19, 0x1f, 0x93, 0xc3, 0x2d, 0xbc, 0x43, 0x57, 0x5d, 0x48, 0x81,
	0xe2, 0xd8, 0x08, 0xd9, 0xbb, 0x78, 0x7f, 0xf8, 0xc8, 0xa4, 0x0f, 0xb7, 0x30, 0x8c, 0x59, 0x9a,
	0x9c, 0xa8, 0xf2, 0x23, 0xec, 0xac, 0x31, 0xdd, 0xbc, 0x3e, 0xf4, 0x00, 0xe0, 0xf2, 0x9d, 0x82,
	0x1e, 0xc7, 0x3c, 0xfb, 0x69, 0xce, 0x54, 0x79, 0x0c, 0xd9, 0xa8, 0xb3, 0xe8, 0x0b, 0xd8, 0xe6,
	0x67, 0x8e, 0x28, 0x7c, 0x77, 0x8d, 0x3c, 0x20, 0x98, 0x2f, 0xef, 0x17, 0x20, 0x3f, 0xf1, 0xc8,
	0x9b, 0x39, 0x71, 0xcc, 0x50, 0xf9, 0x00, 0x85, 0x98, 0x46, 0xa2, 0x36, 0x6c, 0xb3, 0xf0, 0x28,
	0xbf, 0xc7, 0x1b, 0xc8, 0xab, 0xaa, 0x87, 0x2e, 0xc1, 0x1c, 0xad, 0x3c, 0x84, 0x6d, 0x66, 0xa1,
	0x5b, 0x20, 0xe9, 0xa7, 0x83, 0x75, 0x1d, 0xc9, 0xc1, 0x76, 0x5b, 0x1b, 0xea, 0x52, 0x42, 0x19,
	0x41, 0x21, 0xa6, 0xb0, 0xa8, 0x02, 0x39, 0x9f, 0x98, 0x73, 0xcf, 0x0a, 0xc2, 0x68, 0x8f, 0x2f,
	0x6d, 0xb6, 0xfd, 0x67, 0x96, 0x63, 0xcd, 0x0c, 0x9b, 0xb7, 0x22, 0x87, 0x17, 0x26, 0x43, 0x91,
	0x77, 0xa6, 0x3d, 0x1f, 0x13, 0x5f, 0x4e, 0x55, 0x53, 0xb5, 0x3c, 0x5e, 0xda, 0x4a, 0x09, 0x0a,
	0x31, 0x0d, 0x56, 0x24, 0x28, 0xaf, 0x0a, 0xaa, 0xf2, 0x77, 0x12, 0x6e, 0x5f, 0x79, 0xf6, 0x22,
	0x07, 0x76, 0x4c, 0xdb, 0xf0, 0x7d, 0x6b, 0x62, 0x99, 0x7c, 0xa7, 0xfb, 0x72, 0xa2, 0x9a, 0xaa,
	0x95, 0x1b, 0xed, 0x4f, 0x3a, 0xcb, 0xd5, 0xd6, 0x0a, 0x19, 0x5e, 0x27, 0x5f, 0x29, 0x23, 0xb9,
	0x56, 0xc6, 0x1f, 0x09, 0x28, 0xaf, 0xe2, 0xd1, 0x03, 0xa8, 0xb4, 0x7a, 0xcd, 0xe1, 0x50, 0xeb,
	0x6a, 0xad, 0xa6, 0xae, 0xf5, 0x8f, 0xd6, 0x9a, 0x5c, 0x84, 0x5c, 0x0b, 0x6b, 0xba, 0xd6, 0x6a,
	0xf6, 0x84, 0x5c, 0x0f, 0x3b, 0xad, 0x63, 0xac, 0xe9, 0xa7, 0x52, 0x12, 0x95, 0x01, 0xda, 0x9d,
	0xae, 0x76, 0xa4, 0x31, 0x9c, 0x94, 0x62, 0x12, 0xdc, 0xc6, 0x1a, 0xd3, 0xdd, 0x6d, 0x24, 0x41,
	0xb1, 0xdb, 0x69, 0xea, 0xc7, 0xb8, 0x33, 0x1a, 0x34, 0x5b, 0xdf, 0x4b, 0x69, 0xe6, 0x19, 0x76,
	0xf0, 0x89, 0xd6, 0x8a, 0x3c, 0x19, 0xf6, 0x01, 0xf5, 0x7e, 0xbf, 0x27, 0x65, 0xd1, 0x2e, 0x94,
	0x8e, 0x07, 0x6d, 0x76, 0x54, 0xe0, 0x7e, 0xaf, 0x77, 0x3c, 0x90, 0x72, 0x8c, 0x4c, 0xb8, 0xa4,
	0xbc, 0xf2, 0x4b, 0x02, 0xe4, 0x16, 0xbf, 0xf4, 0xc5, 0xae, 0x0c, 0x98, 0x8d, 0x9e, 0x1f, 0xa0,
	0x3b, 0x90, 0x71, 0x0d, 0x8f, 0x38, 0x41, 0x74, 0x3a, 0x45, 0xd6, 0xe5, 0x2d, 0x87, 0x5f, 0xc5,
	0xc3, 0x48, 0x8b, 0x1f, 0x6d, 0x70, 0x29, 0x89, 0x6e, 0x39, 0xc2, 0x50, 0x06, 0x70, 0xfb, 0x80,
	0x04, 0x57, 0x24, 0x70, 0xd5, 0xb5, 0xf7, 0x73, 0x28, 0x89, 0x97, 0x2f, 0x8e, 0xd7, 0x24, 0x3f,
	0x5e, 0x45, 0x46, 0x27, 0xc2, 0xa7, 0x38, 0x20, 0xf7, 0x2c, 0x3f, 0x46, 0x69, 0x11, 0xff, 0xba,
	0xaa, 0xee, 0x41, 0xde, 0x35, 0xa6, 0x64, 0xe4, 0x5b, 0xef, 0x17, 0x9b, 0x39, 0xc7, 0x1c, 0x43,
	0xeb, 0x3d, 0x41, 0xf7, 0x01, 0xf8, 0x62, 0x40, 0xcf, 0x89, 0xc3, 0x0f, 0x92, 0x3c, 0xe6, 0xe1,
	0x3a, 0x73, 0x28, 0xbf, 0x25, 0xe0, 0xee, 0x15, 0x2f, 0xf4, 0x5d, 0xea, 0xf8, 0x04, 0x61, 0x28,
	0xaf, 0xfe, 0xba, 0xf0, 0x39, 0xdd, 0xb0, 0x63, 0x25, 0x37, 0xce, 0x8d, 0x1e, 0xc2, 0x8e, 0x43,
	0xde, 0x05, 0xa3, 0x58, 0x56, 0xe2, 0xba, 0x50, 0x62, 0xee, 0xc1, 0x32, 0xb3, 0xbf, 0x12, 0x20,
	0x8b, 0x39, 0xbf, 0x61, 0x7f, 0xff, 0xe7, 0x8f, 0x1b, 0xfb, 0x8f, 0x60, 0xbf, 0x54, 0x1f, 0xfd,
	0x09, 0xe9, 0xb2, 0xbf, 0xae, 0x17, 0x86, 0x7f, 0xbe, 0xf8, 0x8f, 0x60, 0xcf, 0x8a, 0x0a, 0x72,
	0x9b, 0xd8, 0xe4, 0xa6, 0xc9, 0xef, 0x7f, 0x00, 0xc5, 0xa4, 0xb3, 0x6b, 0x72, 0xdd, 0x2f, 0xad,
	0x7c, 0xa6, 0x57, 0xdd, 0x28, 0x7c, 0x4a, 0x6d, 0xc3, 0x99, 0xaa, 0xd4, 0x9b, 0xd6, 0xa7, 0xc4,
	0xe1, 0x99, 0xd5, 0xc5, 0x92, 0xe1, 0x5a, 0xfe, 0xc7, 0xfe, 0x4a, 0x9f, 0x2f, 0x3c, 0x67, 0x19,
	0x0e, 0x79, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x7e, 0xe9, 0x20, 0xc7, 0x0e, 0x00,
	0x00,
}
