//  Copyright 2021 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: daisy/logger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	reflect "reflect"

	logging "cloud.google.com/go/logging"
	gomock "github.com/golang/mock/gomock"

	daisy "github.com/GoogleCloudPlatform/compute-image-tools/daisy"
)

// MockDaisyLogger is a mock of Logger interface.
type MockDaisyLogger struct {
	ctrl     *gomock.Controller
	recorder *MockDaisyLoggerMockRecorder
}

// MockDaisyLoggerMockRecorder is the mock recorder for MockDaisyLogger.
type MockDaisyLoggerMockRecorder struct {
	mock *MockDaisyLogger
}

// NewMockDaisyLogger creates a new mock instance.
func NewMockDaisyLogger(ctrl *gomock.Controller) *MockDaisyLogger {
	mock := &MockDaisyLogger{ctrl: ctrl}
	mock.recorder = &MockDaisyLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaisyLogger) EXPECT() *MockDaisyLoggerMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockDaisyLogger) Flush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Flush")
}

// Flush indicates an expected call of Flush.
func (mr *MockDaisyLoggerMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockDaisyLogger)(nil).Flush))
}

// ReadSerialPortLogs mocks base method.
func (m *MockDaisyLogger) ReadSerialPortLogs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSerialPortLogs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ReadSerialPortLogs indicates an expected call of ReadSerialPortLogs.
func (mr *MockDaisyLoggerMockRecorder) ReadSerialPortLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSerialPortLogs", reflect.TypeOf((*MockDaisyLogger)(nil).ReadSerialPortLogs))
}

// WriteLogEntry mocks base method.
func (m *MockDaisyLogger) WriteLogEntry(e *daisy.LogEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteLogEntry", e)
}

// WriteLogEntry indicates an expected call of WriteLogEntry.
func (mr *MockDaisyLoggerMockRecorder) WriteLogEntry(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteLogEntry", reflect.TypeOf((*MockDaisyLogger)(nil).WriteLogEntry), e)
}

// WriteSerialPortLogs mocks base method.
func (m *MockDaisyLogger) WriteSerialPortLogs(w *daisy.Workflow, instance string, buf bytes.Buffer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteSerialPortLogs", w, instance, buf)
}

// WriteSerialPortLogs indicates an expected call of WriteSerialPortLogs.
func (mr *MockDaisyLoggerMockRecorder) WriteSerialPortLogs(w, instance, buf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteSerialPortLogs", reflect.TypeOf((*MockDaisyLogger)(nil).WriteSerialPortLogs), w, instance, buf)
}

// MockcloudLogWriter is a mock of cloudLogWriter interface.
type MockcloudLogWriter struct {
	ctrl     *gomock.Controller
	recorder *MockcloudLogWriterMockRecorder
}

// MockcloudLogWriterMockRecorder is the mock recorder for MockcloudLogWriter.
type MockcloudLogWriterMockRecorder struct {
	mock *MockcloudLogWriter
}

// NewMockcloudLogWriter creates a new mock instance.
func NewMockcloudLogWriter(ctrl *gomock.Controller) *MockcloudLogWriter {
	mock := &MockcloudLogWriter{ctrl: ctrl}
	mock.recorder = &MockcloudLogWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcloudLogWriter) EXPECT() *MockcloudLogWriterMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockcloudLogWriter) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockcloudLogWriterMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockcloudLogWriter)(nil).Flush))
}

// Log mocks base method.
func (m *MockcloudLogWriter) Log(e logging.Entry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", e)
}

// Log indicates an expected call of Log.
func (mr *MockcloudLogWriterMockRecorder) Log(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockcloudLogWriter)(nil).Log), e)
}
