#!/bin/bash

# Remove unnecessary packages.
chroot $target apt-get -y autoremove

# Remove GCE unstable and staging repos.
rm -rf $target/etc/apt/sources.list.d/google-cloud-staging.list
rm -rf $target/etc/apt/sources.list.d/google-cloud-unstable.list

# Leave a baseline apt cache on the disk.
chroot $target apt-get clean
chroot $target apt-get update

# Cleanup logs and caches
rm -f $target/etc/resolv.conf \
      $target/etc/mailname \
      $target/etc/machine-id \
      $target/usr/bin/qemu-* \
      $target/var/lib/dbus/machine-id \
      $target/var/log/alternatives.log \
      $target/var/log/apt/* \
      $target/var/log/bootstrap.log \
      $target/var/log/dpkg.log \
      $target/var/log/install_packages.list

# Empty file needed for on-boot generation.
> $target/etc/machine-id

rm -rf $target/var/log/fai

shred --remove $target/etc/ssh/ssh_host_*

fstrim $target
