#!/bin/bash

# Untar secure boot keys.
chroot $target tar -C /boot/efi/EFI/Google/gsetup -xzf /boot/efi/EFI/Google/gsetup/secure-boot-keys.tar.gz
chroot $target rm -rf /boot/efi/EFI/Google/gsetup/secure-boot-keys.tar.gz

# Remove unnecessary packages.
chroot $target apt-get -y autoremove

# Remove GCE unstable and staging repos.
rm -rf $target/etc/apt/sources.list.d/google-cloud-staging.list
rm -rf $target/etc/apt/sources.list.d/google-cloud-unstable.list

# Leave a baseline apt cache on the disk.
chroot $target apt-get clean
chroot $target apt-get update

# Cleanup logs and caches
rm -f $target/etc/resolv.conf \
      $target/etc/mailname \
      $target/etc/machine-id \
      $target/usr/bin/qemu-* \
      $target/var/lib/dbus/machine-id \
      $target/var/log/alternatives.log \
      $target/var/log/apt/* \
      $target/var/log/bootstrap.log \
      $target/var/log/dpkg.log \
      $target/var/log/install_packages.list

rm -rf $target/var/log/fai

shred --remove $target/etc/ssh/ssh_host_*

fstrim $target
