# Config for Google Ops Agent to collect nginx logs and metrics.
# https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/third-party/nginx
logging:
  receivers:
    nginx_access:
      type: nginx_access
      include_paths:
      - /var/log/nginx/ssl-access.log
    nginx_error:
      type: nginx_error
  service:
    pipelines:
      nginx:
        receivers:
        - nginx_access
        - nginx_error
metrics:
  receivers:
    nginx:
      type: nginx
      stub_status_url: http://127.0.0.1:80/status
  service:
    pipelines:
      nginx:
        receivers:
        - nginx
