# plank:
#   job_url_template: 'https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if ne .Spec.Refs.Org ""}}{{if ne .Spec.Refs.Org "kubernetes"}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{else if ne .Spec.Refs.Repo "kubernetes"}}/{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
#   report_template: '[Full PR test history](https://k8s-gubernator.appspot.com/pr/{{if eq .Spec.Refs.Org "kubernetes"}}{{if eq .Spec.Refs.Repo "kubernetes"}}{{else}}{{.Spec.Refs.Repo}}/{{end}}{{else}}{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{end}}{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://k8s-gubernator.appspot.com/pr/{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}). Please help us cut down on flakes by [linking to](https://github.com/kubernetes/community/blob/master/contributors/devel/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/issues?q=is:issue+is:open) when you hit one in your PR.'
# plank:
#  job_url_template: 'https://k8s-gubernator.appspot.com/build/gce-daisy-test/{{if eq .Spec.Type "presubmit"}}pr-logs/pull/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}pr-logs/pull/batch{{else}}logs{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
#  report_template: '[Full PR test history](https://k8s-gubernator.appspot.com/pr/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://k8s-gubernator.appspot.com/pr/{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).'

sinker:
 resync_period: 1h
 max_prowjob_age: 48h
 max_pod_age: 12h

prowjob_namespace: default
pod_namespace: test-pods

triggers:
- repos:
  - GoogleCloudPlatform/compute-image-tools
  trusted_org: GoogleCloudPlatform

presubmits:
 GoogleCloudPlatform/compute-image-tools:
 - name: presubmit-unittests
   agent: kubernetes
   always_run: true
   trigger: "(?m)^/unit(tests)?$"
   rerun_command: "/unit"
   context: prow/presubmit/unittests
   spec:
    containers:
    - image: gcr.io/compute-image-tools-test/unittests:latest
      volumeMounts:
      - name: codecov
        mountPath: /etc/codecov
        readOnly: true
    volumes:
    - name: codecov
      secret:
       secretName: codecov
 - name: presubmit-gocheck
   agent: kubernetes
   always_run: true
   run_if_changed: ".*\\.go$"
   trigger: "(?m)/gocheck$"
   rerun_command: "/gocheck"
   context: prow/presubmit/gocheck
   spec:
    containers:
    - image: gcr.io/compute-image-tools/test/gocheck:latest

periodics:
 - interval: 6h
   agent: kubernetes
   name: ci-daisy-e2e
   spec:
    containers:
    - image: gcr.io/compute-image-tools-test/daisy-e2e:latest
      args:
      - "--tests=e2e_tests"
      env:
      - name: REPO_OWNER
        value: GoogleCloudPlatform
      - name: REPO_NAME
        value: compute-image-tools
      volumeMounts:
      - name: compute-image-tools-test-service-account
        mountPath: /etc/compute-image-tools-test-service-account
        readOnly: true
    volumes:
    - name: compute-image-tools-test-service-account
      secret:
       secretName: compute-image-tools-test-service-account
