# Config for Google Ops Agent to collect nginx logs and metrics.
# https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/third-party/nginx
#
# Log file locations from:
#   https://access.redhat.com/documentation/en-us/red_hat_update_infrastructure/4/html/configuring_and_managing_red_hat_update_infrastructure/assembly_cmg-config-files-status-codes-log-files
logging:
  receivers:
    nginx_access:
      type: nginx_access
    nginx_error:
      type: nginx_error
    rhui_manager:
      type: files
      include_paths:
      - /root/.rhui/rhui.log*
    rhui_sync:
      type: files
      include_paths:
      - /var/log/rhui-subscription-sync.log
  processors:
    # Extracts the timestamp to a structured field. Example message:
    # 2022-06-10 17:30:01,964 - Successfully connected to [http://localhost:24817].
    parse_rhui_log:
      type: parse_regex
      regex: "^(?<time>.*?) - (?<message>.*)$"
      time_key: time
      time_format: "%Y-%m-%d %H:%M:%S,%L"
  service:
    pipelines:
      nginx:
        receivers:
        - nginx_access
        - nginx_error
      rhui:
        receivers:
        - rhui_manager
        - rhui_sync
        processors:
        - parse_rhui_log
metrics:
  receivers:
    nginx:
      type: nginx
      stub_status_url: http://127.0.0.1:80/status
  service:
    pipelines:
      nginx:
        receivers:
        - nginx
